### ISSUE TITLE
device ID cannot be null

### ISSUE THREAD

**Issue by sabirmgd** [Azure/azure-iot-sdk-java#103]
Hi Guys I am trying to stimulate an IoT device from windows 10 laptop by using MQTT in eclipse 

- **OS and version used:** <windows 10>
- **Java runtime used:** java version 1.8

# Description of the issue:
whenever I execute the code, it tells me Device ID cannot be null! while I am already setting the device ID

code:
`App code package com.mycompany.app.simulated_device;
import com.microsoft.azure.sdk.iot.device.DeviceClient;
import com.microsoft.azure.sdk.iot.device.IotHubClientProtocol;
import com.microsoft.azure.sdk.iot.device.Message;
import com.microsoft.azure.sdk.iot.device.IotHubStatusCode;
import com.microsoft.azure.sdk.iot.device.IotHubEventCallback;
import com.microsoft.azure.sdk.iot.device.MessageCallback;
import com.microsoft.azure.sdk.iot.device.IotHubMessageResult;
import com.google.gson.Gson;

import java.io.IOException;
import java.net.URISyntaxException;
import java.util.Random;
import java.util.concurrent.Executors;
import java.util.concurrent.ExecutorService;

public class App 
{
	
	private static class TelemetryDataPoint {
		  public String deviceId;
		  public double temperature;
		  public double humidity;

		  public String serialize() {
		    Gson gson = new Gson();
		    return gson.toJson(this);
		  }
		}
	

	
	
	
	private static String connString = "";
	private static IotHubClientProtocol protocol = IotHubClientProtocol.MQTT;
	private static String deviceId = "Training";
	private static DeviceClient client;
	
	
	
	
	
	private static class EventCallback implements IotHubEventCallback
	{
	  public void execute(IotHubStatusCode status, Object context) {
	    System.out.println("IoT Hub responded to message with status: " + status.name());

	    if (context != null) {
	      synchronized (context) {
	        context.notify();
	      }
	    }
	  }
	}
	
	private static class MessageSender implements Runnable {

		  public void run()  {
		    try {
		      double minTemperature = 20;
		      double minHumidity = 60;
		      Random rand = new Random();

		      while (true) {
		        double currentTemperature = minTemperature + rand.nextDouble() * 15;
		        double currentHumidity = minHumidity + rand.nextDouble() * 20;
		        TelemetryDataPoint telemetryDataPoint = new TelemetryDataPoint();
		        telemetryDataPoint.deviceId = deviceId;
		        telemetryDataPoint.temperature = currentTemperature;
		        telemetryDataPoint.humidity = currentHumidity;

		        String msgStr = telemetryDataPoint.serialize();
		        Message msg = new Message(msgStr);
		        msg.setProperty("temperatureAlert", (currentTemperature > 30) ? "true" : "false");
		        msg.setMessageId(java.util.UUID.randomUUID().toString()); 
		        System.out.println("Sending: " + msgStr);

		        Object lockobj = new Object();
		        EventCallback callback = new EventCallback();
		        client.sendEventAsync(msg, callback, lockobj);

		        synchronized (lockobj) {
		          lockobj.wait();
		        }
		        Thread.sleep(1000);
		      }
		    } catch (InterruptedException e) {
		      System.out.println("Finished.");
		    }
		  }
		}
	
	
	@SuppressWarnings("deprecation")
	public static void main( String[] args ) throws IOException, URISyntaxException {
		  client = new DeviceClient(connString, protocol);
		  client.open();

		  MessageSender sender = new MessageSender();

		  ExecutorService executor = Executors.newFixedThreadPool(1);
		  executor.execute(sender);

		  System.out.println("Press ENTER to exit.");
		  System.in.read();
		  executor.shutdownNow();
		  client.close();
		}
}
`

pom.xml
`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.mycompany.app</groupId>
  <artifactId>simulated-device</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>simulated-device</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
     <dependency>
  <groupId>com.microsoft.azure.sdk.iot</groupId>
  <artifactId>iot-service-client</artifactId>
  <version>1.3.19</version>
</dependency>
<dependency>
  <groupId>com.microsoft.azure.sdk.iot</groupId>
  <artifactId>iot-device-client</artifactId>
  <version>1.1.26</version>
</dependency>
<dependency>
  <groupId>com.google.code.gson</groupId>
  <artifactId>gson</artifactId>
  <version>2.3.1</version>
</dependency>
  </dependencies>
</project>
`

I run the following command on my git bash 
` mvn clean package -DskipTests
`
this one is successful however, the execution:
`mvn exec:java -Dexec.mainClass="com.mycompany.app.simulated_device.App"
`

I got this log

> $ mvn -e exec:java -Dexec.mainClass="com.mycompany.app.simulated_device.App"
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building simulated-device 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ simulated-device ---
[WARNING]
java.lang.IllegalArgumentException: Device ID cannot be null.
        at com.microsoft.azure.sdk.iot.device.DeviceClient.initIotHubClient(DeviceClient.java:566)
        at com.microsoft.azure.sdk.iot.device.DeviceClient.<init>(DeviceClient.java:162)
        at com.mycompany.app.simulated_device.App.main(App.java:97)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
        at java.lang.Thread.run(Thread.java:745)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.710 s
[INFO] Finished at: 2017-06-09T22:29:00+08:00
[INFO] Final Memory: 8M/19M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project simulated-device: An exception occured while executing the Java class. Device ID cannot be null. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project simulated-device: An exception occured while executing the Java class. Device ID cannot be null.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: An exception occured while executing the Java class. Device ID cannot be null.
        at org.codehaus.mojo.exec.ExecJavaMojo.execute(ExecJavaMojo.java:339)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.lang.IllegalArgumentException: Device ID cannot be null.
        at com.microsoft.azure.sdk.iot.device.DeviceClient.initIotHubClient(DeviceClient.java:566)
        at com.microsoft.azure.sdk.iot.device.DeviceClient.<init>(DeviceClient.java:162)
        at com.mycompany.app.simulated_device.App.main(App.java:97)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
        at java.lang.Thread.run(Thread.java:745)
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by timtay-microsoft** [comment]
Hi sabirmgd, sorry you are running into issues here. 

The constructor for DeviceClient is expecting a different kind of key than you are providing. Right now, you are providing a Shared Access Key for your Iot Hub when you need to be providing either a SAS token tied to your specific device or a device connection string. In either of these correct connection strings you will see your device id. 

The expected keys should look like the following:

SAS Token:
HostName=<Host name>;DeviceId=<**_Your device id_**>;SharedAccessSignature=<Your shared access signature>


Device ConnectionString: 
HostName=<Your host name>;DeviceId=<**_Your device id_**>;SharedAccessKey=<SharedAccessKey>

You can get these keys within the device explorer through the Azure portal

![image](https://user-images.githubusercontent.com/28789848/26988096-d80e1120-4d02-11e7-9fe0-bf2204bd6bbd.png)

![image](https://user-images.githubusercontent.com/28789848/26988223-599f0924-4d03-11e7-81de-57471ffb3f13.png)

When you get one of these keys, replace your current connection string and you shouldn't face this issue anymore.

If no devices show up in your device explorer, then you need to create one first.

![image](https://user-images.githubusercontent.com/28789848/26988341-c9699d6e-4d03-11e7-8c0e-ea7a3dc40a8d.png)

Please let me know if you have any problems.

**Comment by sabirmgd** [comment]
thanks! have been stuck for a while and now working like a charm

**Comment by timtay-microsoft** [comment]
Excellent, I'll close this for now then. Feel free to re-open if something comes up.

**Comment by prmathur-microsoft** [comment]
Closing it as per comment above. Feel free to reopen if you see any further issues.
