### ISSUE TITLE
Crashing while reconnecting, MqttAsyncClient is null

### ISSUE THREAD

**Issue by nazmul32** [Azure/azure-iot-sdk-java#1035]
# Context

- Android 10
- Azure IoT SDK Version, 1.28.0 

## Description of the issue
Application is crashing while reconnecting in the latest SDK. This happens in SDK and almost frequent sometimes. I cannot remember any user initiated call that can cause this issue. I will be highly glad to have some insight regarding this.

## Console log of the issue
2020-12-30 17:47:57.086 18113-18652/com.test.iothub E/AndroidRuntime: FATAL EXCEPTION: azure-iot-sdk-ReconnectionTask:91126a52-8c8c-4ce3-9cc7-1f7e0ee9d01a
    Process: com.test.iothub, PID: 18113
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.eclipse.paho.client.mqttv3.MqttAsyncClient.isConnected()' on a null object reference
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.subscribe(Mqtt.java:282)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttMessaging.start(MqttMessaging.java:62)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:201)
        at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:785)
        at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.singleReconnectAttempt(IotHubTransport.java:916)
        at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.reconnect(IotHubTransport.java:865)
        at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.handleDisconnection(IotHubTransport.java:820)
        at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.onConnectionLost(IotHubTransport.java:253)
        at com.microsoft.azure.sdk.iot.device.transport.ReconnectionNotifier$1.run(ReconnectionNotifier.java:21)
        at java.lang.Thread.run(Thread.java:919)

**Comment by bikamani** [comment]
@nazmul32 Could you add some more details about the code exhibiting this issue? Is the device getting disconnected often? What does your application code look like to handle connection status changes?

**Comment by nazmul32** [comment]
Hi @bikamani it was happening for SDK version 1.28.0. My client was getting disconnected often. It was trying to reconnect when it was getting disconnected.

**Comment by timtay-microsoft** [comment]
We're taking a look at this issue now, so I'll keep you posted

**Comment by timtay-microsoft** [comment]
Device client version 1.29.2 has fixed this issue, so I'm closing this issue
