### ISSUE TITLE
[Feature Request] DeviceClient crashes on receiving AMQP message with body as AMQPValue

### ISSUE THREAD

**Issue by DerSchwilk** [Azure/azure-iot-sdk-java#1138]
# Context

- **OS and version used:** Ubuntu 20.04.2 LTS
- **Java runtime used:** 11.0.6
- **SDK version used:** iot-device-client:1.29.2

## Description of the issue
1. I create a DeviceClient via AMQP_WS and open the connection
2. I set a MessageCallback to the client to log incoming messages.
3. I send an AMQP message via [Eclipse Ditto](https://github.com/eclipse/ditto) AMQP to my Azure IoT Hub subscription which is received by the connected DeviceClient. (Eclipse Ditto sets the body of the AMQP message to a new AMQPValue instance)
4. The connection is closed with the error described in the console log.

This seems to be caused by the unchecked casting:

```
log.trace("Converting proton message to iot hub message for {} receiver link with link correlation id {}. Proton message correlation id {}", new Object[]{this.getLinkInstanceType(), this.linkCorrelationId, protonMsg.getCorrelationId()});
        Data d = (Data) protonMsg.getBody();
        byte[] msgBody;
```
(AmqpsReceiverLinkHandler::protonMessageToIoTHubMessage)

Is it feasible to handle the body also when containing AMQPValue instead of Data? (i.e. convertig the AMQPValue Object to bytes)

## Code sample exhibiting the issue
Creating the client:

```
final var client = new DeviceClient("connectionString", IotHubClientProtocol.AMQPS_WS);
client.setMessageCallback(new MessageCallback(), new Object());
client.open();
```

MessageCallback:

```
private static class MessageCallback implements com.microsoft.azure.sdk.iot.device.MessageCallback {

        private static final Logger LOGGER = LoggerFactory.getLogger(MessageCallback.class.getSimpleName());

        @Override
        public IotHubMessageResult execute(final Message message, final Object o) {
            LOGGER.info("Received message with content: <{}>.",
                    new String(message.getBytes(), Message.DEFAULT_IOTHUB_MESSAGE_CHARSET));

            return IotHubMessageResult.COMPLETE;
        }
    }
```

## Console log of the issue
`10:45:49.097 [azure-iot-sdk-ReactorRunner] INFO  c.m.a.s.i.d.t.IotHubTransport - Handling a disconnection event
com.microsoft.azure.sdk.iot.device.exceptions.TransportException: org.apache.qpid.proton.engine.HandlerException: java.lang.ClassCastException: class org.apache.qpid.proton.amqp.messaging.AmqpValue cannot be cast to class org.apache.qpid.proton.amqp.messaging.Data (org.apache.qpid.proton.amqp.messaging.AmqpValue and org.apache.qpid.proton.amqp.messaging.Data are in unnamed module of loader 'app')
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call(AmqpsIotHubConnection.java:1128)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.qpid.proton.engine.HandlerException: java.lang.ClassCastException: class org.apache.qpid.proton.amqp.messaging.AmqpValue cannot be cast to class org.apache.qpid.proton.amqp.messaging.Data (org.apache.qpid.proton.amqp.messaging.AmqpValue and org.apache.qpid.proton.amqp.messaging.Data are in unnamed module of loader 'app')
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:112)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.IotHubReactor.run(IotHubReactor.java:26)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call(AmqpsIotHubConnection.java:1124)
	... 4 common frames omitted
Caused by: java.lang.ClassCastException: class org.apache.qpid.proton.amqp.messaging.AmqpValue cannot be cast to class org.apache.qpid.proton.amqp.messaging.Data (org.apache.qpid.proton.amqp.messaging.AmqpValue and org.apache.qpid.proton.amqp.messaging.Data are in unnamed module of loader 'app')
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsReceiverLinkHandler.protonMessageToIoTHubMessage(AmqpsReceiverLinkHandler.java:188)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsTelemetryReceiverLinkHandler.protonMessageToIoTHubMessage(AmqpsTelemetryReceiverLinkHandler.java:99)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsReceiverLinkHandler.onDelivery(AmqpsReceiverLinkHandler.java:82)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:185)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	... 8 common frames omitted`

AB#9446644

**Comment by timtay-microsoft** [comment]
This strikes me as a bit of an odd use case. Is there a reason why you are sending messages to the device client via Eclipse Ditto rather than using the service client's cloud to device message functionality?

**Comment by timtay-microsoft** [comment]
Marking this as an enhancement because this SDK isn't really designed to handle arbitrary AMQP messages from arbitrary senders.

**Comment by DerSchwilk** [comment]
In this use-case I'm using the Ditto Digital-Twin representation for my devices and the Hub more as a broker. Messages are sent from my service to Ditto which then publishes the message via AMQP to the Hub. Regarding devices telemetry data, this is received by Ditto from the Hub, the Ditto digital-twin is updated and events are emitted to my service.
Thus my service interacts with Eclipse Ditto, which uses the Hub as a broker, which prevents me from using the service client.

**Comment by timtay-microsoft** [comment]
This scenario seems too out of scope to support. The reason the AMQP layer casts the message payload as Data is because IoT Hub will always send AMQP messages with Data payloads. Adding handling for AmqpValue payloads doesn't fit well with this SDK's responsibilities, so I'm marking this as "won't fix"
