### ISSUE TITLE
NullPointerException in ClientState.quiesce iot-device-client:1.29.4

### ISSUE THREAD

**Issue by devzeze** [Azure/azure-iot-sdk-java#1225]
# Context

- **OS and version used:** Android (mostly ver 10 and 11)
- **SDK version used:** iot-device-client:1.29.4

## Description of the issue
Some crashes reported in Crashlytics for version of app that includes iot-device-client:1.29.4.
3 different crashes around ClientState.quiesce

## Console log of the issue
Crashlytics crash info.

========================================

ClientState.java line 1330
org.eclipse.paho.client.mqttv3.internal.ClientState.quiesce

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void org.eclipse.paho.client.mqttv3.internal.CommsCallback.quiesce()  on a null object reference

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.eclipse.paho.client.mqttv3.internal.CommsCallback.quiesce()' on a null object reference
       at org.eclipse.paho.client.mqttv3.internal.ClientState.quiesce(ClientState.java:1330)
       at org.eclipse.paho.client.mqttv3.internal.ClientComms$DisconnectBG.run(ClientComms.java:775)
       at java.lang.Thread.run(Thread.java:923)

========================================

ClientComms.java line 775
org.eclipse.paho.client.mqttv3.internal.ClientComms$DisconnectBG.run

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method org.eclipse.paho.client.mqttv3.internal.ClientState.quiesce(long)  on a null object reference

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.eclipse.paho.client.mqttv3.internal.ClientState.quiesce(long)' on a null object reference
       at org.eclipse.paho.client.mqttv3.internal.ClientComms$DisconnectBG.run(ClientComms.java:775)
       at java.lang.Thread.run(Thread.java:923)

========================================

ClientState.java line 1355
org.eclipse.paho.client.mqttv3.internal.ClientState.quiesce

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void java.util.Vector.clear()' on a null object reference

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.Vector.clear()' on a null object reference
       at org.eclipse.paho.client.mqttv3.internal.ClientState.quiesce(ClientState.java:1355)
       at org.eclipse.paho.client.mqttv3.internal.ClientComms$DisconnectBG.run(ClientComms.java:775)
       at java.lang.Thread.run(Thread.java:923)

**Comment by barustum** [comment]
@devzeze Can you please include a full stack trace that includes the device client sdk lines of code?

**Comment by devzeze** [comment]
@barustum For the Thread that crashed this is all info I got, however I can get for you the stack trace from other threads related with client sdk.

In the meantime, I am trying to collect more info here. I will update you with the results if something new shows up.


com.microsoft.azure.sdk.iot:iot-device-client:1.29.4

========================================

ClientState.java line 1330
org.eclipse.paho.client.mqttv3.internal.ClientState.quiesce

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void org.eclipse.paho.client.mqttv3.internal.CommsCallback.quiesce()  on a null object reference

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.eclipse.paho.client.mqttv3.internal.CommsCallback.quiesce()' on a null object reference
       at org.eclipse.paho.client.mqttv3.internal.ClientState.quiesce(ClientState.java:1330)
       at org.eclipse.paho.client.mqttv3.internal.ClientComms$DisconnectBG.run(ClientComms.java:775)
       at java.lang.Thread.run(Thread.java:923)


Stack trace:

azure-iot-sdk-IotHubSendTask
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubSendTask.run(IotHubSendTask.java:49)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:307)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:302)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

azure-iot-sdk-ConnectionReconnectionTask:086cb86e-a1e9-46a7-8ac2-8334cae7a4a5
       at com.microsoft.azure.sdk.iot.device.DeviceIO.execute(DeviceIO.java:491)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.updateStatus(IotHubTransport.java:1461)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.handleDisconnection(IotHubTransport.java:1027)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.onConnectionLost(IotHubTransport.java:285)
       at com.microsoft.azure.sdk.iot.device.transport.ReconnectionNotifier$1.run(ReconnectionNotifier.java:22)
       at java.lang.Thread.run(Thread.java:923)

azure-iot-sdk-IotHubReceiveTask
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubReceiveTask.run(IotHubReceiveTask.java:53)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:307)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:302)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

AlarmReceiverSyncThread
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at org.eclipse.paho.client.mqttv3.internal.Token.waitForResponse(Token.java:145)
       at org.eclipse.paho.client.mqttv3.internal.Token.waitForCompletion(Token.java:108)
       at org.eclipse.paho.client.mqttv3.MqttToken.waitForCompletion(MqttToken.java:67)
       at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.disconnect(Mqtt.java:157)
       at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttMessaging.stop(MqttMessaging.java:77)
       at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.close(MqttIotHubConnection.java:302)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.close(IotHubTransport.java:429)
       at com.microsoft.azure.sdk.iot.device.DeviceIO.close(DeviceIO.java:265)
       at com.microsoft.azure.sdk.iot.device.InternalClient.closeNow(InternalClient.java:192)
       at com.microsoft.azure.sdk.iot.device.DeviceClient.closeNow(DeviceClient.java:519)
       at com.commend.ims.utils.iot.deviceclient.DeviceClientRegistration.closeNow(DeviceClientRegistration.java:99)
       at com.commend.ims.utils.iot.handler.IoTHandler.destroy(IoTHandler.java:257)
       at com.commend.ims.utils.iot.handler.-$$Lambda$KDAWjRuqDF2132cecib6Xz_z35o.run(-.java:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.os.HandlerThread.run(HandlerThread.java:67)


       

========================================

ClientComms.java line 775
org.eclipse.paho.client.mqttv3.internal.ClientComms$DisconnectBG.run

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method org.eclipse.paho.client.mqttv3.internal.ClientState.quiesce(long)  on a null object reference

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.eclipse.paho.client.mqttv3.internal.ClientState.quiesce(long)' on a null object reference
       at org.eclipse.paho.client.mqttv3.internal.ClientComms$DisconnectBG.run(ClientComms.java:775)
       at java.lang.Thread.run(Thread.java:923)
       

Stack Trace:

azure-iot-sdk-ConnectionReconnectionTask:0a6224ff-3e84-4fe3-89ee-2b9ceafde8f8
       at com.microsoft.azure.sdk.iot.device.DeviceIO.execute(DeviceIO.java:491)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.updateStatus(IotHubTransport.java:1461)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.handleDisconnection(IotHubTransport.java:1027)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.onConnectionLost(IotHubTransport.java:285)
       at com.microsoft.azure.sdk.iot.device.transport.ReconnectionNotifier$1.run(ReconnectionNotifier.java:22)
       at java.lang.Thread.run(Thread.java:923)

azure-iot-sdk-IotHubReceiveTask
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubReceiveTask.run(IotHubReceiveTask.java:53)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:307)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:302)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

AlarmReceiverSyncThread
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at org.eclipse.paho.client.mqttv3.internal.Token.waitForResponse(Token.java:145)
       at org.eclipse.paho.client.mqttv3.internal.Token.waitForCompletion(Token.java:108)
       at org.eclipse.paho.client.mqttv3.MqttToken.waitForCompletion(MqttToken.java:67)
       at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.disconnect(Mqtt.java:157)
       at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttMessaging.stop(MqttMessaging.java:77)
       at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.close(MqttIotHubConnection.java:302)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.close(IotHubTransport.java:429)
       at com.microsoft.azure.sdk.iot.device.DeviceIO.close(DeviceIO.java:265)
       at com.microsoft.azure.sdk.iot.device.InternalClient.closeNow(InternalClient.java:192)
       at com.microsoft.azure.sdk.iot.device.DeviceClient.closeNow(DeviceClient.java:519)
       at com.commend.ims.utils.iot.deviceclient.DeviceClientRegistration.closeNow(DeviceClientRegistration.java:99)
       at com.commend.ims.utils.iot.handler.IoTHandler.destroy(IoTHandler.java:257)
       at com.commend.ims.utils.iot.handler.-$$Lambda$KDAWjRuqDF2132cecib6Xz_z35o.run(-.java:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.os.HandlerThread.run(HandlerThread.java:67)

azure-iot-sdk-IotHubSendTask
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubSendTask.run(IotHubSendTask.java:49)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:307)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:302)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)



========================================

ClientState.java line 1355
org.eclipse.paho.client.mqttv3.internal.ClientState.quiesce

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void java.util.Vector.clear()' on a null object reference

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.Vector.clear()' on a null object reference
       at org.eclipse.paho.client.mqttv3.internal.ClientState.quiesce(ClientState.java:1355)
       at org.eclipse.paho.client.mqttv3.internal.ClientComms$DisconnectBG.run(ClientComms.java:775)
       at java.lang.Thread.run(Thread.java:923)

Stack Trace:

azure-iot-sdk-IotHubSendTask
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubSendTask.run(IotHubSendTask.java:49)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:307)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:302)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)


AlarmReceiverSyncThread
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at org.eclipse.paho.client.mqttv3.internal.Token.waitForResponse(Token.java:145)
       at org.eclipse.paho.client.mqttv3.internal.Token.waitForCompletion(Token.java:108)
       at org.eclipse.paho.client.mqttv3.MqttToken.waitForCompletion(MqttToken.java:67)
       at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.disconnect(Mqtt.java:157)
       at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttMessaging.stop(MqttMessaging.java:77)
       at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.close(MqttIotHubConnection.java:302)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.close(IotHubTransport.java:429)
       at com.microsoft.azure.sdk.iot.device.DeviceIO.close(DeviceIO.java:265)
       at com.microsoft.azure.sdk.iot.device.InternalClient.closeNow(InternalClient.java:192)
       at com.microsoft.azure.sdk.iot.device.DeviceClient.closeNow(DeviceClient.java:519)
       at com.commend.ims.utils.iot.deviceclient.DeviceClientRegistration.closeNow(DeviceClientRegistration.java:99)
       at com.commend.ims.utils.iot.handler.IoTHandler.destroy(IoTHandler.java:257)
       at com.commend.ims.utils.iot.handler.-$$Lambda$KDAWjRuqDF2132cecib6Xz_z35o.run(-.java:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.os.HandlerThread.run(HandlerThread.java:67)

azure-iot-sdk-ConnectionReconnectionTask:6768d2fc-194e-4ede-aab9-1c4873ade88f
       at com.microsoft.azure.sdk.iot.device.DeviceIO.execute(DeviceIO.java:491)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.updateStatus(IotHubTransport.java:1461)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.handleDisconnection(IotHubTransport.java:1027)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.onConnectionLost(IotHubTransport.java:285)
       at com.microsoft.azure.sdk.iot.device.transport.ReconnectionNotifier$1.run(ReconnectionNotifier.java:22)
       at java.lang.Thread.run(Thread.java:923)

azure-iot-sdk-IotHubReceiveTask
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubReceiveTask.run(IotHubReceiveTask.java:53)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:307)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:302)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

**Comment by barustum** [comment]
It seems like this issue is happening when trying to close the device client. Since we don't have a consistent repro, I will try and set up a stress test to open and close a client connection to see if I can reproduce this issue.

**Comment by barustum** [comment]
I've set up a quick sample to run over the weekend, hopefully to be able to reproduce this issue. 

@devzeze How often does it repro for you?

**Comment by devzeze** [comment]
We have a few, maybe something like 5% of our users have this crash per week.

We also assume for now this occurs while app is being closed/background otherwise would be a much serious issue.

**Comment by barustum** [comment]
Thanks for the info. I am still running a sample to open and close clients, and have yet to his this issue. I'll keep you posted.

**Comment by devzeze** [comment]
Hi, any new updates?

Is there any other way I can help? Any feedback so we can try to reproduce in our automated tests also?

Although our automated tests run much more frequently, most of crashes came from users.

**Comment by barustum** [comment]
Hello,

Unfortunately, I was not able to reproduce the issue locally. And maybe because it seems like this issue is happening when the client is closed ungracefully. For that reason, I am planning on doing some testing on Android simulator to open a client and close it ungracefully to hopefully be able to reproduce the issue. I'll keep you up to date.

I really appreciate your patience.

Thanks

**Comment by barustum** [comment]
@devzeze We have not been able to reproduce the problem. It's difficult to know where the issue is without having some sort of an idea on what the scenario is. From your app monitoring telemetry, is it possible to figure out the events that led to the ungraceful closer of the app/client?

**Comment by devzeze** [comment]
Hi,

thank you for the help and time spent already.

I will try to gather more info from devices that had the crash.

Will came back when have some results. Might take some time.

**Comment by devzeze** [comment]
Hi,

since some days ago I have my data from Crashlytics exported to Bigquery and having an overview of the data today I came across an interesting result.

From all exceptions I got, getting a unique table with exception, manufacturer, model I get this.

issue_title	                          manufacturer         model
ClientComms.java line 775	  samsung	         SM-G980F
ClientComms.java line 775	  samsung	         SM-G770F
ClientComms.java line 775	  samsung	         SM-A505FN
ClientComms.java line 775	  samsung	         SM-G973F
ClientComms.java line 775	  samsung	         SM-G975F
ClientComms.java line 775	  samsung	         SM-G981B
ClientComms.java line 775	  samsung	         SM-N975F
ClientState.java line 1355	  samsung	         SM-G975F
ClientState.java line 1355	  samsung	         SM-G973F
ClientState.java line 1355	  samsung	         SM-G770F


It seems this issue is related with Samsung devices that might have an mechanism to kill processes when app is not in use or goes to background.

**Comment by drwill-ms** [comment]
Hi @devzeze. Our teammate Basel is out on family vacation, so I'm picking up the conversation here.

Basel had a note earlier about this looking like an ungraceful shutdown, and your telemetry from Crashlytics seems to support that as well. What do you want to do with it, given that? If an app is being ungracefully closed, in my mind anyway, all bets are off and processes might crash.

**Comment by devzeze** [comment]
Hi,

I will close the issue.

This seems to happen on specific brand of devices, in doze mode so there is not much to do for now.

I am trying to fix this by avoiding this situation in future.

Thank you for the help.
