### ISSUE TITLE
MQTT_WS Disconnects and Reconnects every 2 minutes

### ISSUE THREAD

**Issue by nenright** [Azure/azure-iot-sdk-java#1258]
I haven't found any documentation to explain the behavior we're seeing.  Basically it looks like IoT Hub is resetting our MQTT_WS connection every two minutes:

from our IoT Edge module:
```
2021-06-30 14:29:53,170 WARN   ||  Mqtt connection lost   [com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt]
Connection lost (32109) - java.io.EOFException
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:190)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
	... 1 more
2021-06-30 14:29:53,172 INFO   ||  Handling a disconnection event   [com.microsoft.azure.sdk.iot.device.transport.IotHubTransport]
com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Mqtt connection lost
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:74)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connectionLost(Mqtt.java:335)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.connectionLost(CommsCallback.java:304)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:439)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:190)
	at java.lang.Thread.run(Thread.java:748)
Caused by: Connection lost (32109) - java.io.EOFException
	... 2 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
	... 1 more
2021-06-30 14:29:53,173 WARN   ||  Updating transport status to new status DISCONNECTED_RETRYING with reason NO_NETWORK   [com.microsoft.azure.sdk.iot.device.transport.IotHubTransport]
com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Mqtt connection lost
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:74)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connectionLost(Mqtt.java:335)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.connectionLost(CommsCallback.java:304)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:439)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:190)
	at java.lang.Thread.run(Thread.java:748)
Caused by: Connection lost (32109) - java.io.EOFException
	... 2 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
	... 1 more
Connection Status: Retrying
2021-06-30 14:29:53,771 INFO   ||  Updating transport status to new status CONNECTED with reason CONNECTION_OK   [com.microsoft.azure.sdk.iot.device.transport.IotHubTransport]
Connection Status: Connected
2021-06-30 14:31:53,457 WARN   ||  Mqtt connection lost   [com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt]
Connection lost (32109) - java.io.EOFException
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:190)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
	... 1 more
2021-06-30 14:31:53,459 INFO   ||  Handling a disconnection event   [com.microsoft.azure.sdk.iot.device.transport.IotHubTransport]
com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Mqtt connection lost
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:74)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connectionLost(Mqtt.java:335)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.connectionLost(CommsCallback.java:304)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:439)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:190)
	at java.lang.Thread.run(Thread.java:748)
Caused by: Connection lost (32109) - java.io.EOFException
	... 2 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
	... 1 more
2021-06-30 14:31:53,461 WARN   ||  Updating transport status to new status DISCONNECTED_RETRYING with reason NO_NETWORK   [com.microsoft.azure.sdk.iot.device.transport.IotHubTransport]
com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Mqtt connection lost
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:74)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connectionLost(Mqtt.java:335)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.connectionLost(CommsCallback.java:304)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:439)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:190)
	at java.lang.Thread.run(Thread.java:748)
Caused by: Connection lost (32109) - java.io.EOFException
	... 2 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
	... 1 more
Connection Status: Retrying
2021-06-30 14:31:54,011 INFO   ||  Updating transport status to new status CONNECTED with reason CONNECTION_OK   [com.microsoft.azure.sdk.iot.device.transport.IotHubTransport]
Connection Status: Connected
```  

from the edgeHub module:
```
021-06-30 14:29:53.170 +00:00 [WRN] - Error reading transport. CorrelationId 2c51d8ab
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> System.Net.WebSockets.WebSocketException (0x80004005): An exception caused the WebSocket to enter the Aborted state. Please see the InnerException, if present, for more details.
   at System.Net.WebSockets.ManagedWebSocket.CloseWithReceiveErrorAndThrowAsync(WebSocketCloseStatus closeStatus, WebSocketError error, Exception innerException)
   at System.Net.WebSockets.ManagedWebSocket.HandleReceivedCloseAsync(MessageHeader header, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.ServerWebSocketChannel.DoReadBytes(IByteBuffer byteBuffer) in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/ServerWebSocketChannel.cs:line 239
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.ServerWebSocketChannel.DoBeginRead() in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/ServerWebSocketChannel.cs:line 133
<6> 2021-06-30 14:29:53.171 +00:00 [INF] - Transport aborted. CorrelationId 2c51d8ab
<6> 2021-06-30 14:29:53.171 +00:00 [INF] - Request finished in 120002.6503ms 101
<4> 2021-06-30 14:29:53.171 +00:00 [WRN] - Closing connection for device: device1/module1, scope: ExceptionCaught, System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> System.Net.WebSockets.WebSocketException (0x80004005): An exception caused the WebSocket to enter the Aborted state. Please see the InnerException, if present, for more details.
   at System.Net.WebSockets.ManagedWebSocket.CloseWithReceiveErrorAndThrowAsync(WebSocketCloseStatus closeStatus, WebSocketError error, Exception innerException)
   at System.Net.WebSockets.ManagedWebSocket.HandleReceivedCloseAsync(MessageHeader header, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.ServerWebSocketChannel.DoReadBytes(IByteBuffer byteBuffer) in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/ServerWebSocketChannel.cs:line 239
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.ServerWebSocketChannel.DoBeginRead() in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/ServerWebSocketChannel.cs:line 133, 2c51d8ab
<6> 2021-06-30 14:29:53.172 +00:00 [INF] - Disposing MessagingServiceClient for device Id device1/module1 because of exception - System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> System.Net.WebSockets.WebSocketException (0x80004005): An exception caused the WebSocket to enter the Aborted state. Please see the InnerException, if present, for more details.
   at System.Net.WebSockets.ManagedWebSocket.CloseWithReceiveErrorAndThrowAsync(WebSocketCloseStatus closeStatus, WebSocketError error, Exception innerException)
   at System.Net.WebSockets.ManagedWebSocket.HandleReceivedCloseAsync(MessageHeader header, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.ServerWebSocketChannel.DoReadBytes(IByteBuffer byteBuffer) in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/ServerWebSocketChannel.cs:line 239
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.ServerWebSocketChannel.DoBeginRead() in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/ServerWebSocketChannel.cs:line 133
<6> 2021-06-30 14:29:53.172 +00:00 [INF] - Setting device proxy inactive for device Id device1/module1
<6> 2021-06-30 14:29:53.172 +00:00 [INF] - Removing device connection for device device1/module1 with removeCloudConnection flag 'True'.
<6> 2021-06-30 14:29:53.172 +00:00 [INF] - Closing receiver in cloud proxy 69a39b5d-73ee-4290-927d-7a6fb7dfe878 for device1/module1
<6> 2021-06-30 14:29:53.172 +00:00 [INF] - Closed cloud proxy 69a39b5d-73ee-4290-927d-7a6fb7dfe878 for device1/module1
<6> 2021-06-30 14:29:53.172 +00:00 [INF] - Device connection removed for device device1/module1
<6> 2021-06-30 14:29:53.172 +00:00 [INF] - Remove device connection for device device1/module1
<6> 2021-06-30 14:29:53.172 +00:00 [INF] - Transport closed. CorrelationId 2c51d8ab
<6> 2021-06-30 14:29:53.413 +00:00 [INF] - Updated reported properties for device1/$edgeHub
<6> 2021-06-30 14:29:53.454 +00:00 [INF] - Request starting HTTP/1.1 GET https://device1-eflow:443/$iothub/websocket?iothub-no-client-cert=true
<6> 2021-06-30 14:29:53.454 +00:00 [INF] - Processed MQTT WebSocket request with CorrelationId 72fc2dc6-7214-41b6-b8b0-711fc655db30
<6> 2021-06-30 14:29:53.762 +00:00 [INF] - Client device1/module1 in device scope authenticated locally.
<6> 2021-06-30 14:29:53.762 +00:00 [INF] - Successfully generated identity for clientId device1/module1 and username hubname.azure-devices.net/device1/module1/?api-version=2020-09-30&DeviceClientType=com.microsoft.azure.sdk.iot.iot-device-client%2F1.30.2%20%281.8.0_212%3B%20Linux%3B%20amd64%29
<6> 2021-06-30 14:29:53.762 +00:00 [INF] - ClientAuthenticated, device1/module1, 6f30add6
<6> 2021-06-30 14:29:53.763 +00:00 [INF] - New device connection for device device1/module1
<6> 2021-06-30 14:29:53.763 +00:00 [INF] - Client device1/module1 connected to edgeHub, processing existing subscriptions.
<6> 2021-06-30 14:29:53.763 +00:00 [INF] - Bind device proxy for device device1/module1
<6> 2021-06-30 14:29:53.763 +00:00 [INF] - Binding message channel for device Id device1/module1
<6> 2021-06-30 14:29:53.763 +00:00 [INF] - Processing pending subscriptions for device1/module1
<6> 2021-06-30 14:29:53.763 +00:00 [INF] - Attempting to connect to IoT Hub for client device1/module1 via AMQP...
<6> 2021-06-30 14:29:53.770 +00:00 [INF] - Processing subscriptions ModuleMessages, TwinResponse, DesiredPropertyUpdates, Methods for client device1/module1.
<6> 2021-06-30 14:29:53.771 +00:00 [INF] - Set subscriptions from session state for device1/module1
<6> 2021-06-30 14:29:53.916 +00:00 [INF] - Cloud connection for device1/module1 is True
<6> 2021-06-30 14:29:53.916 +00:00 [INF] - Connection status for device1/module1 changed to ConnectionEstablished
<6> 2021-06-30 14:29:53.916 +00:00 [INF] - Client device1/module1 connected to cloud, processing existing subscriptions.
<6> 2021-06-30 14:29:53.916 +00:00 [INF] - Skipping device1/module1 for subscription processing, as it is currently being processed.
<6> 2021-06-30 14:29:53.916 +00:00 [INF] - Created cloud proxy for client device1/module1 via AMQP, with client operation timeout 20 seconds.
<6> 2021-06-30 14:29:53.916 +00:00 [INF] - Initialized cloud proxy 2caa7f93-af34-4c10-bd1e-ef44f1cc77ea for device1/module1
<6> 2021-06-30 14:29:53.916 +00:00 [INF] - Created cloud connection for client device1/module1
<6> 2021-06-30 14:29:54.019 +00:00 [INF] - Processing pending subscriptions for device1/module1
<6> 2021-06-30 14:29:54.019 +00:00 [INF] - Processing pending subscriptions for device1/module1
<6> 2021-06-30 14:29:54.019 +00:00 [INF] - Processing pending subscriptions for device1/module1
<6> 2021-06-30 14:29:54.019 +00:00 [INF] - Processing pending subscriptions for device1/module1
<6> 2021-06-30 14:29:58.646 +00:00 [INF] - Updated reported properties for device1/$edgeHub
<6> 2021-06-30 14:30:24.557 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<4> 2021-06-30 14:31:53.456 +00:00 [WRN] - Error reading transport. CorrelationId 6f30add6
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> System.Net.WebSockets.WebSocketException (0x80004005): An exception caused the WebSocket to enter the Aborted state. Please see the InnerException, if present, for more details.
   at System.Net.WebSockets.ManagedWebSocket.CloseWithReceiveErrorAndThrowAsync(WebSocketCloseStatus closeStatus, WebSocketError error, Exception innerException)
   at System.Net.WebSockets.ManagedWebSocket.HandleReceivedCloseAsync(MessageHeader header, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.ServerWebSocketChannel.DoReadBytes(IByteBuffer byteBuffer) in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/ServerWebSocketChannel.cs:line 239
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.ServerWebSocketChannel.DoBeginRead() in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/ServerWebSocketChannel.cs:line 133
<6> 2021-06-30 14:31:53.457 +00:00 [INF] - Transport aborted. CorrelationId 6f30add6
<6> 2021-06-30 14:31:53.457 +00:00 [INF] - Request finished in 120003.4688ms 101
<4> 2021-06-30 14:31:53.458 +00:00 [WRN] - Closing connection for device: device1/module1, scope: ExceptionCaught, System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> System.Net.WebSockets.WebSocketException (0x80004005): An exception caused the WebSocket to enter the Aborted state. Please see the InnerException, if present, for more details.
   at System.Net.WebSockets.ManagedWebSocket.CloseWithReceiveErrorAndThrowAsync(WebSocketCloseStatus closeStatus, WebSocketError error, Exception innerException)
   at System.Net.WebSockets.ManagedWebSocket.HandleReceivedCloseAsync(MessageHeader header, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.ServerWebSocketChannel.DoReadBytes(IByteBuffer byteBuffer) in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/ServerWebSocketChannel.cs:line 239
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.ServerWebSocketChannel.DoBeginRead() in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/ServerWebSocketChannel.cs:line 133, 6f30add6
<6> 2021-06-30 14:31:53.458 +00:00 [INF] - Disposing MessagingServiceClient for device Id device1/module1 because of exception - System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> System.Net.WebSockets.WebSocketException (0x80004005): An exception caused the WebSocket to enter the Aborted state. Please see the InnerException, if present, for more details.
   at System.Net.WebSockets.ManagedWebSocket.CloseWithReceiveErrorAndThrowAsync(WebSocketCloseStatus closeStatus, WebSocketError error, Exception innerException)
   at System.Net.WebSockets.ManagedWebSocket.HandleReceivedCloseAsync(MessageHeader header, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.ServerWebSocketChannel.DoReadBytes(IByteBuffer byteBuffer) in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/ServerWebSocketChannel.cs:line 239
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.ServerWebSocketChannel.DoBeginRead() in /home/vsts/work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/ServerWebSocketChannel.cs:line 133
<6> 2021-06-30 14:31:53.458 +00:00 [INF] - Setting device proxy inactive for device Id device1/module1
<6> 2021-06-30 14:31:53.458 +00:00 [INF] - Removing device connection for device device1/module1 with removeCloudConnection flag 'True'.
<6> 2021-06-30 14:31:53.459 +00:00 [INF] - Closing receiver in cloud proxy 2caa7f93-af34-4c10-bd1e-ef44f1cc77ea for device1/module1
<6> 2021-06-30 14:31:53.459 +00:00 [INF] - Closed cloud proxy 2caa7f93-af34-4c10-bd1e-ef44f1cc77ea for device1/module1
<6> 2021-06-30 14:31:53.459 +00:00 [INF] - Device connection removed for device device1/module1
<6> 2021-06-30 14:31:53.459 +00:00 [INF] - Remove device connection for device device1/module1
<6> 2021-06-30 14:31:53.459 +00:00 [INF] - Transport closed. CorrelationId 6f30add6
<6> 2021-06-30 14:31:53.695 +00:00 [INF] - Request starting HTTP/1.1 GET https://device1-eflow:443/$iothub/websocket?iothub-no-client-cert=true
<6> 2021-06-30 14:31:53.696 +00:00 [INF] - Processed MQTT WebSocket request with CorrelationId 4aa1aee0-f405-472a-b5ee-8314acfb39db
<6> 2021-06-30 14:31:53.708 +00:00 [INF] - Updated reported properties for device1/$edgeHub
<6> 2021-06-30 14:31:54.002 +00:00 [INF] - Client device1/module1 in device scope authenticated locally.
<6> 2021-06-30 14:31:54.003 +00:00 [INF] - Successfully generated identity for clientId device1/module1 and username hubname.azure-devices.net/device1/module1/?api-version=2020-09-30&DeviceClientType=com.microsoft.azure.sdk.iot.iot-device-client%2F1.30.2%20%281.8.0_212%3B%20Linux%3B%20amd64%29
<6> 2021-06-30 14:31:54.003 +00:00 [INF] - ClientAuthenticated, device1/module1, 320f8302
<6> 2021-06-30 14:31:54.003 +00:00 [INF] - New device connection for device device1/module1
<6> 2021-06-30 14:31:54.003 +00:00 [INF] - Client device1/module1 connected to edgeHub, processing existing subscriptions.
<6> 2021-06-30 14:31:54.003 +00:00 [INF] - Bind device proxy for device device1/module1
<6> 2021-06-30 14:31:54.003 +00:00 [INF] - Binding message channel for device Id device1/module1
<6> 2021-06-30 14:31:54.003 +00:00 [INF] - Processing pending subscriptions for device1/module1
<6> 2021-06-30 14:31:54.003 +00:00 [INF] - Attempting to connect to IoT Hub for client device1/module1 via AMQP...
<6> 2021-06-30 14:31:54.010 +00:00 [INF] - Processing subscriptions ModuleMessages, TwinResponse, DesiredPropertyUpdates, Methods for client device1/module1.
<6> 2021-06-30 14:31:54.011 +00:00 [INF] - Set subscriptions from session state for device1/module1
<6> 2021-06-30 14:31:54.155 +00:00 [INF] - Cloud connection for device1/module1 is True
<6> 2021-06-30 14:31:54.155 +00:00 [INF] - Connection status for device1/module1 changed to ConnectionEstablished
<6> 2021-06-30 14:31:54.155 +00:00 [INF] - Client device1/module1 connected to cloud, processing existing subscriptions.
<6> 2021-06-30 14:31:54.155 +00:00 [INF] - Skipping device1/module1 for subscription processing, as it is currently being processed.
<6> 2021-06-30 14:31:54.155 +00:00 [INF] - Created cloud proxy for client device1/module1 via AMQP, with client operation timeout 20 seconds.
<6> 2021-06-30 14:31:54.155 +00:00 [INF] - Initialized cloud proxy fd96d3d6-43ac-4ea7-9796-f98f489f7958 for device1/module1
<6> 2021-06-30 14:31:54.155 +00:00 [INF] - Created cloud connection for client device1/module1
<6> 2021-06-30 14:31:54.259 +00:00 [INF] - Processing pending subscriptions for device1/module1
<6> 2021-06-30 14:31:54.259 +00:00 [INF] - Processing pending subscriptions for device1/module1
<6> 2021-06-30 14:31:54.259 +00:00 [INF] - Processing pending subscriptions for device1/module1
<6> 2021-06-30 14:31:54.259 +00:00 [INF] - Processing pending subscriptions for device1/module1
<6> 2021-06-30 14:31:58.951 +00:00 [INF] - Updated reported properties for device1/$edgeHub
```

Diagnostics is turned on at our IoT Hub and we are getting the Connect/Disconnect messages but there are no errors.  It appears that our module is operating correctly but my understanding was that the web socket connection would be kept alive and we wouldn't have so many connect/disconnects.  The 2 minute interval is suspect.

Any idea?

**Comment by timtay-microsoft** [comment]
Can you share a bit more context on the SDK side code you are using? Is this the latest SDK version? What JDK do you have installed? And are you using any optional settings on the SDK like setting a proxy, changing the SAS token expiry time, or anything similar?

**Comment by timtay-microsoft** [comment]
And do you see this same behavior when you have the module connect directly to IoT Hub rather than to an Edgehub instance?

**Comment by nenright** [comment]
Hi @timtay-microsoft, 
we are using version: com.microsoft.azure.sdk.iot:iot-device-client:1.30.2, and are using the openjdk:8-jdk-alpine image.  We're deploying our edge module with a DNS config of 8.8.8.8. No other configs really. I'll try to see if we can run outside of edge and switch the protocol.

**Comment by timtay-microsoft** [comment]
Any updates here, @nenright ?

**Comment by nenright** [comment]
So we still get the disconnects every two minutes with MQTT_WS.  They don't happen if we use AQMP.  Haven't been able to try AQMP_WS yet as we may be ok with AQMP for now.

**Comment by timtay-microsoft** [comment]
Do you see this same behavior with older versions of Edgehub?

**Comment by timtay-microsoft** [comment]
Closing this issue as it appears to be an Edgehub service issue. I can't directly transfer this issue, so it'll need to be opened [here](https://github.com/Azure/iotedge/issues).
