### ISSUE TITLE
[Bug Report] DeviceKeyLengthInvalid for device symmetric keys with length of 64 bytes

### ISSUE THREAD

**Issue by marinabauer** [Azure/azure-iot-sdk-java#1322]
# Context

- **OS and version used:** Ubuntu 20.04
- **Java runtime used:** 11
- **SDK version used:** 1.33.0

## Description of the issue
Devices with Authentication Type Symmetric Key and a primary or secondary key generated in the UI (via the device provisioning service) are raising an issue, once they are constructed with the SDK into the Device-Object.

The issue is in this line: https://github.com/Azure/azure-iot-sdk-java/blob/e2afc21e6f8fcb8f7e87f219f571fcbb9faafa6a/service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/auth/SymmetricKey.java#L137
The base64-encoded string is compared with the max key lenght in Bytes - and obviously the base64 encoded version is longer than the respective byte array.

## Code sample exhibiting the issue
```
val registry = RegistryManager(iotHubConnectionString)
val device: Device = registry.getDevice(myDeviceId)
```

The authentication type of the device with this deviceId has to be SAS and the length of the primary key = 64, respectively the base64 encoded version of the primary key has to be > 64 bytes.

## Console log of the issue
```
2021-08-25 15:34:56.498 -DEBUG [default       ][a:            ] 341573 --- [nio-8080-exec-1] c.d.common.rest.CommonExceptionHandler   : Illegal argument exception: DeviceKeyLengthInvalid

java.lang.IllegalArgumentException: DeviceKeyLengthInvalid
	at com.microsoft.azure.sdk.iot.service.auth.SymmetricKey.validateDeviceAuthenticationKey(SymmetricKey.java:139) ~[iot-service-client-1.33.0.jar:na]
	at com.microsoft.azure.sdk.iot.service.auth.SymmetricKey.setPrimaryKeyFinal(SymmetricKey.java:83) ~[iot-service-client-1.33.0.jar:na]
	at com.microsoft.azure.sdk.iot.service.BaseDevice.<init>(BaseDevice.java:501) ~[iot-service-client-1.33.0.jar:na]
	at com.microsoft.azure.sdk.iot.service.Device.<init>(Device.java:255) ~[iot-service-client-1.33.0.jar:na]
	at com.microsoft.azure.sdk.iot.service.RegistryManager.getDevice(RegistryManager.java:317) ~[iot-service-client-1.33.0.jar:na]
	at 
```

**Comment by DominikVinan** [comment]
Thank you @marinabauer for opening this bug! I have the same Issue.

**Comment by timtay-microsoft** [comment]
This is definitely a bug in the SDK, but we shouldn't even be validating the symmetric key within the SDK since the service does this for us. I'll see about removing this SDK-side validation of the symmetric key completely.

**Comment by timtay-microsoft** [comment]
Service client version 1.32.1 has been released and has the fix for this issue, so I'm closing this issue
