### ISSUE TITLE
[Bug Report] Disconnection race condition 

### ISSUE THREAD

**Issue by DBY047** [Azure/azure-iot-sdk-java#1343]
- **OS and version used:** Android 4.4
- **Java runtime used:** 1.6
- **SDK version used:** Java release 2020-11-16 (1.27.0) and Java release 2021-08-09 (1.32.1)

## Description of the issue
When trying to close the connection, we ran into a race condition with the SDK. The logs below show the race condition between our application successfully closing the connection (status DISCONNECTED) and the SDK restoring the connection (status DISCONNECTED_RETRYING)  

Thread ID 854 in our application called closeNow() to close  the connection but at the same time thread ID 1264 which appear to be from the SDK restored it at the same moment.  

The result is, we tried to close the connection but the SDK restored it so we are still connected. 

The logs are confusing. IotHubTransport set status to DISCONNECTED then DISCONNECTED_RETRYING.
It also print a trace about client being successfully closed but also not being able to disconnect. 

## Code sample exhibiting the issue
No specific code to provide.

## Console log of the issue
```
Timestamp            PID   TID
09-07 18:12:40.661   586   854 I DeviceClient:    Closing device client...
09-07 18:12:40.691   586   854 I IotHubTransport: Updating transport status to new status DISCONNECTED with reason CLIENT_CLOSE
09-07 18:12:40.691   586  1264 W IotHubTransport: Updating transport status to new status DISCONNECTED_RETRYING with reason NO_NETWORK
09-07 18:12:40.691   586  1264 W IotHubTransport: com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Mqtt connection lost
09-07 18:12:40.691   586  1264 W IotHubTransport: 	at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:75)
09-07 18:12:40.691   586  1264 W IotHubTransport: 	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connectionLost(Mqtt.java:389)
09-07 18:12:40.691   586  1264 W IotHubTransport: 	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.connectionLost(CommsCallback.java:304)
09-07 18:12:40.691   586  1264 W IotHubTransport: 	at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:441)
09-07 18:12:40.691   586  1264 W IotHubTransport: 	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:197)
09-07 18:12:40.691   586  1264 W IotHubTransport: 	at java.lang.Thread.run(Thread.java:841)
09-07 18:12:40.691   586  1264 W IotHubTransport: Caused by: Connection lost (32109) - java.io.EOFException
09-07 18:12:40.691   586  1264 W IotHubTransport: 	... 2 more
09-07 18:12:40.691   586  1264 W IotHubTransport: Caused by: java.io.EOFException
09-07 18:12:40.691   586  1264 W IotHubTransport: 	at java.io.DataInputStream.readByte(DataInputStream.java:77)
09-07 18:12:40.691   586  1264 W IotHubTransport: 	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
09-07 18:12:40.691   586  1264 W IotHubTransport: 	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
09-07 18:12:40.691   586  1264 W IotHubTransport: 	... 1 more
09-07 18:12:40.691   586   854 I IotHubTransport: Client connection closed successfully
09-07 18:13:40.920   586  1264 W IotHubTransport: Failed to close and re-open the iot hub transport connection, checking if another retry attempt should be made
09-07 18:13:40.920   586  1264 W IotHubTransport: com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Unable to disconnect
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:75)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.disconnect(Mqtt.java:166)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connect(Mqtt.java:128)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttMessaging.start(MqttMessaging.java:57)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:202)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:785)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.singleReconnectAttempt(IotHubTransport.java:916)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.reconnect(IotHubTransport.java:865)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.handleDisconnection(IotHubTransport.java:820)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.onConnectionLost(IotHubTransport.java:253)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at com.microsoft.azure.sdk.iot.device.transport.ReconnectionNotifier$1.run(ReconnectionNotifier.java:21)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at java.lang.Thread.run(Thread.java:841)
09-07 18:13:40.920   586  1264 W IotHubTransport: Caused by: Connect already in progress (32110)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at org.eclipse.paho.client.mqttv3.internal.ClientComms.close(ClientComms.java:237)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.close(MqttAsyncClient.java:1617)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.close(MqttAsyncClient.java:1605)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttConnection.close(MqttConnection.java:180)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.disconnect(Mqtt.java:158)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	... 10 more
09-07 18:13:42.021   586  1264 I IotHubTransport: The connection to the IoT Hub has been established
09-07 18:13:42.021   586  1264 I IotHubTransport: Updating transport status to new status CONNECTED with reason CONNECTION_OK

**Comment by DBY047** [comment]
I'll keep this one open in case I see it again in the next few weeks.

**Comment by timtay-microsoft** [comment]
@DBY047 any objections to us closing this issue now?

**Comment by DBY047** [comment]
Haven't seen the issue with the new sdk. I'll create a new one if I saw it again.

**Comment by gabrielandrade2** [comment]
I got an issue that looks similar to this one. I am using the version 1.33.0 of the SDK and if I have a connection that has a reconnection task active and I try to close the same connection (in my tests, I am trying to finish the process that manages my connections), it almost certainly deadlocks.

```
"ForkJoinPool-4-worker-3" Id=451 BLOCKED on java.lang.Object@7a53d04a owned by "azure-iot-sdk-ConnectionReconnectionTask:6365d7db-1669-4d7d-9255-a1809a8d1c0b" Id=899
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.close(IotHubTransport.java:501)
	-  blocked on java.lang.Object@7a53d04a
	at com.microsoft.azure.sdk.iot.device.DeviceIO.close(DeviceIO.java:264)
	-  locked java.lang.Object@705a6aa7
	at com.microsoft.azure.sdk.iot.device.InternalClient.closeNow(InternalClient.java:230)
	at com.microsoft.azure.sdk.iot.device.DeviceClient.closeNow(DeviceClient.java:541)
	at com.test.iot.azure.AzureIotConnectionImpl.close(AzureIotConnectionImpl.java:157)
	-  locked java.lang.Object@589df06e
	at com.test.iot.service.Connection.close(Connection.java:287)
 -- removed the rest of the the trace as it is unnecessary --

"azure-iot-sdk-ConnectionReconnectionTask:6365d7db-1669-4d7d-9255-a1809a8d1c0b" Id=899 BLOCKED on java.lang.Object@705a6aa7 owned by "ForkJoinPool-4-worker-3" Id=451
	at com.microsoft.azure.sdk.iot.device.DeviceIO.execute(DeviceIO.java:457)
	-  blocked on java.lang.Object@705a6aa7
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.updateStatus(IotHubTransport.java:1533)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.onConnectionEstablished(IotHubTransport.java:334)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:291)
	-  locked java.lang.Object@6c562643
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:1117)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.singleReconnectAttempt(IotHubTransport.java:1325)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.reconnect(IotHubTransport.java:1265)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.handleDisconnection(IotHubTransport.java:1146)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.onConnectionLost(IotHubTransport.java:318)
	-  locked java.lang.Object@7a53d04a
	at com.microsoft.azure.sdk.iot.device.transport.ReconnectionNotifier$1.run(ReconnectionNotifier.java:22)
	at java.base@15.0.3/java.lang.Thread.run(Thread.java:832)


Deadlocked Threads:
==================
"ForkJoinPool-4-worker-3" Id=451 BLOCKED on java.lang.Object@7a53d04a owned by "azure-iot-sdk-ConnectionReconnectionTask:6365d7db-1669-4d7d-9255-a1809a8d1c0b" Id=899

"azure-iot-sdk-ConnectionReconnectionTask:6365d7db-1669-4d7d-9255-a1809a8d1c0b" Id=899 BLOCKED on java.lang.Object@705a6aa7 owned by "ForkJoinPool-4-worker-3" Id=451
```
