### ISSUE TITLE
[Bug Report] IoTHubTransport updateStatus callback called in the wrong order

### ISSUE THREAD

**Issue by DBY047** [Azure/azure-iot-sdk-java#1348]
- **OS and version used:** Android 4.4
- **Java runtime used:** 1.6
- **SDK version used:** Java release 2020-11-16 (1.27.0) and Java release 2021-08-09 (1.32.1)

## Description of the issue
When IoTHubTransport->updateStatus is called, deviceIOConnectionStatusChangeCallback is call after invokeConnectionStatusChangeCallback. 
invokeConnectionStatusChangeCallback handle callback registered from deviceClient->subscribeToDeviceMethod: client code. 
deviceIOConnectionStatusChangeCallback handle callback for the deviceIO object: SDK code.  

When our code receive a CONNECTED event and try to call method like subscribeToDeviceMethod or subscribeToTwinDesiredProperties, IOException is thrown because deviceIO have not been notified yet that the connection is establish. I think deviceIOConnectionStatusChangeCallback shall be call first and then call client connectionStatusChangeCallback. Doing that, deviceIO will call startWorkerThreads and set the state to CONNECTED and be ready for whatever the client code need to do when notified of the connection status change, 

I mean by client code the code that create a new DeviceClient object and subscribe to eventCallback: whatever code that use the SDK. 

This make IotHubConnectionStatusChangeCallback unreliable because the status change to CONNECTED is false. 

## Code sample exhibiting the issue
```java
//invoke connection status callbacks
this.log.debug("Invoking connection status callbacks with new status details");
invokeConnectionStateCallback(newConnectionStatus, reason);
invokeConnectionStatusChangeCallback(newConnectionStatus, reason, throwable);
this.deviceIOConnectionStatusChangeCallback.execute(newConnectionStatus, reason, throwable, null);
```

## Console log of the issue
```
Open the client connection before using it.
java.io.IOException: Open the client connection before using it.
	at com.microsoft.azure.sdk.iot.device.InternalClient.subscribeToMethodsInternal(InternalClient.java:704)
	at com.microsoft.azure.sdk.iot.device.DeviceClient.subscribeToDeviceMethod(DeviceClient.java:668)
	at com.distech.android.configuration.iot.IoTClient.setupDeviceMethodsHandleAndCallback(IoTClient.java:187)
	at com.distech.android.configuration.iot.IoTClient.execute(IoTClient.java:293)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.invokeConnectionStatusChangeCallback(IotHubTransport.java:1192)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.updateStatus(IotHubTransport.java:1145)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.onConnectionEstablished(IotHubTransport.java:274)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:208)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:785)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.open(IotHubTransport.java:325)
	at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:156)
	at com.microsoft.azure.sdk.iot.device.InternalClient.open(InternalClient.java:148)
	at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:395)
	at com.distech.android.configuration.iot.IoTClient.openNow(IoTClient.java:160)
	at com.distech.android.configuration.iot.IoTClient.access$1300(IoTClient.java:73)
	at com.distech.android.configuration.iot.IoTClient$ReconnectTask.run(IoTClient.java:867)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:279)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

**Comment by timtay-microsoft** [comment]
Device client version 1.31.3 has been released and has the fix for this issue, so this issue was closed
