### ISSUE TITLE
[Bug Report] Deadlock when closing the connection

### ISSUE THREAD

**Issue by gabrielandrade2** [Azure/azure-iot-sdk-java#1392]
# Context

- **OS and version used:** Ubuntu 20.04.3
- **Java runtime used:** openjdk version "15.0.3" 2021-04-20
- **SDK version used:** 1.33.0

## Description of the issue
I got an issue that looks similar to #1343 . I am using the version 1.33.0 of the SDK and if I have a connection that has a reconnection task active and I try to close the same connection (in my tests, I am trying to finish the process that manages my connections), it almost certainly deadlocks.

It looks like the reconnection thread grabs the reconnectionLock on the IotHubTransport class and the closing thread grabs the stateLock on the DeviceIO class, but both threads need the two locks to execute.

## Code sample exhibiting the issue
No specific code to provide

## Thread dump of the issue
```
"ForkJoinPool-4-worker-3" Id=451 BLOCKED on java.lang.Object@7a53d04a owned by "azure-iot-sdk-ConnectionReconnectionTask:6365d7db-1669-4d7d-9255-a1809a8d1c0b" Id=899
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.close(IotHubTransport.java:501)
	-  blocked on java.lang.Object@7a53d04a
	at com.microsoft.azure.sdk.iot.device.DeviceIO.close(DeviceIO.java:264)
	-  locked java.lang.Object@705a6aa7
	at com.microsoft.azure.sdk.iot.device.InternalClient.closeNow(InternalClient.java:230)
	at com.microsoft.azure.sdk.iot.device.DeviceClient.closeNow(DeviceClient.java:541)
	at com.test.iot.azure.AzureIotConnectionImpl.close(AzureIotConnectionImpl.java:157)
	-  locked java.lang.Object@589df06e
	at com.test.iot.service.Connection.close(Connection.java:287)
 -- removed the rest of the the trace as it is unnecessary --

"azure-iot-sdk-ConnectionReconnectionTask:6365d7db-1669-4d7d-9255-a1809a8d1c0b" Id=899 BLOCKED on java.lang.Object@705a6aa7 owned by "ForkJoinPool-4-worker-3" Id=451
	at com.microsoft.azure.sdk.iot.device.DeviceIO.execute(DeviceIO.java:457)
	-  blocked on java.lang.Object@705a6aa7
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.updateStatus(IotHubTransport.java:1533)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.onConnectionEstablished(IotHubTransport.java:334)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:291)
	-  locked java.lang.Object@6c562643
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:1117)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.singleReconnectAttempt(IotHubTransport.java:1325)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.reconnect(IotHubTransport.java:1265)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.handleDisconnection(IotHubTransport.java:1146)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.onConnectionLost(IotHubTransport.java:318)
	-  locked java.lang.Object@7a53d04a
	at com.microsoft.azure.sdk.iot.device.transport.ReconnectionNotifier$1.run(ReconnectionNotifier.java:22)
	at java.base@15.0.3/java.lang.Thread.run(Thread.java:832)


Deadlocked Threads:
==================
"ForkJoinPool-4-worker-3" Id=451 BLOCKED on java.lang.Object@7a53d04a owned by "azure-iot-sdk-ConnectionReconnectionTask:6365d7db-1669-4d7d-9255-a1809a8d1c0b" Id=899

"azure-iot-sdk-ConnectionReconnectionTask:6365d7db-1669-4d7d-9255-a1809a8d1c0b" Id=899 BLOCKED on java.lang.Object@705a6aa7 owned by "ForkJoinPool-4-worker-3" Id=451
```

**Comment by timtay-microsoft** [comment]
Looks like you are correct. We'll try to get a fix out for this soon

**Comment by jamdavi** [comment]
We have added improvements in the latest release that should help with this issue and others. Please feel free to reopen if the upgraded library does not solve this problem.

https://github.com/Azure/azure-iot-sdk-java/releases/tag/2021-12-15
