### ISSUE TITLE
[Bug Report] Connection status reason for routine MQTT disconnects is incorrect

### ISSUE THREAD

**Issue by timtay-microsoft** [Azure/azure-iot-sdk-java#1405]
Device/module clients that connect over MQTT are expected to lose connection once their SAS token has expired, but the connection status update that the SDK makes at this time is always "NO_NETWORK" instead of the expected "EXPIRED_SAS_TOKEN"

**Comment by timtay-microsoft** [comment]
This is likely because the SDK classifies all retryable errors as NO_NETWORK before it even checks if the SAS token was expired: https://github.com/Azure/azure-iot-sdk-java/blob/a0bb73058a2b2b2418019081b92074d2da2a6034/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java#L1048

**Comment by jamdavi** [comment]
We have added improvements in the latest release that should help with this issue and others. Please feel free to reopen if the upgraded library does not solve this problem.

https://github.com/Azure/azure-iot-sdk-java/releases/tag/2021-12-15

**Comment by in-fke** [comment]
> Device/module clients that connect over MQTT are expected to lose connection once their SAS token has expired

Just as a heads up, this used to be logged with WARN and Exceptions.
Apparently this was improved to only be logged with INFO and without stack, see
https://github.com/Azure/azure-iot-sdk-java/blob/main/iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/Mqtt.java#L345
and
https://github.com/Azure/azure-iot-sdk-java/blob/main/iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java#L1658

So I guess we will update and see how it goes with regard to log output.

```
2023-09-20T14:12:42,748 WARN  [MQTT Rec: soo-fnke] transport.mqtt.Mqtt:330 Mqtt connection lost
org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:197) [org.eclipse.paho.client.mqttv3-1.2.5.jar:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:272) ~[?:?]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:?]
	... 1 more
2023-09-20T14:12:42,751 WARN  [MQTT Rec: soo-fnke] device.transport.IotHubTransport:1629 Updating transport status to new status DISCONNECTED_RETRYING with reason EXPIRED_SAS_TOKEN
com.microsoft.azure.sdk.iot.device.transport.ProtocolException: Mqtt connection lost
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:63) ~[iot-device-client-2.1.3.jar:?]
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connectionLost(Mqtt.java:339) [iot-device-client-2.1.3.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.connectionLost(CommsCallback.java:304) [org.eclipse.paho.client.mqttv3-1.2.5.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:441) [org.eclipse.paho.client.mqttv3-1.2.5.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:197) [org.eclipse.paho.client.mqttv3-1.2.5.jar:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	... 2 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:272) ~[?:?]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:?]
	... 1 more
```
