### ISSUE TITLE
[Bug report] DeviceClient threads leak during reconnection events

### ISSUE THREAD

**Issue by sorinpenteleiciuc** [Azure/azure-iot-sdk-java#1412]
When device clients that connect over MQTT lose connection, a 2 news threads are created :
azure-iot-sdk-IotHubReceiveTas, azure-iot-sdk-IotHubSendTask

 
We're currently struggling with an issue that the MQTT connection gets lost after every 3 to 5 minutes.
This leads additionally to the issue that two new threads are started every time the connection gets lost which also leads to the issue that the JVM ran out of memory after a certain time.
 
These are the exceptions for the MQTT connection loss:
 
2021-11-08 23:58:09.666  59562328 [MQTT Rec: 999] WARN  c.m.a.s.i.d.transport.mqtt.Mqtt - Mqtt connection lost
org.eclipse.paho.client.mqttv3.MqttException: Connection lost
            at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:190)
            at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.net.ssl.SSLException: Connection reset
            at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
            at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:326)
            at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:269)
            at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
            at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1576)
            at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:974)
            at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:865)
            at java.base/java.io.DataInputStream.readByte(DataInputStream.java:270)
            at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
            at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
            ... 1 common frames omitted
            Suppressed: java.net.SocketException: Broken pipe (Write failed)
                        at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
                        at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
                        at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
                        at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
                        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:357)
                        ... 9 common frames omitted
Caused by: java.net.SocketException: Connection reset
            at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
            at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
            at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:467)
            at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:461)
            at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
            at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1349)
            at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:958)
            ... 5 common frames omitted
2021-11-08 23:58:09.704  59562366 [azure-iot-sdk-ConnectionReconnectionTask:94be801c-2819-45bd-8a90-db72a99dbfc6] INFO  c.m.a.s.i.d.t.IotHubTransport - Handling a disconnection event
com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Mqtt connection lost
            at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:74)
            at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connectionLost(Mqtt.java:343)
            at org.eclipse.paho.client.mqttv3.internal.CommsCallback.connectionLost(CommsCallback.java:304)
            at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:439)
            at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:190)
            at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.eclipse.paho.client.mqttv3.MqttException: Connection lost
            ... 2 common frames omitted
Caused by: javax.net.ssl.SSLException: Connection reset
            at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
            at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:326)
            at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:269)
            at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
            at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1576)
            at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:974)
            at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:865)
            at java.base/java.io.DataInputStream.readByte(DataInputStream.java:270)
            at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
            at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
            ... 1 common frames omitted
            Suppressed: java.net.SocketException: Broken pipe (Write failed)
                        at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
                        at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
                        at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
                        at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
                        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:357)
                        ... 9 common frames omitted
Caused by: java.net.SocketException: Connection reset
            at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
            at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
            at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:467)
            at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:461)
            at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
            at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1349)
            at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:958)
            ... 5 common frames omitted
2021-11-08 23:58:09.707  59562369 [azure-iot-sdk-ConnectionReconnectionTask:94be801c-2819-45bd-8a90-db72a99dbfc6] WARN  c.m.a.s.i.d.t.IotHubTransport - Updating transport status to new status DISCONNECTED_RETRYING with reason NO_NETWORK
com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Mqtt connection lost
            at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:74)
            at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connectionLost(Mqtt.java:343)
            at org.eclipse.paho.client.mqttv3.internal.CommsCallback.connectionLost(CommsCallback.java:304)
            at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:439)
            at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:190)
            at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.eclipse.paho.client.mqttv3.MqttException: Connection lost
            ... 2 common frames omitted
Caused by: javax.net.ssl.SSLException: Connection reset
            at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
            at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:326)
            at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:269)
            at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
            at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1576)
            at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:974)
            at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:865)
            at java.base/java.io.DataInputStream.readByte(DataInputStream.java:270)
            at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
            at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
            ... 1 common frames omitted
            Suppressed: java.net.SocketException: Broken pipe (Write failed)
                        at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
                        at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
                        at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
                        at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
                        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:357)
                        ... 9 common frames omitted
Caused by: java.net.SocketException: Connection reset
            at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
            at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
            at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:467)
            at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:461)
            at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
            at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1349)
            at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:958)
            ... 5 common frames omitted
2021-11-08 23:58:11.469  59564131 [azure-iot-sdk-ConnectionReconnectionTask:94be801c-2819-45bd-8a90-db72a99dbfc6] INFO  c.m.a.s.i.d.t.IotHubTransport - Updating transport status to new status CONNECTED with reason CONNECTION_OK
 
 
And the Linux (Yocto) reported out of memory exception after the JAVA application was running for around 18 hours and having the above exceptions every few minutes:
 
Nov 09 02:03:39 ... start_application.sh[210]: [67104.036s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 320k, guardsize: 0k, detached.
Nov 09 02:03:39 ... start_application.sh[210]: Exception in thread "azure-iot-sdk-ConnectionReconnectionTask:aae974c5-36e2-4538-848c-8a3bb9587183" java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
Nov 09 02:03:39 ... start_application.sh[210]:         at java.base/java.lang.Thread.start0(Native Method)
Nov 09 02:03:39 ... start_application.sh[210]:         at java.base/java.lang.Thread.start(Thread.java:803)
Nov 09 02:03:39 ... start_application.sh[210]:         at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:937)
Nov 09 02:03:39 ... start_application.sh[210]:         at java.base/java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1583)
Nov 09 02:03:39 ... start_application.sh[210]:         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:346)
Nov 09 02:03:39 ... start_application.sh[210]:         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.scheduleWithFixedDelay(ScheduledThreadPoolExecutor.java:680)
Nov 09 02:03:39 ... start_application.sh[210]:         at com.microsoft.azure.sdk.iot.device.DeviceIO.startWorkerThreads(DeviceIO.java:231)
Nov 09 02:03:39 ... start_application.sh[210]:         at com.microsoft.azure.sdk.iot.device.DeviceIO.execute(DeviceIO.java:473)
Nov 09 02:03:39 ... start_application.sh[210]:         at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.updateStatus(IotHubTransport.java:1533)
Nov 09 02:03:39 ... start_application.sh[210]:         at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.onConnectionEstablished(IotHubTransport.java:334)
Nov 09 02:03:39 ... start_application.sh[210]:         at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:291)
Nov 09 02:03:39 ... start_application.sh[210]:         at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:1117)
Nov 09 02:03:39 ... start_application.sh[210]:         at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.singleReconnectAttempt(IotHubTransport.java:1325)
Nov 09 02:03:39 ... start_application.sh[210]:         at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.reconnect(IotHubTransport.java:1265)
Nov 09 02:03:39 ... start_application.sh[210]:         at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.handleDisconnection(IotHubTransport.java:1146)
Nov 09 02:03:39 ... start_application.sh[210]:         at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.onConnectionLost(IotHubTransport.java:318)
Nov 09 02:03:39 ... start_application.sh[210]:         at com.microsoft.azure.sdk.iot.device.transport.ReconnectionNotifier$1.run(ReconnectionNotifier.java:22)
Nov 09 02:03:39 ... start_application.sh[210]:         at java.base/java.lang.Thread.run(Thread.java:834)
 
These threads are active after a runtime of approx. 1 hour:
 
 Thread Thread[azure-iot-sdk-IotHubSendTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubSendTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubSendTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubReceiveTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubSendTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubReceiveTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubReceiveTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubReceiveTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubSendTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubReceiveTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubReceiveTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubReceiveTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubSendTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubSendTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubReceiveTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubSendTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubReceiveTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubSendTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubSendTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubReceiveTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubReceiveTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubSendTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubSendTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubReceiveTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubReceiveTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubReceiveTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubSendTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubSendTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubReceiveTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubReceiveTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubSendTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubReceiveTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubSendTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubReceiveTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubReceiveTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubSendTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubSendTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubSendTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubSendTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubReceiveTask,5,main]
 Thread Thread[azure-iot-sdk-IotHubSendTask,5,main]

Below is my code `

public class CloudConnectorService {

    private static final Logger logger = LoggerFactory.getLogger(CloudConnectorService.class);

    public static final int MAX_TRYOUTS_CLIENT_CONNECT = 2;
    public static DeviceClient client;    
    public static boolean clientConnected = false;

    @Value("${cloud.idScope}")
    private String idScope;

    @Value("${cloud.globalendpoint}")
    private String globalEndpoint;

    private static final ProvisioningDeviceClientTransportProtocol PROVISIONING_DEVICE_CLIENT_TRANSPORT_PROTOCOL = ProvisioningDeviceClientTransportProtocol.HTTPS;
    private static final int MAX_TIME_TO_WAIT_FOR_REGISTRATION = 1000; // in milli seconds
    private static final Collection<String> signerCertificates = new LinkedList<>();

    @Autowired
    private DirectMethodCallBack directMethodCallBack;

    @Value("${iot.hub.connection.hostname}")
    private String iotHubConnectionHostname;

    @Value("${softwareVersion}")
    String softwareVersion;

    static class ProvisioningStatus {
        ProvisioningDeviceClientRegistrationResult provisioningDeviceClientRegistrationInfoClient = new ProvisioningDeviceClientRegistrationResult();
        Exception exception;
    }

    protected static class DeviceTwinStatusCallBack implements IotHubEventCallback {
        @Override
        public void execute(final IotHubStatusCode status, final Object context) {
            logger.info("IoT Hub responded to device twin operation with status " + status.name());
        }
    }

    protected static class OnProperty implements TwinPropertyCallBack {
        @Override
        public void TwinPropertyCallBack(final Property property, final Object context) {
            logger.info("TwinPropertyCallBack on property.");
        }
    }

    public void instantiateNewClient() {
        logger.info("Try to instantiate the client: " + softwareVersion);

        try {
            String leafPrivateKey = null;
            String leafPublicPem = null;
            String intermediateKey = null;
            String iotHubUri = iotHubConnectionHostname;
            String deviceId = Memory.gatewayStaticInfo.getSerialNumber();

            ProvisioningDeviceClient provisioningDeviceClient = null;

            int tryout = 0;
            while (tryout < MAX_TRYOUTS_CLIENT_CONNECT && !clientConnected) {
                try {
                    tryout++;
                    final ProvisioningStatus provisioningStatus = new ProvisioningStatus();

                    // For group enrollment uncomment this line
                    signerCertificates.add(intermediateKey);

                    final SecurityProvider securityProviderX509 = new SecurityProviderX509Cert(leafPublicPem, leafPrivateKey, signerCertificates);
                    provisioningDeviceClient = ProvisioningDeviceClient.create(globalEndpoint, idScope, PROVISIONING_DEVICE_CLIENT_TRANSPORT_PROTOCOL,
                            securityProviderX509);

                    logger.info("Provisioning started");
                    provisioningDeviceClient.registerDevice(new ProvisioningDeviceClientRegistrationCallbackImpl(), provisioningStatus);
                    while (provisioningStatus.provisioningDeviceClientRegistrationInfoClient.getProvisioningDeviceClientStatus() != ProvisioningDeviceClientStatus.PROVISIONING_DEVICE_STATUS_ASSIGNED) {
                        if (provisioningStatus.provisioningDeviceClientRegistrationInfoClient.getProvisioningDeviceClientStatus() == ProvisioningDeviceClientStatus.PROVISIONING_DEVICE_STATUS_ERROR ||
                                provisioningStatus.provisioningDeviceClientRegistrationInfoClient.getProvisioningDeviceClientStatus() == ProvisioningDeviceClientStatus.PROVISIONING_DEVICE_STATUS_DISABLED ||
                                provisioningStatus.provisioningDeviceClientRegistrationInfoClient.getProvisioningDeviceClientStatus() == ProvisioningDeviceClientStatus.PROVISIONING_DEVICE_STATUS_FAILED) {

                            logger.error("Registration error, bailing out :"
                                    + provisioningStatus.provisioningDeviceClientRegistrationInfoClient.getProvisioningDeviceClientStatus()
                                    + " Error: " + ExceptionUtils.getStackTrace(provisioningStatus.exception));
                            break;
                        }
                        logger.info("Waiting for Provisioning Service to register");
                        Thread.sleep(MAX_TIME_TO_WAIT_FOR_REGISTRATION);
                    }

                    if (provisioningStatus.provisioningDeviceClientRegistrationInfoClient.getProvisioningDeviceClientStatus() == ProvisioningDeviceClientStatus.PROVISIONING_DEVICE_STATUS_ASSIGNED) {
                        logger.info("IotHUb Uri : " + provisioningStatus.provisioningDeviceClientRegistrationInfoClient.getIothubUri());
                        logger.info("Device ID : " + provisioningStatus.provisioningDeviceClientRegistrationInfoClient.getDeviceId());
                        iotHubUri = provisioningStatus.provisioningDeviceClientRegistrationInfoClient.getIothubUri();
                        deviceId = provisioningStatus.provisioningDeviceClientRegistrationInfoClient.getDeviceId();
                    }

                    logger.info("Start to create client with MQTT protocol for device id in iot:" + deviceId);
                    Memory.iotDeviceId = deviceId;
                    client = DeviceClient.createFromSecurityProvider(iotHubUri, deviceId, securityProviderX509, IotHubClientProtocol.MQTT);

                    client.open(true);

                    logger.info("Client created");
                    client.subscribeToDeviceMethod(directMethodCallBack, null, new DirectMethodStatusCallBack(), null);

                    client.startDeviceTwin(new DeviceTwinStatusCallBack(), null, new OnProperty(), null);
                    client.getDeviceTwin();

                    final DeviceClient finalClient = client;
                    Runtime.getRuntime().addShutdownHook(new Thread() {
                        @Override
                        public void run() {
                            try {
                                logger.info("deviceIotclientclosed");
                                finalClient.closeNow();
                                logger.info("deviceIotclientclosed Successful");
                            } catch (final IOException e) {
                                e.printStackTrace();
                            }
                        }
                    });
                    clientConnected = true;
                } catch (final ProvisioningDeviceClientException e) {
                    logger.error("Provisioning Device Client threw an exception" + e.getMessage());
                    if (provisioningDeviceClient != null) {
                        provisioningDeviceClient.closeNow();
                    }
                } catch (final IOException e) {
                    logger.error("Device client threw an exception: " + ExceptionUtils.getStackTrace(e));
                    if (client != null) {
                        try {
                            client.closeNow();
                        } catch (final IOException ioException) {
                            ioException.printStackTrace();
                        }
                    }
                } catch (final Exception ex) {
                    logger.error("XXXXXXXXXXX IOT_NOT_WORKING " + ex);
                    logger.error(ExceptionUtils.getStackTrace(ex));
                }
            }
        } catch (final Exception ex) {
            logger.error("    ------   Error encountered when running iot");
            logger.error(ExceptionUtils.getStackTrace(ex));
        }
    }
    static class ProvisioningDeviceClientRegistrationCallbackImpl implements ProvisioningDeviceClientRegistrationCallback {
        @Override
        public void run(final ProvisioningDeviceClientRegistrationResult provisioningDeviceClientRegistrationResult, final Exception exception, final Object context) {
            if (context instanceof ProvisioningStatus) {
                final ProvisioningStatus status = (ProvisioningStatus) context;
                status.provisioningDeviceClientRegistrationInfoClient = provisioningDeviceClientRegistrationResult;
                status.exception = exception;
            } else {
                logger.info("Received unknown context");
            }
        }
    }

`

**Comment by timtay-microsoft** [comment]
This does look like a bug. I'll try to get the fix for this checked in soon.

**Comment by timtay-microsoft** [comment]
This issue doesn't appear to be tied to just MQTT. The faulty logic sits in a layer above the MQTT layer, so I expect AMQP users would hit this bug as well.

**Comment by jamdavi** [comment]
We have added improvements in the latest release that should help with this issue and others.

https://github.com/Azure/azure-iot-sdk-java/releases/tag/2021-12-15
