### ISSUE TITLE
How to check if the device client object could not be opened due to a blocked port

### ISSUE THREAD

**Issue by DeveloperBeginner** [Azure/azure-iot-sdk-java#1419]
OS and version used: Android 6.0.1

Java runtime used: 1.8.0

SDK version used: 1.19.0

I create a device client object using the following code
`DeviceClient deviceClient = DeviceClient.createFromSecurityProvider(iotHubUri, deviceId, securityProviderX509, IotHubClientProtocol.AMQPS );`

And then I open the device client connection.
`deviceClient.open();`

If opening the device client fails, how can I determine if it is due to a blocked port (5671 in this case) ? Do I get a specific error log?

**Comment by DeveloperBeginner** [comment]
Are there any updates on this?

**Comment by jamdavi** [comment]
@DeveloperBeginner Sorry this took so long I grabbed this before the holidays, and it got pushed far down in my stack. I wanted to make sure that I had the situation right so I could make sure to tell you what to do.

In my scenario what I did was set up an Android Emulator with the exact setup you have. In this instance I blocked the port from my machine and ended up with the EACCES message. 

We don't have any specific set of enumerations or specific exceptions which say that it was due to a blocked port--as really there is no reason to fully know why or if the port is inaccessible. 

You'll have to look into the exception for details. In our code we call throw IOException and put the ProtonIOException as the cause. This should give you enough context to consider it a networking issue and the specific error messages should help you make a proper decision.

In my case I saw the **socket failed: EACCES (Permission denied)** message as a result of blocking the port.

|Component|Version|
|---|---|
|Java|1.8|
|Android|6.0.1 (Marshmallow)|
|SDK|1.19.0|


```java
try {
    DeviceClient deviceClient = new DeviceClient("HostName=ghissue2163.azure-devices.net;DeviceId=oldlibrary;SharedAccessKey=UYWHHcX5Y6ZQ/Evcou6vrpqgyEg9VNxzdBCwcPKNML8=", IotHubClientProtocol.AMQPS);
    deviceClient.open();
} catch (IOException e) {
    if (e.getCause() instanceof ProtonIOException) {
        if (e.getMessage().equalsIgnoreCase("Could not open the connection")) {
            ProtonIOException protonException = (ProtonIOException)e.getCause();
            if (protonException.getMessage().toLowerCase(Locale.ROOT).contains("socket failed:")) {
                // Do work inside of this to alert user that there was a problem
                e.printStackTrace();
            }
        }
    }
}
```

The full exception that comes back is 

```
java.io.IOException: Could not open the connection
        at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:162)
        at com.microsoft.azure.sdk.iot.device.InternalClient.open(InternalClient.java:133)
        at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:334)
        at com.example.iotconnecttest.MainActivity$1.onClick(MainActivity.java:52)
        at android.view.View.performClick(View.java:5198)
        at android.view.View$PerformClick.run(View.java:21147)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    Caused by: com.microsoft.azure.sdk.iot.device.transport.amqps.exceptions.ProtonIOException: socket failed: EACCES (Permission denied)
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsExceptionTranslator.convertToAmqpException(AmqpsExceptionTranslator.java:95)
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.getTransportExceptionFromProtonEndpoints(AmqpsIotHubConnection.java:1248)
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.getTransportExceptionFromEvent(AmqpsIotHubConnection.java:1269)
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.onTransportError(AmqpsIotHubConnection.java:921)
        at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191)
        at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
        at com.microsoft.azure.sdk.iot.device.transport.amqps.IotHubReactor.run(IotHubReactor.java:28)
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call(AmqpsIotHubConnection.java:1350)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
```
And some of the messages are:
```
e.getMessage() = "Could not open the connection"
e.getCause().getMessage() = "socket failed: EACCES (Permission denied)" 
```
