### ISSUE TITLE
[Bug Report] ServiceClient.send() method throws error "insufficient output buffer size" while sending a message of size more than 4KB

### ISSUE THREAD

**Issue by HimaniRanaa** [Azure/azure-iot-sdk-java#1420]
# Context

- **OS and version used:** <VERSION> Windows 10
- **Java runtime used:** <VERSION> openjdk version "1.8.0_242"
- **SDK version used:** <VERSION>iot-service-client:1.33.1

## Description of the issue
While sending a message of size more than **4KB** to a device using the ServiceClient's send method, we are getting an error "insufficient output buffer size"

## Code sample exhibiting the **issue**
Service Client bean creation 
```
 @Bean
    public ServiceClient serviceClient() throws IOException {
        return new ServiceClient(iotHubConnectionString, IotHubServiceClientProtocol.AMQPS_WS);
    }
```
Class with logic to send message
```
@Service
@Slf4j
@Component
@RequiredArgsConstructor
public class IotNotificationSender {
   private final ServiceClient serviceClient;
   public void publish(String deviceId, String message) {
            Message iotMessage = new Message(message);
            serviceClient.open();
            serviceClient.send(deviceId, iotMessage);
            serviceClient.close();
   }
}
```
## Console log of the issue
java.lang.OutOfMemoryError: insufficient output buffer size
	at com.microsoft.azure.sdk.iot.deps.ws.impl.WebSocketHandlerImpl.wrapBuffer(WebSocketHandlerImpl.java:165)
	at com.microsoft.azure.sdk.iot.deps.ws.impl.WebSocketImpl.wrapBuffer(WebSocketImpl.java:102)
	at com.microsoft.azure.sdk.iot.deps.ws.impl.WebSocketImpl$WebSocketTransportWrapper.head(WebSocketImpl.java:591)
	at org.apache.qpid.proton.engine.impl.HandshakeSniffingTransportWrapper.head(HandshakeSniffingTransportWrapper.java:151)
	at org.apache.qpid.proton.engine.impl.ssl.SimpleSslTransportWrapper.wrapOutput(SimpleSslTransportWrapper.java:222)
	at org.apache.qpid.proton.engine.impl.ssl.SimpleSslTransportWrapper.pending(SimpleSslTransportWrapper.java:400)
	at org.apache.qpid.proton.engine.impl.ssl.SslImpl$UnsecureClientAwareTransportWrapper.pending(SslImpl.java:173)
	at org.apache.qpid.proton.engine.impl.TransportImpl.pending(TransportImpl.java:1589)
	at org.apache.qpid.proton.reactor.impl.IOHandler.pending(IOHandler.java:193)
	at org.apache.qpid.proton.reactor.impl.IOHandler.update(IOHandler.java:214)
	at org.apache.qpid.proton.reactor.impl.IOHandler.handleTransport(IOHandler.java:347)
	at org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:384)
	at org.apache.qpid.proton.engine.BaseHandler.onTransport(BaseHandler.java:80)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:188)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:292)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.run(ReactorImpl.java:357)
	at com.microsoft.azure.sdk.iot.service.transport.amqps.ReactorRunner.run(ReactorRunner.java:102)
	at com.microsoft.azure.sdk.iot.service.transport.amqps.AmqpSend.send(AmqpSend.java:230)
	at com.microsoft.azure.sdk.iot.service.ServiceClient.send(ServiceClient.java:354)
	at com.microsoft.azure.sdk.iot.service.ServiceClient.send(ServiceClient.java:334)

**Comment by timtay-microsoft** [comment]
The service client library version 1.33.2 has fixed this issue already, so can you try upgrading to that version?

**Comment by timtay-microsoft** [comment]
@HimaniRanaa can you confirm that you no longer see this issue after upgrading?

**Comment by HimaniRanaa** [comment]
Thank you for the response. Yes, I tried with the new version 1.33.2 but it
also supports only approx 16KB of data. However azure has support for 64KB
data. Could you confirm if currently only 16KB is allowed?

**Comment by timtay-microsoft** [comment]
I'll take a look and confirm what the expected max message size should be here.

**Comment by HimaniRanaa** [comment]
Hi @timtay-microsoft: Do we have any update on this?

**Comment by timtay-microsoft** [comment]
I have identified the bug here, and #1450 will bring this SDK up to the advertised [IoT Hub cloud to device message size limit of 64 kb](https://github.com/MicrosoftDocs/azure-docs/blob/master/includes/iot-hub-limits.md).

**Comment by timtay-microsoft** [comment]
IoT Hub service client version 1.34.1 has been released with the fix for this issue. Service clients using AMQPS_WS can now send messages up to the expected 64 kb limit
