### ISSUE TITLE
[Bug Report] JAVA AZURE Module client graalvm incompatibility

### ISSUE THREAD

**Issue by prashantg077** [Azure/azure-iot-sdk-java#1425]
# Context
- Graalvm version-21.3.0
- **Java runtime used:** jdk11
- **SDK version used:** <version>1.21.1</version>

## Description of the issue

Creation of module client using JAVA Microsoft Azure sdk with graalvm native binary fails . Below is the code snippet

 ModuleClient moduleSenderClient = ModuleClient.createFromEnvironment(IotHubClientProtocol.AMQPS);
 moduleSenderClient.open();

NOTE the same code works when using a JVM based binary.

## Code sample exhibiting the issue
Steps to reproduce the issue:
Reproducing the issue:

Clone the project from

https://github.com/prashantg077/quarkusBugsReproducersPras

## Console log of the issue
Below is the exception trace:

2021-10-06T23:05:27.304627ZCaused by: java.lang.RuntimeException: Could not load platform constants for ProtocolFamily
2021-10-06T23:05:27.304636Z at jnr.constants.platform.ConstantResolver.getConstants(ConstantResolver.java:227)
2021-10-06T23:05:27.304644Z at jnr.constants.platform.ConstantResolver.lookupAndCacheConstant(ConstantResolver.java:128)
2021-10-06T23:05:27.304651Z at jnr.constants.platform.ConstantResolver.getConstant(ConstantResolver.java:116)
2021-10-06T23:05:27.304676Z at jnr.constants.platform.ConstantResolver.longValue(ConstantResolver.java:179)
2021-10-06T23:05:27.304684Z at jnr.constants.platform.ProtocolFamily.intValue(ProtocolFamily.java:48)
2021-10-06T23:05:27.304691Z at jnr.unixsocket.SockAddrUnix.setFamily(SockAddrUnix.java:55)
2021-10-06T23:05:27.304699Z at jnr.unixsocket.UnixSocketAddress.<init>(UnixSocketAddress.java:48)
2021-10-06T23:05:27.304733Z at com.microsoft.azure.sdk.iot.device.hsm.HttpsHsmClient.sendHttpRequestUsingUnixSocket.connect(HttpsHsmClient.java:238)

**Comment by timtay-microsoft** [comment]
We currently don't support using GraalVM with this SDK. That said, we are looking to remove the dependency on JNR unixsocket which appears to be causing this issue.

**Comment by timtay-microsoft** [comment]
Marking this as "Enhancement" since you are asking for us to support GraalVM

**Comment by prashantg077** [comment]
> Marking this as "Enhancement" since you are asking for us to support GraalVM

As a user of Azure cloud not able to deploy high performant low memory footprint solutions affects pricing dynamics and is a blocker for us. would want a ETA for this enhancement/fix.

**Comment by jamdavi** [comment]
Just to make sure we're all on the same page. This is 100% an issue with either JNR or GraalVM. We need to work with these maintainers to make this work. 


Here is the output just using the line of code JNR uses.:

```java
void startup(@Observes StartupEvent event) throws ExecutionException, InterruptedException, URISyntaxException,
            IOException, SecurityProviderException, ModuleClientException {
                LOG.info("Getting int value of PF_INET");
                int pfinet = ProtocolFamily.PF_INET.intValue();
                LOG.info("PF_INET = " + pfinet);
                LOG.info("Getting int value of PF_UNIX");
                int pfunix = ProtocolFamily.PF_UNIX.intValue();
                LOG.info("PF_UNIX = " + pfunix);
    }
```

```
❯ .\target\code-with-quarkus-1.0.0-SNAPSHOT-runner.exe
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2021-12-15 15:50:51,048 INFO  [org.acm.mai.QuarkusModuleMain] (main) Running main method
2021-12-15 15:50:51,348 INFO  [org.acm.mai.ModuleReciever] (main) Getting int value of PF_INET
2021-12-15 15:50:51,348 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.RuntimeException: Could not load platform constants for ProtocolFamily
        at jnr.constants.platform.ConstantResolver.getConstants(ConstantResolver.java:226)
        at jnr.constants.platform.ConstantResolver.lookupAndCacheConstant(ConstantResolver.java:127)
        at jnr.constants.platform.ConstantResolver.getConstant(ConstantResolver.java:115)
        at jnr.constants.platform.ConstantResolver.longValue(ConstantResolver.java:178)
        at jnr.constants.platform.ProtocolFamily.intValue(ProtocolFamily.java:61)
        at org.acme.main.ModuleReciever.startup(ModuleReciever.java:24)
        at org.acme.main.ModuleReciever_Observer_startup_f43ab41051de39ca1e534f6cd06115c3c9b219b8.notify(ModuleReciever_Observer_startup_f43ab41051de39ca1e534f6cd06115c3c9b219b8.zig:111)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:307)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:289)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:70)
        at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(LifecycleEventsBuildStep$startupEvent1144526294.zig:87)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(LifecycleEventsBuildStep$startupEvent1144526294.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:579)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:101)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
        at org.acme.main.QuarkusModuleMain.main(QuarkusModuleMain.java:14)
```
