### ISSUE TITLE
[Bug Report] Azure IOT( iot-device-client ) sdk java (1.34.0) Device client gets stuck with exception "AmqpConnectionFramingErrorException: connection aborted" not recieving messages anymore

### ISSUE THREAD

**Issue by prashantg077** [Azure/azure-iot-sdk-java#1448]
# Context

- **OS and version used:** (Windows 10, Ubuntu 18.04, etc. )
- **Java runtime used:** jdk 11
- **SDK version used:** 1.34.0

## Description of the issue
with reference to issue https://github.com/Azure/azure-iot-sdk-java/issues/1429  , in Device client 1.34.0 , we are facing AmqpConnectionFramingErrorException: connection aborted exception and Device client doesnt seem to reconnect.

## Code sample exhibiting the issue
Device Client created using X509 cert based authentication
Device client is opened
Device client has a message callback where it receives and acknowledges the messages.

NOTE --- Upon restart also the messages are not received for an hour untill the messages in the IOT Hub queue are expired with default 1 hr TTL.

## Console log of the issue

2021-12-23 09:41:52,904 DEBUG [com.mic.azu.sdk.iot.dev.tra.IotHubTransport] (pab.azure-des.net-dote-e-de1-2e-1408-azure-iot-sdk-IotHubReceiveTask) Sending acknowledgement for received cloud to device message ( Message details: Correlation Id [9352acd6834] Message Id [f9f80-4f33] )
[32559942:0] -> Disposition{role=RECEIVER, first=301471, last=301471, settled=true, state=Accepted{}, batchable=false}
[32559942:0] -> Empty Frame
[32559942:0] -> Close{error=Error{condition=amqp:resource-limit-exceeded, description='local-idle-timeout expired', info=null}}
2021-12-23 09:45:42,920 ERROR [com.mic.azu.sdk.iot.dev.tra.amq.AmqpsIotHubConnection] (pab.azure-des.net-dote-e-de1-2e-1408-azure-iot-sdk-ReactorRunner-ConnectionOwner) Amqp transport error occurred, closing the amqps connection: com.microsoft.azure.sdk.iot.device.transport.amqps.exceptions.AmqpConnectionFramingErrorException: connection aborted
at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsExceptionTranslator.convertFromAmqpException(AmqpsExceptionTranslator.java:44)
at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.onTransportError(AmqpsIotHubConnection.java:579)
at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191)
at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
at com.microsoft.azure.sdk.iot.device.transport.amqps.ReactorRunner.call(ReactorRunner.java:50)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by timtay-microsoft** [comment]
Can you share the relevant snippet of code that shows how you create the device client here?

**Comment by prashantg077** [comment]
> Can you share the relevant snippet of code that shows how you create the device client here?

We are using X509 Certificates for creation of device client

SecurityProvider securityProviderX509 = new SecurityProviderX509Cert(deviceX509Cert, deviceX509Key, signerCertificates);

DeviceClient deviceClient = DeviceClient.createFromSecurityProvider(iotHubUri, deviceId, securityProviderX509, IotHubClientProtocol.AMQPS);


dependency for X509
 <dependency>
      <groupId>com.microsoft.azure.sdk.iot.provisioning.security</groupId>
      <artifactId>x509-provider</artifactId>
      <version>1.1.6</version>
    </dependency>

**Comment by timtay-microsoft** [comment]
How frequently can you repro this issue with that code? 100%?

**Comment by prashantg077** [comment]
> How frequently can you repro this issue with that code? 100%?

we are doing reli runs by sending  80 C2D messages/ min . The application ran without issues for close to 3 days. After which we saw this issue , so we again restarted the edge modules and saw the error coming again.

**Comment by jamdavi** [comment]
Fixed with #1453

**Comment by jamdavi** [comment]
Fixed with 1.34.1
