### ISSUE TITLE
[Technical Question] Unable to subscribe to topic

### ISSUE THREAD

**Issue by DBY047** [Azure/azure-iot-sdk-java#1464]
Hi,

I choose to create this issue as Technical Question because I am not sure if this is anm SDK bug SDK or the IT hub bug. 

I see exceptions like the one below on all sites where we deployed our IoT solution. The network is highly unreliable and the device regularly disconnect and needs to reconnect. 

When we get the exception below , IotHubTransport sends the IotHubConnectionStatusChangeCallback with IotHubConnectionStatus CONNECTED but then throws ProtocolException like this:

```
com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Unable to subscribe to topic :$iothub/twin/PATCH/properties/desired/#
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:74)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.subscribe(Mqtt.java:280)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttDeviceTwin.send(MqttDeviceTwin.java:201)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.sendMessage(MqttIotHubConnection.java:368)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.sendPacket(IotHubTransport.java:1448)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.sendMessages(IotHubTransport.java:607)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubSendTask.run(IotHubSendTask.java:53)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:279)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: Timed out waiting for a response from the server (32000)
	at org.eclipse.paho.client.mqttv3.internal.Token.waitForCompletion(Token.java:112)
	at org.eclipse.paho.client.mqttv3.MqttToken.waitForCompletion(MqttToken.java:67)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.subscribe(Mqtt.java:272)
	... 12 more
```

We see "Unable to subscribe to topic" exceptions to all topics. Anybody can tell me what could be the cause of these exceptions? We deployed SDK 1.32.2 recently and 1.34.0 is in QA but I didn't see any changes that are related to topics subscriptions and could explain subscriptions issue. 

Also, I thinks IotHubTransport should wait till mqtt client was able to successfully subscribe to all topics before sending CONNECTED event but that could be another discussion. I really need to know if this is an issue with the IoT hub how could we fix it. 

Regards,

**Comment by timtay-microsoft** [comment]
> Caused by: Timed out waiting for a response from the server (32000)

This error from the MQTT library suggests that the client made the request to subscribe to the service, but the service was too slow to respond to the request ([15 second timeout](https://github.com/Azure/azure-iot-sdk-java/blob/feaeaaf8ab9fd91897ae73684ecead15c190a9ae/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/Mqtt.java#L33)). The topic that is being subscribed to is fine, it is just a question of service responsiveness

**Comment by timtay-microsoft** [comment]
> Also, I thinks IotHubTransport should wait till mqtt client was able to successfully subscribe to all topics before sending CONNECTED event but that could be another discussion. I really need to know if this is an issue with the IoT hub how could we fix it.

This is a design decision that is on the client side. Our stance has been that not every user will use twins/methods, so we didn't want them included in the requirements before we issue the CONNECTED callback. There are separate callbacks for when the twin subscription has been opened.

**Comment by DBY047** [comment]
15 seconds seems an eternity to me. I mean, the service doesn't runs on a small computer right? Cloud services should have infinite cpu power to handled those request.

**Comment by timtay-microsoft** [comment]
I agree that 15 seconds is rather long for an operation like this, but the service's performance will vary heavily depending on how many devices you have interacting with your IoT Hub.

There are [published quotas on service performance](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-quotas-throttling) that should be used to set expectations on how many devices can do how many operations per second based on the service scale unit your IoT Hub has. Unfortunately, I don't see any promises for new subscriptions per second, but if you are surpassing other quotas like new device connections per second then it's possible you are being throttled by the service.

> I see exceptions like the one below on all sites where we deployed our IoT solution. The network is highly unreliable and the device regularly disconnect and needs to reconnect.

One other possibility here is that the subscription packet is being lost due to this unstable network.

If you'd like confirmation that your IoT hub is throttling these requests (and causing them to timeout), or if you'd like to check if these requests are even making it to your IoT Hub, then I'd suggest opening a support ticket through the Azure Portal for you IoT Hub in question. A service side engineer can take a look at the performance of your hub in greater detail and give you a recommendation.

As for the SDK side of this issue, we could make these subscription timeouts configurable if that would help.

**Comment by timtay-microsoft** [comment]
Is there anything on the SDK side that I can help you with here, @DBY047 ?

**Comment by DBY047** [comment]
@timtay-microsoft, for our client point of view, our product is unable to connect to the hub and errors returned doesn't help us to pine point where the issue is. 

On the SDK side, I would like to have better error reports from the hub. If the hub throttled devices because quotas are reitch, I would like to have a clear error from the hub once the connection is made, before the SDK try to subscribe to topics, that quotas have been exceeded.
