### ISSUE TITLE
RegistryManager getModulesOnDevice should work when module doesn't have auth type

### ISSUE THREAD

**Issue by ancaantochi** [Azure/azure-iot-sdk-java#1507]
# Context

- **OS and version used:** <VERSION> (Windows 10, Ubuntu 18.04, etc. )
- **Java runtime used:** <VERSION> (in a command prompt: java -version )
- **SDK version used:** com.microsoft.azure.sdk.iot:iot-service-client:1.33.1 or latest

## Description of the issue

Modules on edge devices get created without authentication type being set (via deployment or when an edge device is created automatically edgeHub and edgeAgent modules get created). It should work to call getModulesOnDevice and get the list of modules.

## Code sample exhibiting the issue

```
Exception in thread "main" java.lang.IllegalArgumentException: deviceParser must have an
authentication type assigned
        at com.microsoft.azure.sdk.iot.service.BaseDevice.<init>(BaseDevice.java:439)
        at com.microsoft.azure.sdk.iot.service.Module.<init>(Module.java:164)
        at com.microsoft.azure.sdk.iot.service.RegistryManager.getModulesOnDevice(RegistryManager.java:1166)
```

**Comment by timtay-microsoft** [comment]
This bug has been fixed as of 2.0.1, so I'm closing this issue
