### ISSUE TITLE
[Bug Report] Unreliable registered device count in MultiplexingClient

### ISSUE THREAD

**Issue by gmousset** [Azure/azure-iot-sdk-java#1526]
# Context

- **OS and version used:** Docker container based on alpine 3.15 (eclipse-temurin:17-alpine)
- **Java runtime used:** openjdk version "17.0.1" 2021-10-19
- **SDK version used:** iot-device-client:2.0.1

## Description of the issue
It seems that when the MultiplexingClient is stressed with a lot of registrations/unregistrations the registered devices count is not reliable (**MultiplexingClient.getRegisteredDeviceCount()**). 
It causes exception on new registrations.

I added some debug traces. because SDK shadows root cause, there's may be an improvement to do.

***IotHubTransport.java - line 988***
```
                if (deviceRegistrationException != null)
                {
                    if (registrationException == null)
                    {
                        log.error("***********************************");
                        deviceRegistrationException.printStackTrace();
                        log.error("***********************************");
                        registrationException = new MultiplexingClientRegistrationException("Failed to register one or more devices to the multiplexed connection.");
                    }

                    registrationException.addRegistrationException(deviceId, deviceRegistrationException);

                    // Since the registration failed, need to remove the device from the list of multiplexed devices
                    ClientConfiguration configThatFailedToRegister = this.deviceClientConfigs.remove(deviceId);
                    this.multiplexedDeviceConnectionStates.remove(deviceId);
                    ((AmqpsIotHubConnection) this.iotHubTransportConnection).unregisterMultiplexedDevice(configThatFailedToRegister, false);
                }
```
On the stack trace below, at the last line, the first 480 is the device count according to my internal counter and the second 480 is the device count according to the SDK via **MultiplexingClient.getRegisteredDeviceCount()**.
But the IoT Hub has reach the 1000 device connections limit.

Thanks for your help.

## Console log of the issue
```
[2022-04-08 09:17:12][ERROR][IotHubTransport:992] ***********************************
com.microsoft.azure.sdk.iot.device.transport.https.exceptions.InternalServerErrorException: The maximum number of tokens per connection (1000) has been reached.
	at com.microsoft.azure.sdk.iot.device.IotHubStatusCode.getConnectionStatusException(IotHubStatusCode.java:129)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSasTokenRenewalHandler.handleAuthenticationResponseMessage(AmqpsSasTokenRenewalHandler.java:100)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsCbsReceiverLinkHandler.handleCBSResponseMessage(AmqpsCbsReceiverLinkHandler.java:96)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsCbsReceiverLinkHandler.onDelivery(AmqpsCbsReceiverLinkHandler.java:60)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:185)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.ReactorRunner.call(ReactorRunner.java:50)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
com.microsoft.azure.sdk.iot.device.exceptions.MultiplexingClientRegistrationException: Failed to register one or more devices to the multiplexed connection.
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.registerMultiplexedDeviceClient(IotHubTransport.java:995)
	at com.microsoft.azure.sdk.iot.device.DeviceIO.registerMultiplexedDeviceClient(DeviceIO.java:113)
	at com.microsoft.azure.sdk.iot.device.MultiplexingClient.registerDeviceClients(MultiplexingClient.java:473)
	at com.microsoft.azure.sdk.iot.device.MultiplexingClient.registerDeviceClient(MultiplexingClient.java:292)
	at com.microsoft.azure.sdk.iot.device.MultiplexingClient.registerDeviceClient(MultiplexingClient.java:234)
	at com.xxx
	at com.xxx
	at com.xxx
	at com.xxx
	at com.xxx
	at org.springframework.web.socket.handler.WebSocketHandlerDecorator.afterConnectionEstablished(WebSocketHandlerDecorator.java:70)
	at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.afterConnectionEstablished(LoggingWebSocketHandlerDecorator.java:48)
	at org.springframework.web.socket.handler.ExceptionWebSocketHandlerDecorator.afterConnectionEstablished(ExceptionWebSocketHandlerDecorator.java:48)
	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.onOpen(StandardWebSocketHandlerAdapter.java:104)
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.init(WsHttpUpgradeHandler.java:136)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:942)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1732)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.microsoft.azure.sdk.iot.device.transport.https.exceptions.InternalServerErrorException: The maximum number of tokens per connection (1000) has been reached.
	at com.microsoft.azure.sdk.iot.device.IotHubStatusCode.getConnectionStatusException(IotHubStatusCode.java:129)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSasTokenRenewalHandler.handleAuthenticationResponseMessage(AmqpsSasTokenRenewalHandler.java:100)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsCbsReceiverLinkHandler.handleCBSResponseMessage(AmqpsCbsReceiverLinkHandler.java:96)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsCbsReceiverLinkHandler.onDelivery(AmqpsCbsReceiverLinkHandler.java:60)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:185)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.ReactorRunner.call(ReactorRunner.java:50)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2022-04-08 09:17:12][ERROR][IotHubTransport:994] ***********************************
[2022-04-08 09:17:12][ERROR][IotHubClient:110] [480/480] cannot register device XXX in client 34496141-1302-4f4c-b571-0da78ff7875d: Failed to register one or more devices to the multiplexed connection.
```

**Comment by timtay-microsoft** [comment]
I suspect this is actually a service bug. I've repro'd the service rejecting a new device from the muxed connection even when manually checking that the number of clients I registered to a given multiplexed client is under the allowed threshold. I suspect the service isn't checking the number of clients registered at that moment, but instead, its checking the number of clients that have _ever been_ registered on this particular connection. I'm working to verify this with the service team, though.

**Comment by timtay-microsoft** [comment]
The SDK does expose these exceptions that you've added logs to look at, by the way:

```java
try
{
    multiplexingClient.registerDeviceClients(deviceClients);
}
catch (MultiplexingClientRegistrationException e)
{
    for (String deviceIdThatFailedToRegister : e.getRegistrationExceptions().keySet())
    {
        Exception reason = e.getRegistrationExceptions().get(deviceIdThatFailedToRegister);
        System.out.println("Failed to register device " + deviceIdThatFailedToRegister + " because of reason " + reason.getMessage());
    }
}
```

**Comment by gmousset** [comment]
Thanks @timtay-microsoft
I've implemented a work around with a connections pool + connections rotation + a counter to never exceed 1000 subscriptions by connection (counter is never decremented).
The service runs from 9 hours without errors.
Not the perfect solution, nevertheless, it works.
I hope this could be fixed on the iot hub.

**Comment by timtay-microsoft** [comment]
We haven't been able to get any traction from the service team to provide a way to fully unregister a device from a muxed connection so that it doesn't count against the cap. Unfortunately, I'll have to close this as "won't fix" for now. The solution described above is one way to work around this issue.
