### ISSUE TITLE
[Bug Report] PRECONDITION_FAILED when trying to update DeviceTwins on SDK v2

### ISSUE THREAD

**Issue by gabrielandrade2** [Azure/azure-iot-sdk-java#1530]
# Context

- **OS and version used:** Ubuntu 20.04.4 LTS
- **Java runtime used:** openjdk version "15.0.3" 2021-04-20
- **SDK version used:** 2.0.1

## Description of the issue
Hi, this may be something that I am doing wrong, but I don't actually understand the reason.
I am currently updating my former code from SDK v1 to v2 and I got stuck when trying to update the DeviceTwin properties.
I tried by many different ways (creating a new TwinCollection with only the property I want to update or sending the complete set), but I usually receive an error from the cloud with the code `PRECONDITION_FAILED`.

I tried then to run the `DeviceTwinSample` class from the SDK examples using the same device I was testing my code and still received `PRECONDITION_FAILED`.
I thought that maybe it could be some issue related to my device, as it already had plenty of old properties laying around in its twin dictionary. So I created a new clean IoT Device and, even so, trying to run the sample code always give me the same error.

Looks to me that either is something wrong with the v2 implementation or there is, at least, some step missing from the example class I am using.

Lastly, I saw somewhere (I believe in the IoT Hub Csharp github) that this error proably means that the collection I am sending has an out of date ETag with the patch request. I don't actually understand 100% what this means, but I tried to call `client.getTwin()` everytime that I try to send twin update, and indeed, "forcing" this update works, but it limits how fast I can update the twins as I have to wait for the update to then send the new value.
Also, it doesn't make sense to me having to know the old _reported_ properties that are stored in the cloud in order to send an update to a single value.

Again, I can be doing something wrong, but, if it is the case, I don't see where the mistake could be.

Thank you!

## Code sample exhibiting the issue
Straight trying to run the `DeviceTwinSample` class from the SDK examples with a newly created IoT Device throws me the error.

## Console log of the issue
```
Starting...
Beginning setup.
Successfully read input parameters.
Using communication protocol MQTT.
2022-04-13 22:56:56,179 INFO (main) [com.microsoft.azure.sdk.iot.device.transport.ExponentialBackoffWithJitter] - NOTE: A new instance of ExponentialBackoffWithJitter has been created with the following properties. Retry Count: 2147483647, Min Backoff Interval: 100, Max Backoff Interval: 10000, Max Time Between Retries: 100, Fast Retry Enabled: true
2022-04-13 22:56:56,370 DEBUG (main) [com.microsoft.azure.sdk.iot.device.ClientConfiguration] - Device configured to use software based SAS authentication provider
2022-04-13 22:56:56,378 INFO (main) [com.microsoft.azure.sdk.iot.device.transport.ExponentialBackoffWithJitter] - NOTE: A new instance of ExponentialBackoffWithJitter has been created with the following properties. Retry Count: 2147483647, Min Backoff Interval: 100, Max Backoff Interval: 10000, Max Time Between Retries: 100, Fast Retry Enabled: true
2022-04-13 22:56:56,382 DEBUG (main) [com.microsoft.azure.sdk.iot.device.DeviceClient] - Initialized a DeviceClient instance using SDK version 2.0.1
Successfully created an IoT Hub client.
Open connection to IoT Hub.
2022-04-13 22:56:56,428 DEBUG (main) [com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection] - Opening MQTT connection...
2022-04-13 22:56:56,518 DEBUG (main) [com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt] - Sending MQTT CONNECT packet...
2022-04-13 22:56:58,167 DEBUG (main) [com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt] - Sent MQTT CONNECT packet was acknowledged
2022-04-13 22:56:58,168 DEBUG (main) [com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt] - Sending MQTT SUBSCRIBE packet for topic devices/TESTDEVICE_GXA05-3/messages/devicebound/#
2022-04-13 22:56:58,402 DEBUG (main) [com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt] - Sent MQTT SUBSCRIBE packet for topic devices/TESTDEVICE_GXA05-3/messages/devicebound/# was acknowledged
2022-04-13 22:56:58,402 DEBUG (main) [com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection] - MQTT connection opened successfully
2022-04-13 22:56:58,403 DEBUG (main) [com.microsoft.azure.sdk.iot.device.transport.IotHubTransport] - The connection to the IoT Hub has been established
2022-04-13 22:56:58,403 DEBUG (main) [com.microsoft.azure.sdk.iot.device.transport.IotHubTransport] - Updating transport status to new status CONNECTED with reason CONNECTION_OK
2022-04-13 22:56:58,404 DEBUG (main) [com.microsoft.azure.sdk.iot.device.DeviceIO] - Starting worker threads
2022-04-13 22:56:58,406 DEBUG (main) [com.microsoft.azure.sdk.iot.device.transport.IotHubTransport] - Invoking connection status callbacks with new status details

CONNECTION STATUS UPDATE: CONNECTED
CONNECTION STATUS REASON: CONNECTION_OK
CONNECTION STATUS THROWABLE: null

The connection was successfully established. Can send messages.
2022-04-13 22:56:58,406 DEBUG (main) [com.microsoft.azure.sdk.iot.device.transport.IotHubTransport] - Client connection opened successfully
2022-04-13 22:56:58,407 INFO (main) [com.microsoft.azure.sdk.iot.device.DeviceClient] - Device client opened successfully
Start device Twin and get remaining properties...
2022-04-13 22:56:58,414 DEBUG (main) [com.microsoft.azure.sdk.iot.device.transport.IotHubTransport] - Message was queued to be sent later ( Message details: Correlation Id [c0cc29aa-3ea3-42cf-86e8-a9b92d3fac25] Message Id [c603e50b-97e7-48d6-9db2-506d1d7a2570] Device Operation Type [DEVICE_OPERATION_TWIN_SUBSCRIBE_DESIRED_PROPERTIES_REQUEST] )
2022-04-13 22:56:58,414 DEBUG (dcshared-iothub.azure-devices.net-TESTDEVICE_GXA05-3-0bc0f962-Cxn7296e619-7c36-499a-b2cc-21f5befd9dcf-azure-iot-sdk-IotHubSendTask) [com.microsoft.azure.sdk.iot.device.transport.IotHubTransport] - Sending message ( Message details: Correlation Id [c0cc29aa-3ea3-42cf-86e8-a9b92d3fac25] Message Id [c603e50b-97e7-48d6-9db2-506d1d7a2570] Device Operation Type [DEVICE_OPERATION_TWIN_SUBSCRIBE_DESIRED_PROPERTIES_REQUEST] )
2022-04-13 22:56:58,419 DEBUG (dcshared-iothub.azure-devices.net-TESTDEVICE_GXA05-3-0bc0f962-Cxn7296e619-7c36-499a-b2cc-21f5befd9dcf-azure-iot-sdk-IotHubSendTask) [com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt] - Sending MQTT SUBSCRIBE packet for topic $iothub/twin/res/#
2022-04-13 22:56:58,588 DEBUG (dcshared-iothub.azure-devices.net-TESTDEVICE_GXA05-3-0bc0f962-Cxn7296e619-7c36-499a-b2cc-21f5befd9dcf-azure-iot-sdk-IotHubSendTask) [com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt] - Sent MQTT SUBSCRIBE packet for topic $iothub/twin/res/# was acknowledged
2022-04-13 22:56:58,589 DEBUG (dcshared-iothub.azure-devices.net-TESTDEVICE_GXA05-3-0bc0f962-Cxn7296e619-7c36-499a-b2cc-21f5befd9dcf-azure-iot-sdk-IotHubSendTask) [com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt] - Sending MQTT SUBSCRIBE packet for topic $iothub/twin/PATCH/properties/desired/#
2022-04-13 22:56:58,795 DEBUG (dcshared-iothub.azure-devices.net-TESTDEVICE_GXA05-3-0bc0f962-Cxn7296e619-7c36-499a-b2cc-21f5befd9dcf-azure-iot-sdk-IotHubSendTask) [com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt] - Sent MQTT SUBSCRIBE packet for topic $iothub/twin/PATCH/properties/desired/# was acknowledged
2022-04-13 22:56:58,795 DEBUG (dcshared-iothub.azure-devices.net-TESTDEVICE_GXA05-3-0bc0f962-Cxn7296e619-7c36-499a-b2cc-21f5befd9dcf-azure-iot-sdk-IotHubSendTask) [com.microsoft.azure.sdk.iot.device.transport.IotHubTransport] - Invoking the callback function for sent message, IoT Hub responded to message ( Message details: Correlation Id [c0cc29aa-3ea3-42cf-86e8-a9b92d3fac25] Message Id [c603e50b-97e7-48d6-9db2-506d1d7a2570] Device Operation Type [DEVICE_OPERATION_TWIN_SUBSCRIBE_DESIRED_PROPERTIES_REQUEST] ) with status OK
Successfully subscribed to desired properties. Getting initial twin state
2022-04-13 22:56:58,797 DEBUG (dcshared-iothub.azure-devices.net-TESTDEVICE_GXA05-3-0bc0f962-Cxn7296e619-7c36-499a-b2cc-21f5befd9dcf-azure-iot-sdk-IotHubSendTask) [com.microsoft.azure.sdk.iot.device.transport.IotHubTransport] - Message was queued to be sent later ( Message details: Correlation Id [4245a06e-df71-4613-8b4a-6c326b72abca] Message Id [23235a68-7c57-4d8b-8762-46e22beea363] Request Id [4245a06e-df71-4613-8b4a-6c326b72abca] Device Operation Type [DEVICE_OPERATION_TWIN_GET_REQUEST] )
2022-04-13 22:56:58,808 DEBUG (dcshared-iothub.azure-devices.net-TESTDEVICE_GXA05-3-0bc0f962-Cxn7296e619-7c36-499a-b2cc-21f5befd9dcf-azure-iot-sdk-IotHubSendTask) [com.microsoft.azure.sdk.iot.device.transport.IotHubTransport] - Sending message ( Message details: Correlation Id [4245a06e-df71-4613-8b4a-6c326b72abca] Message Id [23235a68-7c57-4d8b-8762-46e22beea363] Request Id [4245a06e-df71-4613-8b4a-6c326b72abca] Device Operation Type [DEVICE_OPERATION_TWIN_GET_REQUEST] )
2022-04-13 22:56:58,978 DEBUG (MQTT Call: TESTDEVICE_GXA05-3) [com.microsoft.azure.sdk.iot.device.transport.IotHubTransport] - IotHub message was acknowledged. Checking if there is record of sending this message ( Message details: Correlation Id [4245a06e-df71-4613-8b4a-6c326b72abca] Message Id [23235a68-7c57-4d8b-8762-46e22beea363] Request Id [4245a06e-df71-4613-8b4a-6c326b72abca] Device Operation Type [DEVICE_OPERATION_TWIN_GET_REQUEST] )
2022-04-13 22:56:58,979 DEBUG (dcshared-iothub.azure-devices.net-TESTDEVICE_GXA05-3-0bc0f962-Cxn7296e619-7c36-499a-b2cc-21f5befd9dcf-azure-iot-sdk-IotHubSendTask) [com.microsoft.azure.sdk.iot.device.transport.IotHubTransport] - Invoking the callback function for sent message, IoT Hub responded to message ( Message details: Correlation Id [4245a06e-df71-4613-8b4a-6c326b72abca] Message Id [23235a68-7c57-4d8b-8762-46e22beea363] Request Id [4245a06e-df71-4613-8b4a-6c326b72abca] Device Operation Type [DEVICE_OPERATION_TWIN_GET_REQUEST] ) with status OK
2022-04-13 22:56:58,985 DEBUG (MQTT Call: TESTDEVICE_GXA05-3) [com.microsoft.azure.sdk.iot.device.transport.IotHubTransport] - Message was received from IotHub ( Message details: Correlation Id [4245a06e-df71-4613-8b4a-6c326b72abca] Message Id [31f65a5b-cfc2-4a15-8530-3092c3f3724d] Request Id [4245a06e-df71-4613-8b4a-6c326b72abca] Device Operation Type [DEVICE_OPERATION_TWIN_GET_RESPONSE] )
2022-04-13 22:56:58,986 DEBUG (dcshared-iothub.azure-devices.net-TESTDEVICE_GXA05-3-0bc0f962-Cxn7296e619-7c36-499a-b2cc-21f5befd9dcf-azure-iot-sdk-IotHubReceiveTask) [com.microsoft.azure.sdk.iot.device.transport.IotHubTransport] - Executing callback for received message ( Message details: Correlation Id [4245a06e-df71-4613-8b4a-6c326b72abca] Message Id [31f65a5b-cfc2-4a15-8530-3092c3f3724d] Request Id [4245a06e-df71-4613-8b4a-6c326b72abca] Device Operation Type [DEVICE_OPERATION_TWIN_GET_RESPONSE] )
2022-04-13 22:56:58,987 DEBUG (dcshared-iothub.azure-devices.net-TESTDEVICE_GXA05-3-0bc0f962-Cxn7296e619-7c36-499a-b2cc-21f5befd9dcf-azure-iot-sdk-IotHubReceiveTask) [com.microsoft.azure.sdk.iot.device.transport.IotHubTransport] - Sending acknowledgement for received cloud to device message ( Message details: Correlation Id [4245a06e-df71-4613-8b4a-6c326b72abca] Message Id [31f65a5b-cfc2-4a15-8530-3092c3f3724d] Request Id [4245a06e-df71-4613-8b4a-6c326b72abca] Device Operation Type [DEVICE_OPERATION_TWIN_GET_RESPONSE] )
Received initial twin state
{"properties":{"desired":{"$version":1},"reported":{"$version":1}}}
Update reported properties...
2022-04-13 22:56:59,056 DEBUG (main) [com.microsoft.azure.sdk.iot.device.transport.IotHubTransport] - Message was queued to be sent later ( Message details: Correlation Id [e9c24a6c-04c1-41bc-994e-f446ee9d6a3e] Message Id [72add66e-05b5-4c9c-87d0-ba48d42f6093] Request Id [e9c24a6c-04c1-41bc-994e-f446ee9d6a3e] Device Operation Type [DEVICE_OPERATION_TWIN_UPDATE_REPORTED_PROPERTIES_REQUEST] )
2022-04-13 22:56:59,056 DEBUG (dcshared-iothub.azure-devices.net-TESTDEVICE_GXA05-3-0bc0f962-Cxn7296e619-7c36-499a-b2cc-21f5befd9dcf-azure-iot-sdk-IotHubSendTask) [com.microsoft.azure.sdk.iot.device.transport.IotHubTransport] - Sending message ( Message details: Correlation Id [e9c24a6c-04c1-41bc-994e-f446ee9d6a3e] Message Id [72add66e-05b5-4c9c-87d0-ba48d42f6093] Request Id [e9c24a6c-04c1-41bc-994e-f446ee9d6a3e] Device Operation Type [DEVICE_OPERATION_TWIN_UPDATE_REPORTED_PROPERTIES_REQUEST] )
2022-04-13 22:56:59,409 DEBUG (MQTT Call: TESTDEVICE_GXA05-3) [com.microsoft.azure.sdk.iot.device.transport.IotHubTransport] - IotHub message was acknowledged. Checking if there is record of sending this message ( Message details: Correlation Id [e9c24a6c-04c1-41bc-994e-f446ee9d6a3e] Message Id [72add66e-05b5-4c9c-87d0-ba48d42f6093] Request Id [e9c24a6c-04c1-41bc-994e-f446ee9d6a3e] Device Operation Type [DEVICE_OPERATION_TWIN_UPDATE_REPORTED_PROPERTIES_REQUEST] )
2022-04-13 22:56:59,409 DEBUG (dcshared-iothub.azure-devices.net-TESTDEVICE_GXA05-3-0bc0f962-Cxn7296e619-7c36-499a-b2cc-21f5befd9dcf-azure-iot-sdk-IotHubSendTask) [com.microsoft.azure.sdk.iot.device.transport.IotHubTransport] - Invoking the callback function for sent message, IoT Hub responded to message ( Message details: Correlation Id [e9c24a6c-04c1-41bc-994e-f446ee9d6a3e] Message Id [72add66e-05b5-4c9c-87d0-ba48d42f6093] Request Id [e9c24a6c-04c1-41bc-994e-f446ee9d6a3e] Device Operation Type [DEVICE_OPERATION_TWIN_UPDATE_REPORTED_PROPERTIES_REQUEST] ) with status OK
2022-04-13 22:56:59,410 DEBUG (MQTT Call: TESTDEVICE_GXA05-3) [com.microsoft.azure.sdk.iot.device.transport.IotHubTransport] - Message was received from IotHub ( Message details: Correlation Id [e9c24a6c-04c1-41bc-994e-f446ee9d6a3e] Message Id [0bbd0dc7-1878-4b0d-ab34-b4a29e0a2241] Request Id [e9c24a6c-04c1-41bc-994e-f446ee9d6a3e] Device Operation Type [DEVICE_OPERATION_TWIN_UPDATE_REPORTED_PROPERTIES_RESPONSE] )
2022-04-13 22:56:59,410 DEBUG (dcshared-iothub.azure-devices.net-TESTDEVICE_GXA05-3-0bc0f962-Cxn7296e619-7c36-499a-b2cc-21f5befd9dcf-azure-iot-sdk-IotHubReceiveTask) [com.microsoft.azure.sdk.iot.device.transport.IotHubTransport] - Executing callback for received message ( Message details: Correlation Id [e9c24a6c-04c1-41bc-994e-f446ee9d6a3e] Message Id [0bbd0dc7-1878-4b0d-ab34-b4a29e0a2241] Request Id [e9c24a6c-04c1-41bc-994e-f446ee9d6a3e] Device Operation Type [DEVICE_OPERATION_TWIN_UPDATE_REPORTED_PROPERTIES_RESPONSE] )
2022-04-13 22:56:59,410 DEBUG (dcshared-iothub.azure-devices.net-TESTDEVICE_GXA05-3-0bc0f962-Cxn7296e619-7c36-499a-b2cc-21f5befd9dcf-azure-iot-sdk-IotHubReceiveTask) [com.microsoft.azure.sdk.iot.device.transport.IotHubTransport] - Sending acknowledgement for received cloud to device message ( Message details: Correlation Id [e9c24a6c-04c1-41bc-994e-f446ee9d6a3e] Message Id [0bbd0dc7-1878-4b0d-ab34-b4a29e0a2241] Request Id [e9c24a6c-04c1-41bc-994e-f446ee9d6a3e] Device Operation Type [DEVICE_OPERATION_TWIN_UPDATE_REPORTED_PROPERTIES_RESPONSE] )
Reported properties failed to be updated. Status code: PRECONDITION_FAILED
Press any key to exit...
com.microsoft.azure.sdk.iot.device.exceptions.IotHubClientException: Received an unsuccessful operation error code from the service: PRECONDITION_FAILED
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.onMessageReceived(IotHubTransport.java:332)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.onMessageArrived(MqttIotHubConnection.java:488)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.messageArrived(Mqtt.java:364)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:514)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:417)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:214)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by gabrielandrade2** [comment]
@timtay-microsoft. Thank you for your answer. I'll check that link out.

However, I still am a little bit curious on why does my device needs to be aware of the (probably) outdated reported properties from the cloud, if the device itself is the one producing and reporting those properties.
Maybe there is an use case for this that I don't see, but at lease for my usage I think that such behavior doesn't make sense.

**Comment by timtay-microsoft** [comment]
[This document](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins#optimistic-concurrency) highlights why you should care about this version field. Even if a single device is the only one sending these updates, there is some risk that a reported properties update can be lost due to the device being disconnected.

**Comment by gabrielandrade2** [comment]
@timtay-microsoft, I've managed to get the Twins working again after looking at the new example. Thank you for your support.
