### ISSUE TITLE
[Bug Report] NoSuchMethodError for GsonBuilder 

### ISSUE THREAD

**Issue by DawidWasala** [Azure/azure-iot-sdk-java#1602]
- **OS and version used:** MacOS 12.4

- **Java runtime used:** 11.0.16.1+1-LTS Microsoft OpenJDK

- **SDK version used:** com.microsoft.azure.sdk.iot:iot-service-client:2.1.2

# Description of the issue:
NoSuchMethodError is thrown when executing TwinClient.get() method. Method is present when deserializing GSON library in IDE. Exception is thrown only when code is triggered by HTTP Request, when running the method in unit tests the twin data is fetched successfully. Tried adding manually latest GSON version and excluding the old GSON dependency from iot-service-client in maven, but it did not fix the issue.
No transitive dependencies found when executing mvn dependency:tree. Attaching dependency tree below:

[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ azure-function-examples ---
[INFO] com.example:azure-function-examples:jar:1.0.0-SNAPSHOT
[INFO] +- org.slf4j:slf4j-log4j12:jar:1.7.29:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.29:compile
[INFO] |  \- log4j:log4j:jar:1.2.17:compile
[INFO] +- org.projectlombok:lombok:jar:1.18.24:compile
[INFO] +- com.microsoft.azure.functions:azure-functions-java-library:jar:2.0.1:compile
[INFO] |  \- com.microsoft.azure.functions:azure-functions-java-core-library:jar:1.0.0:compile
[INFO] +- com.microsoft.azure.sdk.iot:iot-service-client:jar:2.1.2:compile
[INFO] |  +- com.microsoft.rest:client-runtime:jar:1.7.14:compile
[INFO] |  |  +- com.squareup.retrofit2:retrofit:jar:2.6.4:compile
[INFO] |  |  +- com.squareup.okhttp3:okhttp:jar:3.12.12:compile
[INFO] |  |  |  \- com.squareup.okio:okio:jar:1.15.0:compile
[INFO] |  |  +- com.squareup.okhttp3:logging-interceptor:jar:3.12.12:compile
[INFO] |  |  +- com.squareup.okhttp3:okhttp-urlconnection:jar:3.12.12:compile
[INFO] |  |  +- com.squareup.retrofit2:converter-jackson:jar:2.6.4:compile
[INFO] |  |  +- org.apache.commons:commons-lang3:jar:3.4:compile
[INFO] |  |  +- io.reactivex:rxjava:jar:1.3.8:compile
[INFO] |  |  +- com.squareup.retrofit2:adapter-rxjava:jar:2.6.4:compile
[INFO] |  |  \- com.microsoft.azure:azure-annotations:jar:1.10.0:compile
[INFO] |  +- org.apache.qpid:proton-j:jar:0.34.0:compile
[INFO] |  +- com.microsoft.azure:qpid-proton-j-extensions:jar:1.2.4:compile
[INFO] |  +- com.google.code.gson:gson:jar:2.9.0:compile
[INFO] |  +- com.azure:azure-core:jar:1.13.0:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.11.3:compile
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.11.3:compile
[INFO] |  |  |  +- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.11.3:compile
[INFO] |  |  |  |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.2:compile
[INFO] |  |  |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.1:compile
[INFO] |  |  |  +- org.codehaus.woodstox:stax2-api:jar:4.2.1:compile
[INFO] |  |  |  \- com.fasterxml.woodstox:woodstox-core:jar:6.2.1:compile
[INFO] |  |  +- io.projectreactor:reactor-core:jar:3.3.12.RELEASE:compile
[INFO] |  |  |  \- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO] |  |  \- io.netty:netty-tcnative-boringssl-static:jar:2.0.35.Final:compile
[INFO] |  +- commons-codec:commons-codec:jar:1.14:compile
[INFO] |  +- com.google.guava:guava:jar:31.1-jre:compile
[INFO] |  |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  |  +- org.checkerframework:checker-qual:jar:3.12.0:compile
[INFO] |  |  +- com.google.errorprone:error_prone_annotations:jar:2.11.0:compile
[INFO] |  |  \- com.google.j2objc:j2objc-annotations:jar:1.3:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.13.2.1:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.13.2:compile
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.13.2:compile
[INFO] |  \- com.fasterxml.jackson.datatype:jackson-datatype-joda:jar:2.13.2:compile
[INFO] |     \- joda-time:joda-time:jar:2.10.8:compile
[INFO] +- org.junit.jupiter:junit-jupiter-api:jar:5.9.0:test
[INFO] |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |  +- org.junit.platform:junit-platform-commons:jar:1.9.0:test
[INFO] |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO] +- org.mockito:mockito-core:jar:4.8.0:test
[INFO] |  +- net.bytebuddy:byte-buddy:jar:1.12.14:test
[INFO] |  +- net.bytebuddy:byte-buddy-agent:jar:1.12.14:test
[INFO] |  \- org.objenesis:objenesis:jar:3.2:test
[INFO] \- org.mockito:mockito-junit-jupiter:jar:4.8.0:test

# Code sample exhibiting the issue

    @FunctionName("GetTest1Device")
    public HttpResponseMessage run(
            @HttpTrigger(
                name = "req",
                methods = {HttpMethod.GET},
                authLevel = AuthorizationLevel.ANONYMOUS)
                HttpRequestMessage<Optional<String>> request,
            final ExecutionContext context) throws IOException, IotHubException {
        context.getLogger().info("Java HTTP trigger processed a request2.");

        TwinClient twinClient = new TwinClient(IOTHUB_URI);
        Twin twin = twinClient.get("device44");
        return request.createResponseBuilder(HttpStatus.OK)
            .body(twin)
            .header("Content-Type", "application/json")
            .build();

    }

# Console log of the issue:
[2022-09-23T09:29:44.037Z] Caused by: java.lang.NoSuchMethodError: 'com.google.gson.GsonBuilder com.google.gson.GsonBuilder.setObjectToNumberStrategy(com.google.gson.ToNumberStrategy)' 
[2022-09-23T09:29:44.037Z] 	at com.microsoft.azure.sdk.iot.service.twin.TwinGsonBuilder.getGson(TwinGsonBuilder.java:27)
[2022-09-23T09:29:44.037Z] 	at com.microsoft.azure.sdk.iot.service.twin.TwinState.<init>(TwinState.java:434)
[2022-09-23T09:29:44.037Z] 	at com.microsoft.azure.sdk.iot.service.twin.Twin.fromJson(Twin.java:92)
[2022-09-23T09:29:44.037Z] 	at com.microsoft.azure.sdk.iot.service.twin.TwinClient.get(TwinClient.java:222)
[2022-09-23T09:29:44.037Z] 	at com.microsoft.azure.sdk.iot.service.twin.TwinClient.get(TwinClient.java:195)
[2022-09-23T09:29:44.037Z] 	at org.example.functions.HttpTriggerFunction.run(HttpTriggerFunction.java:39)

**Comment by DawidWasala** [comment]
I managed to fix it on my own. For anyone struggling with the issue I suggest debugging it in runtime and check where from is the library loaded. In my scenario it was loaded from azure-core-tools (not maven directory). For me, updating the azure-core-tools to latest version fixed the issue.
