### ISSUE TITLE
[Bug Report] MQTT_WS not working with Java 17

### ISSUE THREAD

**Issue by Xerxekyran** [Azure/azure-iot-sdk-java#1614]
# Context

- **OS and version used:** Linux with Kernel 4.4.302 
- **Java runtime used:** several, see details below
- **SDK version used:** 2.1.1

## Description of the issue
Basically the problem is as simple as _DeviceClient::open_  does not work with Java 17 when the MQTT_WS protocol is used. I did several tests with target Java compile versions of the application (code to reproduce below) as well as different Java Runtime versions for the executions. The exception in the error cases I am facing is:

```
com.microsoft.azure.sdk.iot.device.exceptions.IotHubClientException: Failed to open the client due to network issues. See inner exception for more details
        at com.microsoft.azure.sdk.iot.device.transport.TransportException.toIotHubClientException(TransportException.java:109)
        at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:106)
        at com.microsoft.azure.sdk.iot.device.InternalClient.open(InternalClient.java:162)
        at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:195)
        at azuretest.AzureTest.main(AzureTest.java:63)
Caused by: com.microsoft.azure.sdk.iot.device.transport.ProtocolException: Unable to establish MQTT connection
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:63)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connect(Mqtt.java:132)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttMessaging.start(MqttMessaging.java:61)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:285)
        at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:1309)
        at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.open(IotHubTransport.java:498)
        at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:102)
        ... 3 more
Caused by: Timed out waiting for a response from the server (32000)
        at org.eclipse.paho.client.mqttv3.internal.Token.waitForCompletion(Token.java:112)
        at org.eclipse.paho.client.mqttv3.MqttToken.waitForCompletion(MqttToken.java:67)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connect(Mqtt.java:123)
        ... 8 more
```

## Code sample exhibiting the issue
```
ClientOptions.ClientOptionsBuilder clientOptionsBuilder = ClientOptions.builder();
SSLContext sslContext = SSLContextBuilder.buildSSLContext(getPublicCertificate(), getPrivateKey());
clientOptionsBuilder = clientOptionsBuilder.sslContext(sslContext);

DeviceClient client = new DeviceClient("<connection_string>", MQTT_WS, clientOptionsBuilder.build());
client.open(false);
```

From my tested combinations I would think that there is a problem with the Java 17 runtime in this case:

| Compile target Java version | Runtime Java version | IotHubClientProtocol | Result |  
|-----------------------------|----------------------|----------------------|--------|
| 8                           | 8                    | MQTT_WS              | OK     |  
| 8                           | 17                    | MQTT_WS              | Error |  
| 8                           | 17                    | MQTT              | OK |  
| 11                           | 11                    | MQTT_WS              | OK |  
| 11                           | 11                    | MQTT              | OK |  
| 11                           | 17                    | MQTT_WS              | Error |  
| 11                           | 17                    | MQTT              | OK |  
| 17                           | 17                    | MQTT_WS              | Error |  
| 17                           | 17                    | MQTT              | OK |  

If I can give any more information about the problem or do different tests please tell me so.

**Comment by timtay-microsoft** [comment]
Do you see the same behavior when trying to connect with a symmetric key authenticated device (as opposed to your x509 authenticated device)?

**Comment by Xerxekyran** [comment]
Using a symmetric key authentication works with Java 17 and MQTT_WS as well as MQTT.

**Comment by timtay-microsoft** [comment]
Hm, interesting. We'll try to take a look into this when we get the chance

**Comment by tmahmood-microsoft** [comment]
@Xerxekyran can you please provide complete console log for the when the issue occurs for you. So far, I have not been able to reproduce the issue using the same Java, SDK and Linux kernel version.

**Comment by tmahmood-microsoft** [comment]
@Xerxekyran I am still not able to reproduce it when using Azul JRE 17 for execution. Can you please try using open JDK 17 and check if the issue persists?

**Comment by Xerxekyran** [comment]
@tmahmood-microsoft When testing with the Eclipse OpenJDK 17 (https://adoptium.net/, Linux, ARM, jre, 17.0.5+8) I see the same results. MQTT works, MQTT_WS runs into that timeout...
As other Java versions work with MQTT_WS I do not think this has to do with any network infrastructure stuff at my location?

**Comment by tmahmood-microsoft** [comment]
@Xerxekyran unfortunately I am still not able to reproduce the issue. It looks like there might be some issue with the infrastructure or setup you have on your end causing it to fail with java 17. I would recommend using another java version.

You can find details about recommended platforms for the SDK: https://github.com/Azure/azure-iot-sdk-java/blob/main/supported_platforms.md

**Comment by Xerxekyran** [comment]
@tmahmood-microsoft After coming back to this issue, I retested things and now everyting seems to work just fine. I can not tell you what changed, as it is not my code or the OS. So it seems there was some kind of network issue. Thank you for your effort and sorry to raise an issue that seems not to be a problem with the iot-sdk.
