### ISSUE TITLE
[Bug Report] OutOfMemory Error due to growing correlatingCallbacks map in IoTHubTransport.class

### ISSUE THREAD

**Issue by tarekmues** [Azure/azure-iot-sdk-java#1629]
# Context

- **OS and version used**: Ubuntu Server 22.04, MacOS Ventura
- **Java runtime used**: openjdk-17-alpine (Docker container)
- **SDK version used**: 2.1.2

## Description of the issue
While the app is running and sending twin reported properties for a while, the correlating callbacks map in IotHubTransport.class grows endlessly. Managing several virtual devices in one application, it eventually leads to an OutOfMemory error due to a massive amount of correlating Callbacks to messages which response has already been handled.

To reproduce the error in a short amount of time, I've created a simple code example that just updates the reported properties over and over. Choose a small heapsize (I set 22mb for me in a spring boot environment, took about 15min with the example down below) for the vm in order to reproduce the exception.

## Code sample exhibiting the issue
```
    String connectionString = ""; //insert your connection string here
    DeviceClient client = new DeviceClient(connectionString, IotHubClientProtocol.AMQPS_WS);
    client.open(false);
    client.subscribeToDesiredProperties(new DesiredPropertiesCallback() {
        @Override
        public void onDesiredPropertiesUpdated(Twin twin, Object context) {
            //do nothing
        }
    }, null);`
    
    while (true) {
        TwinCollection reportedProperties = client.getTwin().getReportedProperties();
        client.updateReportedProperties(reportedProperties);
        Thread.sleep(400);
    }
```

## Console log of the issue
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'test': Injection of autowired dependencies failed; nested exception is java.lang.OutOfMemoryError: Java heap space
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:405) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.5.jar:2.7.5]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.5.jar:2.7.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.5.jar:2.7.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.5.jar:2.7.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.5.jar:2.7.5]
	at com.example.demo.DemoApplication.main(DemoApplication.java:10) ~[main/:na]
Caused by: java.lang.OutOfMemoryError: Java heap space
```

**Comment by brycewang-microsoft** [comment]
Hi @tarekmues, thanks for bringing this to our attention and sharing the code snippet with us! 

We have successfully reproduced this issue and will make a fix ASAP. Will keep you updated here.

**Comment by brycewang-microsoft** [comment]
#1647 should fix this issue. I will update here again once we release a newer version including this fix.

**Comment by brycewang-microsoft** [comment]
The hub device client package [2.1.4](https://github.com/Azure/azure-iot-sdk-java/releases/tag/2023-01-23) has been released with the fix included, so I am closing this thread.
