### ISSUE TITLE
[Bug Report] Unable to upload to Azure Blob Storage after closing and re-opening DeviceClient

### ISSUE THREAD

**Issue by gabrielandrade2** [Azure/azure-iot-sdk-java#1662]
# Context

- **OS and version used:** Ubuntu 22.04.1
- **Java runtime used:** 17.0.5
- **SDK version used:** 2.1.2 and 2.1.3

## Description of the issue
To give a bit of context, I have a piece of code in my project that, after receiving a DirectMethod request, uploads a file to Azure Blob Storage and returns the generated URL as the DirectMethod response. This works just fine as long as I don't have any disconnection events or purposefully disable and re-enable the IoT connection.

After a disconnection and reconnection occur, when I try the same process, the blob upload fails when I call `client.getFileUploadSasUri`, which gives me the stack trace in the log section. This only happens if the disconnection/reconnection occurs after at least one blob has been uploaded before it.

I was also able to reproduce the same behavior using the `FileUploadSimpleSample.java` example code, by modifying it to upload the file more than one time. I attached the source for this in this post.

**_Possible cause:_** Upon some investigation in the SDK source code, I noticed that in the `com.microsoft.azure.sdk.iot.device.FileUpload` class, `httpsTransportManager` is received as a parameter and have `open()` called. 

However, when `DeviceClient`  is closed (in a disconnection event), this object is also closed and unless a new `DeviceClient` is instantiated it is never opened again, so the internal `httpsIotHubConnection` object remains null and causes the Exception, even though we are connected to the cloud.

I believe that `open()` should be called again, either when `DeviceClient.open()` is called again or when the first blob upload occurs.

Thank you for your time in supporting this.

## Code sample exhibiting the issue
```
package samples.com.microsoft.azure.sdk.iot;

import com.azure.storage.blob.BlobClient;
import com.azure.storage.blob.BlobClientBuilder;
import com.microsoft.azure.sdk.iot.device.FileUploadCompletionNotification;
import com.microsoft.azure.sdk.iot.device.FileUploadSasUriRequest;
import com.microsoft.azure.sdk.iot.device.FileUploadSasUriResponse;
import com.microsoft.azure.sdk.iot.device.DeviceClient;
import com.microsoft.azure.sdk.iot.device.IotHubClientProtocol;
import com.microsoft.azure.sdk.iot.device.exceptions.IotHubClientException;

import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.nio.charset.StandardCharsets;
import java.util.Scanner;

/**
 * File Upload Simple Sample for an IoT Hub. This is a sample
 * that upload a single file to blob using the IoT Hub.
 */
public class FileUploadSimpleSample
{
    /**
     * Upload a single file to blobs using IoT Hub.
     *
     * @param args
     * args[0] = IoT Hub connection string
     * args[1] = File to upload
     */
    public static void main(String[] args)
            throws IOException, URISyntaxException, IotHubClientException
    {
        String connString;
        String fullFileName;

        System.out.println("Starting...");
        System.out.println("Beginning setup.");


        if (args.length == 2)
        {
            connString = args[0];
            fullFileName = args[1];
        }
        else
        {
            System.out.format(
                    "Expected the following argument but received: %d.\n"
                            + "The program should be called with the following args: \n"
                            + "[Device connection string] - String containing Hostname, Device Id & Device Key in the following formats: HostName=<iothub_host_name>;DeviceId=<device_id>;SharedAccessKey=<device_key>\n"
                            + "[File to upload] - String containing the full path for the file to upload.\n",
                    args.length);
            return;
        }

        // File upload will always use HTTPS, DeviceClient will use this protocol only
        //   for the other services like Telemetry, Device Method and Device Twin.
        IotHubClientProtocol protocol = IotHubClientProtocol.MQTT;

        System.out.println("Successfully read input parameters.");

        DeviceClient client = new DeviceClient(connString, protocol);

        System.out.println("Successfully created an IoT Hub client.");

        // First upload should work and the rest fail.
        for(int i=0; i < 3; i++)
        {
            client.open(true);
            try
            {
                File file = new File(fullFileName);
                if (file.isDirectory())
                {
                    throw new IllegalArgumentException(fullFileName + " is a directory, please provide a single file name, or use the FileUploadSample to upload directories.");
                }

                System.out.println("Retrieving SAS URI from IoT Hub...");
                FileUploadSasUriResponse sasUriResponse = client.getFileUploadSasUri(new FileUploadSasUriRequest(file.getName()));

                System.out.println("Successfully got SAS URI from IoT Hub");
                System.out.println("Correlation Id: " + sasUriResponse.getCorrelationId());
                System.out.println("Container name: " + sasUriResponse.getContainerName());
                System.out.println("Blob name: " + sasUriResponse.getBlobName());
                System.out.println("Blob Uri: " + sasUriResponse.getBlobUri());

                System.out.println("Using the Azure Storage SDK to upload file to Azure Storage...");
 
                // No need to actually upload the file, just get the SAS URI
                // Here client is closed to simulate a disconnection event.
                client.close();

            }
            catch (Exception e)
            {
                System.out.println("On exception, shutting down \n" + " Cause: " + e.getCause() + " \nERROR: " + e.getMessage());
                System.out.println("Shutting down...");
                client.close();
            }
        }
        System.out.println("Press any key to exit...");

        Scanner scanner = new Scanner(System.in, StandardCharsets.UTF_8.name());
        scanner.nextLine();
        System.out.println("Shutting down...");
        client.close();
    }
}
```

## Console log of the issue

- Output of the sample code:
```
2023-01-26 01:49:35,110 INFO (main) [com.microsoft.azure.sdk.iot.device.DeviceClient] - Device client opened successfully
Retrieving SAS URI from IoT Hub...
2023-01-26 01:49:35,110 DEBUG (dcshared-iothub.azure-devices.net-SOFTECLYPSE_GXA05-8f2379b1-Cxnb124b597-df4c-4828-a65a-24ab21f4d35f-azure-iot-sdk-IotHubReconnectTask) [com.microsoft.azure.sdk.iot.device.transport.IotHubReconnectTask] - Starting reconnection process
On exception, shutting down 
 Cause: null 
ERROR: Cannot invoke "com.microsoft.azure.sdk.iot.device.transport.https.HttpsIotHubConnection.sendHttpsMessage(com.microsoft.azure.sdk.iot.device.transport.https.HttpsMessage, com.microsoft.azure.sdk.iot.device.transport.https.HttpsMethod, String, java.util.Map)" because "this.httpsIotHubConnection" is null
Shutting down...
2023-01-26 01:49:35,111 INFO (main) [com.microsoft.azure.sdk.iot.device.DeviceClient] - Closing device client...
```

- Ouput of my device:
```
Caused by: java.lang.NullPointerException: Cannot invoke "com.microsoft.azure.sdk.iot.device.transport.https.HttpsIotHubConnection.sendHttpsMessage(com.microsoft.azure.sdk.iot.device.transport.https.HttpsMessage, com.microsoft.azure.sdk.iot.device.transport.https.HttpsMethod, String, java.util.Map)" because "this.httpsIotHubConnection" is null
	at com.microsoft.azure.sdk.iot.device.transport.https.HttpsTransportManager.send(HttpsTransportManager.java:136) ~[?:?]
	at com.microsoft.azure.sdk.iot.device.transport.https.HttpsTransportManager.getFileUploadSasUri(HttpsTransportManager.java:90) ~[?:?]
	at com.microsoft.azure.sdk.iot.device.FileUpload.getFileUploadSasUri(FileUpload.java:37) ~[?:?]
	at com.microsoft.azure.sdk.iot.device.DeviceClient.getFileUploadSasUri(DeviceClient.java:244) ~[?:?]
	at [omitted].iot.azure.capabilities.BlobManager.upload(BlobManager.java:82) ~[?:?]
	at [omitted].iot.azure.capabilities.BlobManager.uploadFile(BlobManager.java:75) ~[?:?]
	at [omitted].iot.azure.capabilities.DirectMethodHandler.invoke(DirectMethodHandler.java:66) ~[?:?]
	... 11 more
``

**Comment by tmahmood-microsoft** [comment]
Hi @gabrielandrade2 thank you for bringing the issue to our attention. 
This issue has been fixed in the following pull request: https://github.com/Azure/azure-iot-sdk-java/pull/1666

Please let me know if this still does not work for you.

**Comment by gabrielandrade2** [comment]
Hello @tmahmood-microsoft!

Thank you for your work on this. I've built the latest master commit locally and confirmed that it fixes the issue I was having with my device.

I'll be looking forward to the next SDK release containing the fix.

**Comment by timtay-microsoft** [comment]
I'm glad to hear it works for you! We'll go ahead and keep this issue open until we release it just so that we don't forget to release it.

**Comment by brycewang-microsoft** [comment]
The hub device client package [2.1.5](https://github.com/Azure/azure-iot-sdk-java/releases/tag/2023-03-10) has been released with the fix included, so I am closing this thread.
