### ISSUE TITLE
[Bug Report] Error 500001 is not retried when sending device events

### ISSUE THREAD

**Issue by mwalser** [Azure/azure-iot-sdk-java#1672]
# Context

- **OS and version used:** Ubuntu 22.04
- **Java runtime used:** openjdk version "17.0.5" 2022-10-18
- **SDK version used:** iot-device-client 2.1.4

## Description of the issue
When using `deviceClient.sendEvent()` the [/devices/{id}/messages/events](https://learn.microsoft.com/en-us/rest/api/iothub/device/send-device-event) endpoint sometimes returns an 500001 error.

According to the documentation, this error should be retried by the SDK. The Azure Portal troubleshooting explicitly mentiones that:

> If you're seeing 500xxx errors (i.e. **500001** ServerError), the issue is likely temporary. Make sure your device can automatically retry: [How to manage connectivity and reliable messaging using Azure IoT Hub device SDKs](https://docs.microsoft.com/azure/iot-hub/iot-hub-reliability-features-in-sdks?WT.mc_id=Portal-Microsoft_Azure_Support#connection-and-retry)

It even mentions `500001` (which is exactly the error that we are getting) as an example of a **retriable** error, but according to the log the Device Client SDK sees things differently and thinks its non-retryable:
```
WARN  c.m.a.s.i.d.t.IotHubTransport - Encountering an non-retryable exception while sending a message, so it has been abandoned
```

## HTTP Communication
Request:
![iothub_request](https://user-images.githubusercontent.com/2938826/218096942-cee59920-717f-4c04-9bd5-4a499091f022.png)

Response:
![iothub_response](https://user-images.githubusercontent.com/2938826/218097161-3b39c356-3fb2-4974-8015-02d74c5fbaba.png)

## Code sample exhibiting the issue
The code is in Kotlin but uses the Java SDK:
```kotlin
val deviceClient = DeviceClient(deviceConnectionString, IotHubClientProtocol.HTTPS)
deviceClient.open(true)
deviceClient.sendEvents(listOf(Message(...), Message(...)))
```

## Console log of the issue
```
13:41:14.974 [main] INFO  c.m.a.sdk.iot.device.DeviceClient - Device client opened successfully
13:42:21.096 [XXXXX.azure-devices.net-it-tenant:it-device-8dab9318-Cxn-azure-iot-sdk-IotHubSendTask] WARN  c.m.a.s.i.d.t.IotHubTransport - Handling an exception from sending message: Attempt number 0
com.microsoft.azure.sdk.iot.device.transport.https.exceptions.InternalServerErrorException: 
	at com.microsoft.azure.sdk.iot.device.IotHubStatusCode.getConnectionStatusException(IotHubStatusCode.java:129)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.sendPacket(IotHubTransport.java:1573)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.sendMessages(IotHubTransport.java:751)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubSendTask.run(IotHubSendTask.java:61)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
13:42:21.097 [XXXXX.azure-devices.net-it-tenant:it-device-8dab9318-Cxn-azure-iot-sdk-IotHubSendTask] WARN  c.m.a.s.i.d.t.IotHubTransport - Encountering an non-retryable exception while sending a message, so it has been abandoned ( Message details: Correlation Id [356642ba-38ef-47ea-9ca1-a37d6f64dff8] Message Id [d2523f12-1405-40a2-9158-09ed6d608da4] )
com.microsoft.azure.sdk.iot.device.transport.https.exceptions.InternalServerErrorException: 
	at com.microsoft.azure.sdk.iot.device.IotHubStatusCode.getConnectionStatusException(IotHubStatusCode.java:129)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.sendPacket(IotHubTransport.java:1573)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.sendMessages(IotHubTransport.java:751)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubSendTask.run(IotHubSendTask.java:61)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

com.microsoft.azure.sdk.iot.device.exceptions.IotHubClientException: Received an unsuccessful operation error code from the service: INTERNAL_SERVER_ERROR
```

**Comment by brycewang-microsoft** [comment]
Hi @mwalser, thanks for bringing this to our attention! The fix has been merged in, and we will update this thread once we ship another release including it.

**Comment by brycewang-microsoft** [comment]
The hub device client package [2.1.5](https://github.com/Azure/azure-iot-sdk-java/releases/tag/2023-03-10) has been released with the fix included, so I am closing this thread.
