### ISSUE TITLE
Java Iot client failing when there is a value missing in the propertyString in C2D message.

### ISSUE THREAD

**Issue by sauravBhasin** [Azure/azure-iot-sdk-java#1726]
I am trying to receive a c2d message from IOThub using the java iot client. But the message's propertyString seems to have a field having missing value for trackingId.
<removed>%2Fmessages%2FdeviceBound&iothub-ack=full&iothub-creation-time-utc=2023-06-19T13:35:13.4276974Z&functionId=9**&trackingId=**&requestId=0

This results in an unhandled IndexOutOfBoundsException in the sdk at the following line in Mqtt.java class.
                //Expected format is <key>=<value> where both key and value may be encoded
                String key = propertyString.split("=")[PROPERTY_KEY_INDEX];
                String value = propertyString.split("=")[PROPERTY_VALUE_INDEX];

the callback is to be invoked only after this piece of code assigns the properties to the message but it fails here. 
It does not seem like we can override by providing a custom implementation for handling the missing properties.

Can you please suggest on how to handle this using the sdk as the C2D message can have empty values for some properties.

Stack Trace
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.assignPropertiesToMessage(Mqtt.java:476) ~[iot-device-client-2.2.0.jar:na]
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.constructMessage(Mqtt.java:442) ~[iot-device-client-2.2.0.jar:na]
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.receive(Mqtt.java:306) ~[iot-device-client-2.2.0.jar:na]
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.onMessageArrived(MqttIotHubConnection.java:458) ~[iot-device-client-2.2.0.jar:na]
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.messageArrived(Mqtt.java:364) ~[iot-device-client-2.2.0.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:519) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:417) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:na]
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:214) ~[org.eclipse.paho.client.mqttv3-1.2.5.jar:na]
	... 1 common frames omitted

**Comment by aliouuuw** [comment]
I am getting the same ArrayIndexOutOfBoudsException immediatly after I hit send a message on IotHub's Message to Device tool page.
Note however, the message is sent with no errors or exception when I use the Direct Method tool. 
It seems like in Mqtt.java (line 476), there's an attempt to access an element of index 1 in an array of length 1.
I'm new to a project using this SDK, so any help would be appreciated.
Again below is the StackTrace.
![Screenshot 2023-06-22 at 4 18 54 AM](https://github.com/Azure/azure-iot-sdk-java/assets/55468255/e085dc2c-f295-4283-a931-0feba4badd55)

**Comment by timtay-microsoft** [comment]
This is most likely a dupe of #1722 

The TL;DR is that the service behavior changed here unexpectedly. The service used to omit sending a key-value pair in the MQTT topic string if the value was null or empty. The service team is aware of this behavior and is working to fix it.

In the meantime, the way to avoid this issue is to make sure that any C2D message you send has its fields populated with something.

Alternatively, you can raise a support ticket in the Azure Portal for your particular IoT hub and a service engineer may be able to revert this service behavior for you.

**Comment by sauravBhasin** [comment]
Thanks a lot
