### ISSUE TITLE
[Bug Report] queryTwins throws exception java.lang.IllegalArgumentException: Key cannot be null or empty

### ISSUE THREAD

**Issue by ranjith-t** [Azure/azure-iot-sdk-java#1754]
Below code throws exception:
        val filter: String = "*"
        var sqlQuery: String = SqlQueryBuilder.createSqlQuery(filter, SqlQueryBuilder.FromType.DEVICES, null, null)
        var twinQueryResponse: TwinQueryResponse = queryClient.queryTwins(sqlQuery)

2023-10-18T23:35:32.262981076Z java.lang.IllegalArgumentException: Key cannot be null or empty
2023-10-18T23:35:32.262991077Z at com.microsoft.azure.sdk.iot.service.twin.TwinCollection.put(TwinCollection.java:206)
2023-10-18T23:35:32.263443794Z at com.microsoft.azure.sdk.iot.service.twin.TwinCollection.putAll(TwinCollection.java:185)
2023-10-18T23:35:32.263464295Z at com.microsoft.azure.sdk.iot.service.twin.TwinCollection.<init>(TwinCollection.java:128)
2023-10-18T23:35:32.263470596Z at com.microsoft.azure.sdk.iot.service.twin.TwinCollection.put(TwinCollection.java:211)
2023-10-18T23:35:32.263497197Z at com.microsoft.azure.sdk.iot.service.twin.TwinCollection.putAll(TwinCollection.java:185)
2023-10-18T23:35:32.263512197Z at com.microsoft.azure.sdk.iot.service.twin.TwinCollection.<init>(TwinCollection.java:128)
2023-10-18T23:35:32.266920332Z at com.microsoft.azure.sdk.iot.service.twin.TwinCollection.put(TwinCollection.java:211)
2023-10-18T23:35:32.266942833Z at com.microsoft.azure.sdk.iot.service.twin.TwinCollection.putAll(TwinCollection.java:185)
2023-10-18T23:35:32.266949233Z at com.microsoft.azure.sdk.iot.service.twin.TwinCollection.<init>(TwinCollection.java:128)
2023-10-18T23:35:32.266954633Z at com.microsoft.azure.sdk.iot.service.twin.TwinCollection.put(TwinCollection.java:211)
2023-10-18T23:35:32.266968234Z at com.microsoft.azure.sdk.iot.service.twin.TwinCollection.put(TwinCollection.java:98)
2023-10-18T23:35:32.266973334Z at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:188)
2023-10-18T23:35:32.266978334Z at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
2023-10-18T23:35:32.266983234Z at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
2023-10-18T23:35:32.266988235Z at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
2023-10-18T23:35:32.266993235Z at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
2023-10-18T23:35:32.266998535Z at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
2023-10-18T23:35:32.267003635Z at com.google.gson.Gson.fromJson(Gson.java:991)
2023-10-18T23:35:32.267008235Z at com.google.gson.Gson.fromJson(Gson.java:956)
2023-10-18T23:35:32.267012936Z at com.google.gson.Gson.fromJson(Gson.java:905)
2023-10-18T23:35:32.267017436Z at com.google.gson.Gson.fromJson(Gson.java:876)
2023-10-18T23:35:32.267022136Z at com.microsoft.azure.sdk.iot.service.twin.TwinState.<init>(TwinState.java:436)
2023-10-18T23:35:32.267027036Z at com.microsoft.azure.sdk.iot.service.twin.Twin.fromJson(Twin.java:92)
2023-10-18T23:35:32.267032036Z at com.microsoft.azure.sdk.iot.service.query.TwinQueryResponse.<init>(TwinQueryResponse.java:50)
2023-10-18T23:35:32.267036936Z at com.microsoft.azure.sdk.iot.service.query.QueryClient.queryTwins(QueryClient.java:202)

# Context
SDK: group: "com.microsoft.azure.sdk.iot", name: "iot-service-client", version:"2.1.6"
Ubuntu 18.04
- jvm
- **SDK version used:** 2.1.6

we are using KTor Kotlin based jar file

**Comment by timtay-microsoft** [comment]
Is there a device twin in your hub with an empty string as a key?

**Comment by ranjith-t** [comment]
> Is there a device twin in your hub with an empty string as a key?

Yes, there was one device twin with empty("") key value(that was also my expectation). But the exception is not throwing much information, at least I would expect it to point to the device?

**Comment by timtay-microsoft** [comment]
I would advise against using any empty strings as keys in any device's twin JSON. However, it does appear that IoT hub allows this. 

#1756 will allow the SDK to handle this case on the device SDK side.

If you'd like the service SDK to support allowing this as well, you'll need to file this issue on the [IoT hub service SDK repo](https://github.com/Azure/azure-iot-service-sdk-java/issues) as well since this repo doesn't own that code anymore.

**Comment by timtay-microsoft** [comment]
DPS service client version 2.0.3 and IoT hub device client 2.4.0 now allow empty strings as keys, so I'll close this thread
