### ISSUE TITLE
Device Provisioning throws CA certificate not found and errorCode:401002 Unauthorized

### ISSUE THREAD

**Issue by xtrycatchx** [Azure/azure-iot-sdk-java#203]
- **OS and version used:** macOS 10.13.3

- **Java runtime used:** 1.8.0_45

- **SDK version used:** 1.8.0_45

# Description of the issue:
I uploaded and verified my rootCA cert in DPS
In the DPS Manage Enrollment, I created an Enrollment Group with Identity Attestation Information as Intermediate Certificate (the same cert for primary and secondary)

My device cert is signed by the Intermediate Certificate in the Enrollment Group.

# Code sample exhibiting the issue:
modified /src/main/java/samples/com/microsoft/azure/sdk/iot/ProvisioningX509Sample.java

with the correct entries for :
```
private static final String idScope = "[My ID scope]";
private static final String globalEndpoint = "global.azure-devices-provisioning.net";
private static final ProvisioningDeviceClientTransportProtocol PROVISIONING_DEVICE_CLIENT_TRANSPORT_PROTOCOL = ProvisioningDeviceClientTransportProtocol.HTTPS;
private static final String leafPublicPem = "<My Device Public PEM Certificate here>";
private static final String leafPrivateKey = "<My Device Private PEM Key here>";
```

Also I added the chain in the sample java code, where in main I got this:
```
String intermediatePem = "<My Intermediate CA Cert Uploaded Signer Certificate here>";          
String rootPem = "<My Root Certificate used to Signed My Intermediate CA here>";

signerCertificates.add(intermediatePem);
signerCertificates.add(root);
```

# Console log of the issue:
However building (mvn clean package install) and running the output, I encountered this error:

```
Starting...
Beginning setup.
Waiting for Provisioning Service to register
java.util.concurrent.ExecutionException: com.microsoft.azure.sdk.iot.provisioning.device.internal.exceptions.ProvisioningDeviceHubException: {"errorCode":401002,"trackingId":"5abb3624-8dfc-47b1-a787-7173e9188197","message":"Unauthorized","timestampUtc":"2018-02-07T05:40:30.9608217Z"}
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at com.microsoft.azure.sdk.iot.provisioning.device.internal.task.ProvisioningTask.invokeRegister(ProvisioningTask.java:111)
        at com.microsoft.azure.sdk.iot.provisioning.device.internal.task.ProvisioningTask.call(ProvisioningTask.java:283)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.microsoft.azure.sdk.iot.provisioning.device.internal.exceptions.ProvisioningDeviceHubException: {"errorCode":401002,"trackingId":"5abb3624-8dfc-47b1-a787-7173e9188197","message":"Unauthorized","timestampUtc":"2018-02-07T05:40:30.9608217Z"}
        at com.microsoft.azure.sdk.iot.provisioning.device.internal.exceptions.ProvisioningDeviceClientExceptionManager.verifyHttpResponse(ProvisioningDeviceClientExceptionManager.java:28)
        at com.microsoft.azure.sdk.iot.provisioning.device.internal.contract.http.ContractAPIHttp.sendRequest(ContractAPIHttp.java:140)
        at com.microsoft.azure.sdk.iot.provisioning.device.internal.contract.http.ContractAPIHttp.authenticateWithProvisioningService(ContractAPIHttp.java:282)
        at com.microsoft.azure.sdk.iot.provisioning.device.internal.task.RegisterTask.authenticateWithX509(RegisterTask.java:130)
        at com.microsoft.azure.sdk.iot.provisioning.device.internal.task.RegisterTask.authenticateWithDPS(RegisterTask.java:283)
        at com.microsoft.azure.sdk.iot.provisioning.device.internal.task.RegisterTask.call(RegisterTask.java:308)
        at com.microsoft.azure.sdk.iot.provisioning.device.internal.task.RegisterTask.call(RegisterTask.java:33)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        ... 4 more
Registration error, bailing out
Press any key to exit...
```

and if i removed the intermediate CA pem from the signerCertificates list, I got this another issue:
```
//signerCertificates.add(intermediatePem);
signerCertificates.add(root);
```
issue:
Starting...
```
Beginning setup.
Waiting for Provisioning Service to register
Waiting for Provisioning Service to register
com.microsoft.azure.sdk.iot.provisioning.device.internal.exceptions.ProvisioningDeviceHubException: CA certificate not found
        at com.microsoft.azure.sdk.iot.provisioning.device.internal.task.ProvisioningTask.executeStateMachineForStatus(ProvisioningTask.java:232)
        at com.microsoft.azure.sdk.iot.provisioning.device.internal.task.ProvisioningTask.call(ProvisioningTask.java:285)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Registration error, bailing out
Press any key to exit...
```
And by the way, my rootCA was generated using openssl and is not issued from a trusted CA:
```
openssl genrsa -out rootCA.key 2048
openssl req -x509 -new -nodes -key rootCA.key -sha256 -days 1024 -out rootCA.pem
```
and also, my intermediate CA was generated using openssl:
```
openssl genrsa -out intermediate.key 2048
openssl req -new -key intermediate.key -out intermediate.csr
openssl x509 -req -days 360 -in intermediate.csr -CA rootCA.pem -CAkey rootCA.key -CAcreateserial -out intermediate.pem
```

**Comment by xtrycatchx** [comment]
If I use the provisioning-x509-cert-generator tool, this works. but if i use openssl, its failing :(

**Comment by xtrycatchx** [comment]
my openssl conf:
```
[ req ]
#default_bits           = 2048
#default_md             = sha256
#default_keyfile        = privkey.pem
distinguished_name      = req_distinguished_name
attributes              = req_attributes

[ req_distinguished_name ]
countryName                     = Country Name (2 letter code)
countryName_min                 = 2
countryName_max                 = 2
stateOrProvinceName             = State or Province Name (full name)
localityName                    = Locality Name (eg, city)
0.organizationName              = Organization Name (eg, company)
organizationalUnitName          = Organizational Unit Name (eg, section)
commonName                      = Common Name (eg, fully qualified host name)
commonName_max                  = 64
emailAddress                    = Email Address
emailAddress_max                = 64

[ req_attributes ]
challengePassword               = A challenge password
challengePassword_min           = 4
challengePassword_max           = 20

[ v3_ca ]
subjectKeyIdentifier            = hash
basicConstraints                = CA:true
```

my commands to create the keys for rootCA, intermediateCA and device
```
openssl genrsa -out rootCA.key 2048
openssl req -new -x509 -extensions v3_ca -key rootCA.key -out rootCA.pem -days 365
openssl genrsa -out intermediateCA.key 2048
openssl req -new -key intermediateCA.key -out intermediateCA.csr
openssl x509 -req -days 360 -in intermediateCA.csr -CA rootCA.pem -CAkey rootCA.key -CAcreateserial -out intermediateCA.pem
openssl genrsa -out device.key 2048
openssl req -new -key device.key -out device.csr
openssl x509 -req -days 360 -in device.csr -CA intermediateCA.pem -CAkey intermediateCA.key -CAcreateserial -out device.pem
```

**Comment by prmathur-microsoft** [comment]
As a part of this check-in https://github.com/Azure/azure-iot-sdk-java/commit/cef000f0eb24c22821b0602543fc06cbe1775237 we have a potential fix for this issue. Maven packages for this fix will be released on 2/9. Until then can you try our master branch and let me know if you still see the issue ?

**Comment by prmathur-microsoft** [comment]
New maven packages with a potential fix for this issue are released. Feel free to reopen this issue if you still see any problems. Closing this issue for now.

**Comment by yzhong94** [comment]
@xtrycatchx thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute customer satisfaction survey.

**Comment by MZDN** [comment]
I faced the same issue a the top:
java -jar ./provisioning-X509-sample-1.4.1-with-deps.jar 
Starting...
Beginning setup.
Waiting for Provisioning Service to register
Waiting for Provisioning Service to register
com.microsoft.azure.sdk.iot.provisioning.device.internal.exceptions.ProvisioningDeviceHubException: CA certificate not found
	at com.microsoft.azure.sdk.iot.provisioning.device.internal.task.ProvisioningTask.executeStateMachineForStatus(ProvisioningTask.java:233)
	at com.microsoft.azure.sdk.iot.provisioning.device.internal.task.ProvisioningTask.call(ProvisioningTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Registration error, bailing out

I used the java -jar ./provisioning-x509-cert-generator-1.4.1-with-deps.jar to create needed certs.

**Comment by timtay-microsoft** [comment]
@MZDN did you upload your certificates to the azure portal already? That exception is saying that the certificate you are trying to use for registration was not registered in the portal.
