### ISSUE TITLE
When sending a C2D message on the DeviceExplorer, "Lost connection to the server...." is output.

### ISSUE THREAD

**Issue by kaki-mon** [Azure/azure-iot-sdk-java#206]
- **OS and version used:** Windows 10 

- **Java runtime used:** Java 8 

- **SDK version used:** 1.8.0 

# Description of the issue:

When sending the C2D message from the Azure portal's Device Explorer, the message "Connection to the server has been lost" is output and can not receive the message.

https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-samples/send-receive-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/SendReceive.java

* Run using the MQTT protocol.
* There was no problem with v.1.0.16.

Also, after this, IotHub can not be opened for a while.

# Code sample exhibiting the issue:

https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-samples/send-receive-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/SendReceive.java

# Console log of the issue:

* 1st TESTLOG
Successfully read input parameters.
Using communication protocol MQTT.
[main] INFO  c.m.a.s.i.d.IotHubConnectionString - IotHubConnectionString object is created successfully for XXXXX.azure-devices.net, method name is <init> 
[main] INFO  c.m.a.s.i.d.DeviceClientConfig - DeviceClientConfig object is created successfully with IotHubName=XXXXX.azure-devices.net, deviceID=myFirstJavaDevice , method name is <init> 
[main] INFO  c.m.a.sdk.iot.device.DeviceIO - DeviceIO object is created successfully, method name is <init> 
[main] INFO  c.m.a.s.iot.device.DeviceClient - DeviceClient object is created successfully, method name is commonConstructorSetup 
Successfully created an IoT Hub client.
Successfully set message callback.
[main] INFO  c.m.a.s.iot.device.DeviceClient - Setting SASTokenExpiryTime as 2400 seconds, method name is setOption_SetSASTokenExpiryTime 
[main] INFO  c.m.a.s.iot.device.DeviceClient - Connection opened with success, method name is open 
Opened connection to IoT Hub.
Beginning to receive messages...
Sending the following event messages: 
Updated token expiry time to 2400
[main] INFO  c.m.azure.sdk.iot.device.Message - Setting message property with name=temperatureAlert and value=false, method name is setProperty 
[main] INFO  c.m.azure.sdk.iot.device.Message - The message with messageid xxxx-xxxx-xxxx-xxxx-xxxx has expiry time as 2000 milliseconds and the message will expire on Sun Feb 11 11:06:54 JST 2018, method name is setExpiryTime 
{"deviceId":"myFirstJavaDevice","messageId":0,"temperature":24.953512822655508,"humidity":30.709331581865168}
[main] INFO  c.m.a.sdk.iot.device.DeviceIO - Message with messageid xxxx-xxxx-xxxx-xxxx-xxxx along with callback and callbackcontext is added to the queue, method name is sendEventAsync 
[main] INFO  c.m.a.s.iot.device.DeviceClient - Message with messageid xxxx-xxxx-xxxx-xxxx-xxxx along with callback and callbackcontext is added to the queue, method name is sendEventAsync 
IoT Hub responded to message xxxx-xxxx-xxxx-xxxx-xxxx with status OK_EMPTY
Wait for 2 second(s) for response from the IoT Hub...
In receive mode. Waiting for receiving C2D messages. Press ENTER to close
Lost connection to the server. Reconnecting 0 time.
Lost connection to the server. Reconnecting 0 time.
Lost connection to the server. Reconnecting 0 time.
Lost connection to the server. Reconnecting 0 time.
Lost connection to the server. Reconnecting 0 time.
Lost connection to the server. Reconnecting 0 time.
: (Press ENTER Key)
Closing
[main] INFO  c.m.a.s.iot.device.DeviceClient - Connection closed with success, method name is closeNow 
Shutting down...

* 2nd TESTLOG
Successfully created an IoT Hub client.
Successfully set message callback.
INFO  c.m.a.s.iot.device.DeviceClient - Setting SASTokenExpiryTime as 2400 seconds, method name is setOption_SetSASTokenExpiryTime 
Lost connection to the server. Reconnecting 0 time.
[main] ERROR SendReceive - java.io.IOException: Unable to subscribe to topic :devices/myFirstJavaDevice/messages/devicebound/# because null ...
java.io.IOException: java.io.IOException: Unable to subscribe to topic :devices/myFirstJavaDevice/messages/devicebound/# because null ...
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:182)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttTransport.open(MqttTransport.java:83)
	at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:176)
	at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:365)
	at SendReceive.main(SendReceive.java:251)
Caused by: java.io.IOException: Unable to subscribe to topic :devices/myFirstJavaDevice/messages/devicebound/# because ...
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.subscribe(Mqtt.java:286)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttMessaging.start(MqttMessaging.java:39)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:162)
	... 5 common frames omitted
Caused by: org.eclipse.paho.client.mqttv3.MqttException: ...
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java:143)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.subscribe(MqttAsyncClient.java:721)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.subscribe(MqttAsyncClient.java:681)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.subscribe(Mqtt.java:277)
	... 7 common frames omitted

**Comment by kaki-mon** [comment]
Sorry, I was able to solve it.

I reviewed the dependency jar library.
I received it correctly as a result of doing the following.
* "org.eclipse.paho.client.mqttv3" change v1.0.2 to v1.2.0.
* "commons-lang3" added.

I have not found "commons-lang 3" from Marven (pom) dependency.
