### ISSUE TITLE
Exception thrown after upgrade to SDK 1.8

### ISSUE THREAD

**Issue by milunko** [Azure/azure-iot-sdk-java#209]
Hi, recently we upgraded to version 1.8 and there are some exceptions happening after the upgrade that weren't there before.

- **OS and version used:** Linux Debian based distribution 

- **Java runtime used:** Java embedded runtime 1.8

- **SDK version used:** 1.8 

We are connectiong to the IOT hub via amqps protocol. and we are using a connection string based authentication.

# Description of the issue:
Exceptions appearing after update to 1.8 that were not present prior to upgrade
`2018-02-22 07:21:51,597 ERROR c.m.a.s.i.d.t.IotHubReceiveTask [pool-14-thread-1] java.lang.IllegalStateException: No handler found for received message!: No handler found for received message!
2018-02-22 07:21:51,606 ERROR c.m.a.s.i.d.t.IotHubReceiveTask [pool-14-thread-2] java.lang.IllegalStateException: No handler found for received message!: No handler found for received message!
2018-02-22 08:07:45,661 ERROR c.m.a.s.i.d.t.a.AmqpsDeviceAuthenticationCBSTokenRenewalTask [pool-12-thread-1] java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@c1b190 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@65c38[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 1]: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@c1b190 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@65c38[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 1]
2018-02-22 08:51:32,686 ERROR c.m.a.s.i.d.t.IotHubReceiveTask [pool-14-thread-1] java.lang.IllegalStateException: No handler found for received message!: No handler found for received message!
2018-02-22 08:51:36,437 ERROR c.m.a.s.i.d.t.IotHubReceiveTask [pool-14-thread-2] java.lang.IllegalStateException: No handler found for received message!: No handler found for received message!
2018-02-22 09:37:27,002 ERROR c.m.a.s.i.d.t.a.AmqpsDeviceAuthenticationCBSTokenRenewalTask [pool-12-thread-1] java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@16b190d rejected from java.util.concurrent.ScheduledThreadPoolExecutor@1ace510[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 1]: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@16b190d rejected from java.util.concurrent.ScheduledThreadPoolExecutor@1ace510[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 1]`

IllegalState exception is happening right after the boot of the device if there are any messages on the iot hub side as far as we have noticed. But anyway here is the trace:
`2018-02-22 10:38:47,115 DEBUG c.m.a.s.i.d.t.IotHubReceiveTask [pool-14-thread-2] Exception on receiving queued messages to IoT Hub
java.lang.IllegalStateException: No handler found for received message!
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsTransport.handleMessage(AmqpsTransport.java:421) ~[zuehlke-iot-platform-all.jar:?]
	at com.microsoft.azure.sdk.iot.device.transport.IotHubReceiveTask.run(IotHubReceiveTask.java:41) ~[zuehlke-iot-platform-all.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]`

CBS Token error stacktrace:
`2018-02-22 09:37:27,010 DEBUG c.m.a.s.i.d.t.a.AmqpsDeviceAuthenticationCBSTokenRenewalTask [pool-12-thread-1] Exception on housekeeping
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@16b190d rejected from java.util.concurrent.ScheduledThreadPoolExecutor@1ace510[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 1]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047) ~[?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823) ~[?:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326) ~[?:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(ScheduledThreadPoolExecutor.java:573) ~[?:1.8.0_111]
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionDeviceOperation.scheduleRenewalThread(AmqpsSessionDeviceOperation.java:504) ~[zuehlke-iot-platform-all.jar:?]
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionDeviceOperation.renewToken(AmqpsSessionDeviceOperation.java:152) ~[zuehlke-iot-platform-all.jar:?]
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsDeviceAuthenticationCBSTokenRenewalTask.run(AmqpsDeviceAuthenticationCBSTokenRenewalTask.java:38) ~[zuehlke-iot-platform-all.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]`

**Comment by timtay-microsoft** [comment]
We are actively looking into this right now. From our preliminary research, you shouldn't worry much about these exceptions. We are working to stop them, but they are not causing any problems in our SDK right now.

**Comment by rkanubaddhi** [comment]
when can we expect a fix for this?

**Comment by timtay-microsoft** [comment]
We are hoping to get this fix released within a month and change. I'll keep you posted

**Comment by timtay-microsoft** [comment]
Just a quick update. We are shooting to release the fix to this issue 4/6. I'll update this thread as soon as we complete the release

**Comment by timtay-microsoft** [comment]
The fix for this issue has been released as of Device Client 1.10.0, so I'm closing this issue for now. Feel free to re-open if you still see any issues.

@rkanubaddhi  @milunko, thank you for your contribution to our open-sourced project! Please help us improve by filling out this [2-minute customer satisfaction survey](https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.surveymonkey.com%2Fr%2FQ5PLZ3V&data=02%7C01%7Ctimtay%40microsoft.com%7Cbfd772231c9c48abe82a08d5a0a66479%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636591558866731119&sdata=Eke9uU0qRn3tR%2BTFcP9yqLcv5dlcDfG%2F1owna8PhIno%3D&reserved=0)
