### ISSUE TITLE
Twin metada is inconsistent

### ISSUE THREAD

**Issue by karlchen7** [Azure/azure-iot-sdk-java#237]
- **OS and version used:** <VERSION> Windows 10

- **Java runtime used:** <VERSION> Java

- **SDK version used:** <VERSION> 1.13.2

_After the issue [#221] was fixed with version 1.13.2 a new issue appears.

Steps to the bug:
1. Create one desired property
2. delete this desired property
3. close the device twin (stop programm)
4. start programm
5. get deviceTwin --> Error_ 

`java.lang.IllegalArgumentException: Twin metadata is inconsistent
	at com.microsoft.azure.sdk.iot.deps.twin.TwinCollection.addMetadata(TwinCollection.java:345) ~[iot-deps-0.5.2.jar:na]
	at com.microsoft.azure.sdk.iot.deps.twin.TwinCollection.addMetadata(TwinCollection.java:354) ~[iot-deps-0.5.2.jar:na]
	at com.microsoft.azure.sdk.iot.deps.twin.TwinCollection.addMetadata(TwinCollection.java:354) ~[iot-deps-0.5.2.jar:na]
	at com.microsoft.azure.sdk.iot.deps.twin.TwinCollection.createFromRawCollection(TwinCollection.java:317) ~[iot-deps-0.5.2.jar:na]
	at com.microsoft.azure.sdk.iot.deps.twin.TwinProperties.<init>(TwinProperties.java:134) ~[iot-deps-0.5.2.jar:na]
	at com.microsoft.azure.sdk.iot.deps.twin.TwinState.createFromTwinJson(TwinState.java:289) ~[iot-deps-0.5.2.jar:na]
	at com.microsoft.azure.sdk.iot.service.devicetwin.DeviceTwin.jsonToDeviceTwinDevice(DeviceTwin.java:595) ~[iot-service-client-1.13.2.jar:na]
	at com.microsoft.azure.sdk.iot.service.devicetwin.DeviceTwin.getNextDeviceTwin(DeviceTwin.java:458) ~[iot-service-client-1.13.2.jar:na]`

_The problem is that the desired property was deleted, but in properties -> $metadata -> (same path) the property existis with $lastUpdated and $lastUpdatedVersion!_

**Comment by karlchen7** [comment]
No this wasn't the problem.

I don't know if this is an issue or not, but I found the problem for the error 

> Twin metada is inconsistent

first i filled the twinproperties
e.g.:
```
"properties": {
    "desired": {
      "test": {
        "hello": {
          "key": "value"
        },
        "hello2": {
          "key": "value"
        }
     }
   }
}
```
than i pushed a empty Object hello into the desired properties

```
"properties": {
    "desired": {
      "test": {
        "hello": {
        },
        "hello2": {
          "key": "value2"
        }
     }
   }
}
```

Now the twin properties throw the error, when I try to get the twin device again.


I solved it for myselfe. I just filtered the empty object out.

**Comment by timtay-microsoft** [comment]
Can you please provide a full code sample that demonstrates this issue? I still cannot repro this issue.

**Comment by timtay-microsoft** [comment]
Closing this issue because I can't repro the issue.
