### ISSUE TITLE
RSA And EC Certificates problem

### ISSUE THREAD

**Issue by taroyutao** [Azure/azure-iot-sdk-java#256]
I use the link:https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md to creat CA certificates.

**The Authentication type:**  X.509 CA Signed.

When I use the **powershell method** to generate the CA, use them directly in my java code:

import com.microsoft.azure.sdk.iot.device.*;

import java.io.IOException;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.List;

public class SendEventX509 {

    //PEM encoded representation of the public key certificate
    private static String publicKeyCertificateString =
            "-----BEGIN CERTIFICATE-----\n" +
                    "MIIDMjCCAhqgAwIBAgIQGvAB111lREiSLLAzOc9DyjANBgkqhkiG9w0BAQsFADAW\n" +
                    "MRQwEgYDVQQDEwtteWRvbWFpbi5jbjAeFw0xODA1MjkwNjMxNTlaFw0xOTA1Mjkw\n" +
                    "NjQxNTlaMBYxFDASBgNVBAMTC215ZG9tYWluLmNuMIIBIjANBgkqhkiG9w0BAQEF\n" +
                    "AAOCAQ8AMIIBCgKCAQEAsA7mxkVcLuqF5+U509wWCypf+aa3Do2GS9rr5Fu7PBSi\n" +
                    "j3S50WiQHz7Bwya8dK/dEbfGZJe5VTQ4ajwnyCJzqZmALk/7CJ/I64pO2T9G1adP\n" +
                    "jrgCIe4NjzST2EbbLxcSBKNuE8loq8EImjVNzGdrzlosp2pam/j66Kmeu+KK5e/m\n" +
                    "VDK8Mv7JmHYlpCOqJ45QTFrbHC2j29k7rBL4Esm+WWMgy8dYZQ34wHppof8MGgjP\n" +
                    "bPjSXj06QBBae5GJM8Bj3TK+9Jyw/r6P58P87cUn8yWBqokkJcywlXQYZeH8AVof\n" +
                    "2q/Sjw913H/Ef1CL+0NyMVFGCCUrtQBMazPmCYNp2wIDAQABo3wwejAOBgNVHQ8B\n" +
                    "Af8EBAMCBaAwCQYDVR0TBAIwADAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH\n" +
                    "AwIwHwYDVR0jBBgwFoAUWzVwusC5tzjV9V0sU6JX27fwsdAwHQYDVR0OBBYEFFs1\n" +
                    "cLrAubc41fVdLFOiV9u38LHQMA0GCSqGSIb3DQEBCwUAA4IBAQA34ILkfxI5hPVY\n" +
                    "MH635hfvCKBhhLSQthLCcRr4eGINaFamkQxR9D083tIhO5J66qvMy+DlccQG64ww\n" +
                    "3bOciVdNjaId0niFnxG+AJiQ5o0UlAeEJty2VozARljdqVVTvVIfakMH7iW3o9GR\n" +
                    "ZAFsjeRCA4z2FeyTXxVY/SZCWni9WcBl6xrlYdmKsXvHJjrMqR+MZROZijPh3Aig\n" +
                    "7VI4916MgsuW7ft/khMFmU0m764sBDfQKWCUgmZE457BpotWnU8s/0v899se+jfM\n" +
                    "0KQ4o9qdF+fWdaQFV+6gtBTn7DSMVpALzgAF9U0x8v5U9ZJX3b0CFfvYRP7Wq5Jv\n" +
                    "fBKvC+7W\n" +
                    "-----END CERTIFICATE-----\n";

    //PEM encoded representation of the private key
    private static String privateKeyString =
            "-----BEGIN PRIVATE KEY-----\n" +
                    "MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCwDubGRVwu6oXn\n" +
                    "5TnT3BYLKl/5prcOjYZL2uvkW7s8FKKPdLnRaJAfPsHDJrx0r90Rt8Zkl7lVNDhq\n" +
                    "PCfIInOpmYAuT/sIn8jrik7ZP0bVp0+OuAIh7g2PNJPYRtsvFxIEo24TyWirwQia\n" +
                    "NU3MZ2vOWiynalqb+ProqZ674orl7+ZUMrwy/smYdiWkI6onjlBMWtscLaPb2Tus\n" +
                    "EvgSyb5ZYyDLx1hlDfjAemmh/wwaCM9s+NJePTpAEFp7kYkzwGPdMr70nLD+vo/n\n" +
                    "w/ztxSfzJYGqiSQlzLCVdBhl4fwBWh/ar9KPD3Xcf8R/UIv7Q3IxUUYIJSu1AExr\n" +
                    "M+YJg2nbAgMBAAECggEAFEVISYXM4lNQTZiKkEZj0gSeqPDgB3CWCNUmRH78pM3q\n" +
                    "FZhRQ2Ia+JingzT04n5+dpQb5z3CMfmMO/cRzCzjTPYGgyPkTw7j+Z1NYh1d+4At\n" +
                    "scylOjYyy3fjRIs2oJ+zDGOrazh3sRF4UGuuDx3NP3oJxXuCU+Or3UPs/yGgmm6p\n" +
                    "I/7zH2ByEevhVqN33MLDGlog88pQ7SBlnyTnFym6vVRbnmnFMNHZPJdoE3EZjDAs\n" +
                    "tZeQ3rLmOI2kjJLr0jR+tt78KFBGeu1rcZn4f59h9lw4zokpYR3QRqTog+BW+43o\n" +
                    "dXC0gvTsk58JfPHOvbmP/CeIzEC3tZOs0shMaIvbsQKBgQC9lf5uUe7IVh7C/f4f\n" +
                    "RBrOd/+d7N4JmcY39Lz8A1Vol+WCYAzFfohStWkRX/Un8OKhxGchob8bc1hLJd+V\n" +
                    "IEBS484dmmNvk0NktWPVLF5M11yOVcckT3z1M7HRnD5NfhcwcmFU9pnqWwZj3RWm\n" +
                    "Uy5xLOcJkqH7AoDbLGuTsrhPKQKBgQDtu79JbHWoLXpjke7QIA6f+agbUT1qh9+O\n" +
                    "YQrXFttIi4VvX0aaXfFjAvuQUkiZfU7nvkumXkwUwNloC73Qe5Oq2oHfykfFmllD\n" +
                    "aJCwlabQFXmV0IYQof1mqZwJIJ8G9qChDwos0OvOjJTPKAnZg+2ucBS1W80VgCj7\n" +
                    "wK8VwEkFYwKBgGVEvM6zB0iN8AqaX+bVmzgUkz8JaqVYNbBoE5bONQ4UrSzSH6BS\n" +
                    "8YC0lHYKesql+nkMj0ZAvvNrzor9pQtkWdetBcl8UYck84fU+InDFG/LasQQ/7ne\n" +
                    "l9HmliJwQjtkkgB36JPY0eiETMqFKu5YWmNr59GOOOX6tVfdx2zyt07ZAoGAVeM3\n" +
                    "h5JMq5bKmcB2U/DQ99DdgAkItD0kci7zGKQkUwA9E/CK9GguNkQ0mH5xxio0YJsq\n" +
                    "f4+f0vudT+62A+Uxg09wDmbpKSXLTAQyCen3G0Q26f4tAUNU5ksumUmUypI9lBJ3\n" +
                    "7ZsJJlU5yeHANTppm1TY1nC1Fih4JgQF/Ui72NsCgYBCH0+mX3r4NP9vJ0A2M5VQ\n" +
                    "PUlZpV6K1f4qN92rlDt1BORCPlRV5iCRKrBo4z7uZ90DP4a2zW/J94vtTkdAcuhz\n" +
                    "eWeBiIXREe4RZ8IDN02G+5k7QXRV8vC0GzzxE95ly9dzX/ru/05Bovh+FVLHO3H0\n" +
                    "edPKIr8jQRmkL8nt/ry/6A==\n" +
                    "-----END PRIVATE KEY-----\n";

    private  static final int D2C_MESSAGE_TIMEOUT = 2000; // 2 seconds
    private  static List failedMessageListOnClose = new ArrayList(); // List of messages that failed on close

    protected static class EventCallback implements IotHubEventCallback
    {
        public void execute(IotHubStatusCode status, Object context)
        {
            Message msg = (Message) context;

            System.out.println("IoT Hub responded to message "+ msg.getMessageId()  + " with status " + status.name());

            if (status== IotHubStatusCode.MESSAGE_CANCELLED_ONCLOSE)
            {
                failedMessageListOnClose.add(msg.getMessageId());
            }
        }
    }

    /**
     * Sends a number of messages to an IoT Hub. Default protocol is to
     * use MQTT transport.
     *
     * @param args
     * args[0] = IoT Hub connection string
     * args[1] = number of requests to send
     * args[2] = IoT Hub protocol to use, optional and defaults to MQTT
     */
    public static void main(String[] args) throws IOException, URISyntaxException
    {
        System.out.println("Starting...");
        System.out.println("Beginning setup.");
        args = new String[3];
        args[0] = "HostName=chenzheng.azure-devices.cn;DeviceId=mydevicecer;x509=true";
        args[1] = "20";
        args[2] = "mqtt";

        if (!(args.length == 2 || args.length == 3))
        {
            System.out.format(
                    "Expected 2 or 3 arguments but received: %d.\n"
                            + "The program should be called with the following args: \n"
                            + "1. [Device connection string] - String containing Hostname, Device Id & Device Key in one of the following formats: HostName=<host_name>;DeviceId=<device_id>;x509=true\n"
                            + "2. [number of requests to send]\n"
                            + "3. (mqtt | https | amqps | amqps_ws | mqtt_ws)\n",
                    args.length);
            return;
        }

        String connectionString = args[0];

        int numRequests;
        try
        {
            numRequests = Integer.parseInt(args[1]);
        }
        catch (NumberFormatException e)
        {
            System.out.format(
                    "Could not parse the number of requests to send. "
                            + "Expected an int but received:\n%s.\n", args[1]);
            return;
        }

        IotHubClientProtocol protocol;
        if (args.length == 2)
        {
            protocol = IotHubClientProtocol.MQTT;
        }
        else
        {
            String protocolStr = args[2].toLowerCase();
            if (protocolStr.equals("amqps"))
            {
                protocol = IotHubClientProtocol.AMQPS;
            }
            else if (protocolStr.equals("mqtt"))
            {
                protocol = IotHubClientProtocol.MQTT;
            }
            else
            {
                throw new UnsupportedOperationException("The protocol " + protocolStr + " does not support x509 authentication");
            }
        }

        System.out.println("Successfully read input parameters.");
        System.out.format("Using communication protocol %s.\n", protocol.name());

        DeviceClient client = new DeviceClient(connectionString, protocol, publicKeyCertificateString, false, privateKeyString, false);

        System.out.println("Successfully created an IoT Hub client.");

        client.open();

        System.out.println("Opened connection to IoT Hub.");
        System.out.println("Sending the following event messages:");

        String deviceId = "mydevicecer";
        double temperature = 0.0;
        double humidity = 0.0;

        for (int i = 0; i < numRequests; ++i)
        {
            temperature = 20 + Math.random() * 10;
            humidity = 30 + Math.random() * 20;

            String msgStr = "{\"deviceId\":\"" + deviceId +"\",\"messageId\":" + i + ",\"temperature\":"+ temperature +",\"humidity\":"+ humidity +"}";

            try
            {
                Message msg = new Message(msgStr);
                msg.setProperty("temperatureAlert", temperature > 28 ? "true" : "false");
                msg.setMessageId(java.util.UUID.randomUUID().toString());
                msg.setExpiryTime(D2C_MESSAGE_TIMEOUT);
                System.out.println(msgStr);

                EventCallback callback = new EventCallback();
                client.sendEventAsync(msg, callback, msg);
            }
            catch (Exception e)
            {
                e.printStackTrace();
            }
        }

        System.out.println("Wait for " + D2C_MESSAGE_TIMEOUT / 1000 + " second(s) for response from the IoT Hub...");

        // Wait for IoT Hub to respond.
        try
        {
            Thread.sleep(D2C_MESSAGE_TIMEOUT);
        }
        catch (InterruptedException e)
        {
            e.printStackTrace();
        }

        // close the connection
        System.out.println("Closing");
        client.closeNow();

        if (!failedMessageListOnClose.isEmpty())
        {
            System.out.println("List of messages that were cancelled on close:" + failedMessageListOnClose.toString());
        }

        System.out.println("Shutting down...");
    }
}

**The Result:**
Everything works fine.

---

**But when I use the Bash script to generate the CA and use them abmost in the same way in my code, the error is:**

Exception in thread "main" java.io.IOException: Could not open the connection
	at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:164)
	at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:372)
	at iot.SendEventX5091.main(SendEventX5091.java:195)
Caused by: com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.MqttUnauthorizedException: Unable to establish MQTT connection
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:57)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connect(Mqtt.java:105)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttMessaging.start(MqttMessaging.java:40)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:181)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:642)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.open(IotHubTransport.java:276)
	at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:160)
	... 2 more
Caused by: Not authorized to connect (5)
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:28)
	at org.eclipse.paho.client.mqttv3.internal.ClientState.notifyReceivedAck(ClientState.java:988)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:145)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

---

**I have also  changed the "-----END/BEGIN PRIVATE KEY-----" to "-----END/BEGIN RSA PRIVATE KEY-----"

---

the error is:**
com.microsoft.azure.sdk.iot.provisioning.security.exceptions.SecurityProviderException: java.security.cert.CertificateException: org.bouncycastle.openssl.PEMException: malformed sequence in RSA private key
	at iot.SecurityProviderX509Cert.<init>(SecurityProviderX509Cert.java:69)
	at iot.GetGenerateTestCertificate1.main(GetGenerateTestCertificate1.java:85)
Caused by: java.security.cert.CertificateException: org.bouncycastle.openssl.PEMException: malformed sequence in RSA private key
	at iot.SecurityProviderX509Cert.parsePrivateKey(SecurityProviderX509Cert.java:181)
	at iot.SecurityProviderX509Cert.<init>(SecurityProviderX509Cert.java:60)
	... 1 more
Caused by: org.bouncycastle.openssl.PEMException: malformed sequence in RSA private key
	at org.bouncycastle.openssl.PEMParser$KeyPairParser.parseObject(Unknown Source)
	at org.bouncycastle.openssl.PEMParser.readObject(Unknown Source)
	at iot.SecurityProviderX509Cert.parsePrivateKey(SecurityProviderX509Cert.java:175)
	... 2 more
Caused by: org.bouncycastle.openssl.PEMException: malformed sequence in RSA private key
	at org.bouncycastle.openssl.PEMParser$RSAKeyPairParser.parse(Unknown Source)
	... 5 more

**issues:**

I find the main difference between the Powershell script and the Bash script is the encryption algorithm.

The encryption algorithm of Powershell script is Ecc, but the encryption algorithm of  Bash script is RSA.

I have test several times, the CA certificates created by Powershell script works find, but the CA certificates created by the Bash script always work wrong.

I don't know why. 

Anyone can give some advices about this issue?

Thanks in advance.

**Comment by timtay-microsoft** [comment]
I'm a little confused, are you altering the headers of the bash generated certs? Why? And do they work when you don't change the header?

From the readme you linked about those ps1 and bash scripts:
```
The PS1 and Bash scripts are functionally equivalent; they are both provided depending on your preference for Windows or Linux.
```

The certificates generated by these two scripts shouldn't have different encryption types.

**Comment by timtay-microsoft** [comment]
And are you sure that you have uploaded each certificate to your IotHub instance before trying to connect a device with it?

**Comment by taroyutao** [comment]
Yes， I'm sure, I have upload certificates to my Iot hub.

 I follow the [document](https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md) step by step.

When I use the powershell script in windows, everything works fine, and I can connect to my Iot hub in my device by cercertificate's info.

But when I followed the Bash script to create certificate  step by step in linux, There is no problem in the generation of certificates. But when I used the information in certificates, it doesn't work.

From the readme:
The PS1 and Bash scripts are functionally equivalent.

Certificates generated in these two ways should all work properly. But the Bash script doesn't work.

**Comment by taroyutao** [comment]
**The certificates generated by these two scripts shouldn't have different encryption types.**

The algorithm of Powershell script is ECC:
![ecc](https://user-images.githubusercontent.com/20704268/40960166-79ee5cc6-68d1-11e8-8861-2245c7690fd6.png)

The algorithm of Bash script is RSA:
![rsa](https://user-images.githubusercontent.com/20704268/40960172-7e4a2a8e-68d1-11e8-9c80-93859b146cf0.png)

**Comment by timtay-microsoft** [comment]
I would still avoid changing headers/footers on the certs. The certs are generated with the correct headers.

So you are getting the below stacktrace when using the bash generated certs without changing the headers?

```
Exception in thread "main" java.io.IOException: Could not open the connection
at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:164)
at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:372)
at iot.SendEventX5091.main(SendEventX5091.java:195)
Caused by: com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.MqttUnauthorizedException: Unable to establish MQTT connection
at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:57)
at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connect(Mqtt.java:105)
at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttMessaging.start(MqttMessaging.java:40)
at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:181)
at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:642)
at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.open(IotHubTransport.java:276)
at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:160)
... 2 more
Caused by: Not authorized to connect (5)
at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:28)
at org.eclipse.paho.client.mqttv3.internal.ClientState.notifyReceivedAck(ClientState.java:988)
at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:145)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
```

If so, that would suggest that the service does not have the correct certificate uploaded, or that you are using a private key locally that doesn't match with the certificate you uploaded. That exception means this SDK attempted to open a connection with the service using the cert you provided in the Device Client constructor, but that the service rejected the connection because you are unauthorized.

Are you positive that the certs generated by the base script are legitimate? Have you tried using them in one of the other SDKs we offer (C, C#, Python, Node)? It may be an issue with the bash script rather than the Java SDK.

**Comment by taroyutao** [comment]
Thanks for your help, I hava test in C# SDK, the same result. I also think it may be an issue with the bash script rather than the Java SDK. I create a new[ issue](https://github.com/Azure/azure-iot-sdk-c/issues/511) in C SDK.

**Comment by timtay-microsoft** [comment]
Since this is an issue with the bash script itself, and not the Java SDK, I'm going to close this issue for now. Feel free to re-open if you find something specific to the Java SDK that isn't working for you.

@taroyutao thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).
