### ISSUE TITLE
Open Threads after 'Could not open the connection' azure response

### ISSUE THREAD

**Issue by FranAlterados** [Azure/azure-iot-sdk-java#261]
- **OS and version used:** Android 7.0

- **Java runtime used:** 1.8

- **SDK version used:** 
iot-device-client:1.11.0
iot-service-client:1.13.2
iot-deps:0.5.2
azure-storage-android:2.0.0
org.apache.commons:commons-lang3:3.6

# Description of the issue:
When I try to open a connection to send a message sometimes (aparently randomly) Azure responds me 'Could not open the connection'. After that, 3 threads are created, they stay sleeping and they are never destroyed. This behavior, repeats itslef, increasing the number of threads rendenring our software unstable.

Threads name are:
MQTT Con: [DeviceId..]
MQTT Rec: [DeviceId..]
MQTT Snd: [DeviceId..]
MQTT Call: [DeviceId..]

**Comment by timtay-microsoft** [comment]
Duplicate issue of #247 

Closing this issue because it already exists

**Comment by FranAlterados** [comment]
It's a diferent problem than #247 

When we send many messages, one after another, sometimes azure gets me this error

Example Code:

```Java
public class MainActivity extends AppCompatActivity {

    private final String connString = "[device connection string]";
    private final String deviceId = "MyAndroidDevice";
    DeviceClient client;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        try {
            IotHubClientProtocol protocol = IotHubClientProtocol.MQTT;
            client = new DeviceClient(connString, protocol);
            sendManyMessages(0,1000);
        } catch (Exception e) {
            System.err.println("Exception while opening IoTHub connection: " + e.toString());
        }
    }

    public void sendManyMessages(Integer index, Integer numberOfMessages) {
        if (index < numberOfMessages) {
            try {
                client.open();
                Message msg = new Message("{json]");
                msg.setExpiryTime(3_000);
                client.sendEventAsync(msg, new IotHubEventCallback() {
                    @Override
                    public void execute(IotHubStatusCode responseStatus, Object callbackContext) {
                        try {
                            client.closeNow();
                        } catch (IOException e) {
                            e.printStackTrace();
                        }
                        sendManyMessages(index + 1,numberOfMessages);
                    }
                }, null);
            } catch (IOException e) {
                e.printStackTrace();
                sendManyMessages(index + 1,numberOfMessages);
            }
        }
    }
}

```

Error displayed:
```
06-11 11:51:23.845 12735-27844/com.helloauto.azureerror I/System.out: [socket][897] connection iot-hub-brjbetvtk3czs.azure-devices.net/51.144.118.31:8883;LocalPort=-1(30000)
06-11 11:51:23.922 12735-27844/com.helloauto.azureerror I/System.out: [socket][/192.168.1.46:60567] connected
06-11 11:51:23.923 12735-27844/com.helloauto.azureerror D/NativeCrypto: ssl=0x95283000 NativeCrypto_SSL_do_handshake fd=0x9467a1d0 shc=0x9467a1d4 timeout_millis=30000 client_mode=1 npn=0x0
    ssl=0x95283000 info_callback calling handshakeCompleted
06-11 11:51:23.998 12735-27844/com.helloauto.azureerror D/NativeCrypto: ssl=0x95283000 cert_verify_callback => 1
06-11 11:51:24.064 12735-27844/com.helloauto.azureerror D/NativeCrypto: ssl=0x95283000 info_callback calling handshakeCompleted
06-11 11:51:24.065 12735-27844/com.helloauto.azureerror D/NativeCrypto: ssl=0x95283000 NativeCrypto_SSL_get_certificate => NULL
06-11 11:51:24.065 12735-27844/com.helloauto.azureerror I/System.out: gba_cipher_suite:TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
06-11 11:51:25.123 12735-27840/com.helloauto.azureerror W/System.err: java.io.IOException: Could not open the connection
06-11 11:51:25.132 12735-27840/com.helloauto.azureerror W/System.err:     at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:164)
        at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:372)
        at com.helloauto.azureerror.MainActivity.sendManyMessages(MainActivity.java:37)
        at com.helloauto.azureerror.MainActivity$1.execute(MainActivity.java:48)
        at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.invokeCallbacks(IotHubTransport.java:384)
        at com.microsoft.azure.sdk.iot.device.transport.IotHubSendTask.run(IotHubSendTask.java:48)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:278)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:273)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
06-11 11:51:25.133 12735-27840/com.helloauto.azureerror W/System.err: Caused by: com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Unable to subscribe to topic :devices/DeviceId/messages/devicebound/#
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:69)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.subscribe(Mqtt.java:270)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttMessaging.start(MqttMessaging.java:41)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:177)
        at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:630)
        at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.open(IotHubTransport.java:264)
        at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:160)
    	... 11 more
06-11 11:51:25.134 12735-27840/com.helloauto.azureerror W/System.err: Caused by: Tiempo de espera excedido al esperar una respuesta del servidor (32000)
        at org.eclipse.paho.client.mqttv3.internal.Token.waitForCompletion(Token.java:112)
        at org.eclipse.paho.client.mqttv3.MqttToken.waitForCompletion(MqttToken.java:67)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.subscribe(Mqtt.java:265)
    	... 16 more
```

Other times I get a different Error, but this error only leak 1 thread, not 4

````
06-11 11:23:26.361 26005-32381/com.helloauto.azureerror I/System.out: [socket][347] connection iot-hub-brjbetvtk3czs.azure-devices.net/51.144.118.31:8883;LocalPort=-1(30000)
06-11 11:23:26.408 26005-32381/com.helloauto.azureerror I/System.out: [socket][/192.168.1.46:59012] connected
06-11 11:23:26.409 26005-32381/com.helloauto.azureerror D/NativeCrypto: ssl=0x94987140 NativeCrypto_SSL_do_handshake fd=0x9647e1d0 shc=0x9647e1d4 timeout_millis=30000 client_mode=1 npn=0x0
    ssl=0x94987140 info_callback calling handshakeCompleted
06-11 11:23:29.152 26005-32381/com.helloauto.azureerror D/NativeCrypto: ssl=0x94987140 cert_verify_callback => 1
06-11 11:23:29.247 26005-32381/com.helloauto.azureerror E/NativeCrypto: Unknown error 5 during handshake
06-11 11:23:29.248 26005-32381/com.helloauto.azureerror D/NativeCrypto: ssl=0x94987140 NativeCrypto_SSL_do_handshake clean error => 0
06-11 11:23:29.249 26005-32381/com.helloauto.azureerror I/System.out: close [socket][/192.168.1.46:59012]
06-11 11:23:29.251 26005-32377/com.helloauto.azureerror W/System.err: java.io.IOException: Could not open the connection
        at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:164)
06-11 11:23:29.252 26005-32377/com.helloauto.azureerror W/System.err:     at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:372)
        at com.helloauto.azureerror.MainActivity.sendManyMessages(MainActivity.java:37)
        at com.helloauto.azureerror.MainActivity$1.execute(MainActivity.java:48)
        at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.invokeCallbacks(IotHubTransport.java:384)
        at com.microsoft.azure.sdk.iot.device.transport.IotHubSendTask.run(IotHubSendTask.java:48)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:278)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:273)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
06-11 11:23:29.253 26005-32377/com.helloauto.azureerror W/System.err: Caused by: com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Unable to establish MQTT connection
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:41)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connect(Mqtt.java:109)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttMessaging.start(MqttMessaging.java:40)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:177)
        at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:630)
        at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.open(IotHubTransport.java:264)
        at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:160)
    	... 11 more
06-11 11:23:29.284 26005-32377/com.helloauto.azureerror W/System.err: Caused by: MqttException (0) - javax.net.ssl.SSLHandshakeException: Connection closed by peer
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:715)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
    	... 3 more
    Caused by: javax.net.ssl.SSLHandshakeException: Connection closed by peer
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:362)
        at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:108)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:701)
    	... 6 more
````

**Comment by timtay-microsoft** [comment]
The problem here is that the underlying MQTT library does not close it's threads properly if the connection was not established. Whether it is one thread left alive or four is not really an important distinction. We have the issue already opened with Paho and they are taking a look into it.
