### ISSUE TITLE
[Device Client - MQTT]  Issue while connecting to IOT HUB

### ISSUE THREAD

**Issue by hidips** [Azure/azure-iot-sdk-java#264]
I'm trying to connect to IOT Hub from Java to generate Telemetry.
Following 
https://docs.microsoft.com/en-us/azure/iot-hub/quickstart-send-telemetry-java

 **OS and version used:** <VERSION> <!-- Windows 7

**Java runtime used:** <VERSION> <!-- JDK 1.8

 **SDK version used:** <VERSION> <!-- iot-device-client-1.11.2.jar

# Description of the issue:
 While connecting to the IOT Hub, its throwing connection error 

# Code sample exhibiting the issue:

try {
client = new DeviceClient(connString, protocol);
client.open();
  // Register to receive direct method calls.
	
    client.subscribeToDeviceMethod(new DirectMethodCallback(), null, new DirectMethodStatusCallback(), null);
    
    // Create new thread and start sending messages 
    MessageSender sender = new MessageSender();
    ExecutorService executor = Executors.newFixedThreadPool(1);
    executor.execute(sender);

    // Stop the application.
    System.out.println("Press ENTER to exit.");
    System.in.read();
    executor.shutdownNow();
    client.closeNow();
    
	  }catch(Exception e) {
		  e.printStackTrace();
	  }
    

# Console log of the issue:
 java.io.IOException: Could not open the connection
	at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:164)
	at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:372)
	at com.microsoft.docs.iothub.samples.SimulatedDevice.main(SimulatedDevice.java:171)
Caused by: com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Unable to establish MQTT connection
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:69)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connect(Mqtt.java:105)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttMessaging.start(MqttMessaging.java:40)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:181)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:642)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.open(IotHubTransport.java:276)
	at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:160)
	... 2 more
Caused by: Unable to connect to server (32103) - java.net.ConnectException: Connection timed out: connect
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:79)
	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:86)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:70)
	... 3 more

AB#7765809

**Comment by timtay-microsoft** [comment]
This error occurs when your device is trying to connect to your IotHub, but the connection attempt times out. It could be due to either bad network connectivity, or due to a load problem on your IotHub side.

How consistently do you get this error? Do you have a lot of other devices connecting to your hub at the same time?

**Comment by timtay-microsoft** [comment]
And what happens if you try using a different protocol? Such as AMQPS or HTTPS instead of MQTT?

**Comment by hidips** [comment]
HTTPS is working fine.
AMQPS is throwing similar error:
***********
java.io.IOException: Could not open the connection
	at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:164)
	at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:372)
	at com.microsoft.docs.iothub.samples.SimulatedDevice.main(SimulatedDevice.java:171)
Caused by: com.microsoft.azure.sdk.iot.device.exceptions.TransportException: Timed out waiting to connect to service
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.open(AmqpsIotHubConnection.java:229)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:642)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.open(IotHubTransport.java:276)
	at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:160)

***********

**Comment by timtay-microsoft** [comment]
What about AMQPS_WS and MQTT_WS?

And how consistently are you getting this error? If you are getting this randomly, it just means that your device has network connectivity problems. If you get it very frequently, there may be a bigger problem

**Comment by hidips** [comment]
AMQPS_WS  works! But MQTT_WS doesn't.
HTTPS and AMQPS_WS works consistently. Others don't work at all.

**Comment by timtay-microsoft** [comment]
What is the exception that you get for MQTT_WS? Please include the full stacktrace.

**Comment by timtay-microsoft** [comment]
And do you know if the device is using any sort of firewall? Or if it blocks any network ports?

**Comment by hidips** [comment]
Here is the stacktrace for MQTT_WS:
******
java.io.IOException: Could not open the connection
	at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:164)
	at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:372)
	at com.microsoft.docs.iothub.samples.SimulatedDevice.main(SimulatedDevice.java:171)
Caused by: com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Unable to establish MQTT connection
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:41)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connect(Mqtt.java:105)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttMessaging.start(MqttMessaging.java:40)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:181)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:642)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.open(IotHubTransport.java:276)
	at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:160)
	... 2 more
Caused by: MqttException (0) - java.io.IOException: WebSocket Response header: Incorrect connection header
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:690)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: WebSocket Response header: Incorrect connection header
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.receiveHandshakeResponse(WebSocketHandshake.java:144)
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.execute(WebSocketHandshake.java:74)
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.start(WebSocketSecureNetworkModule.java:77)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:676)
******

**Comment by timtay-microsoft** [comment]
There must be some kind of network configuration problem with your device because I can't repro any of this behavior. Have you tried running the same code sample on a different computer/device?

**Comment by timtay-microsoft** [comment]
And what happens when you try to use the service client? Are you able to communicate with the iothub to do things like creating a device, or sending desired properties?

**Comment by hidips** [comment]
You're right!
I tried from a different network and found everything is working except MQTT. I was also able to read the messages from the hub. 
Now could you guide me on what could be wrong in network when I can write to the hub, but cannot read from it? Any particular port/IP that I need to put somewhere?
Thanks for all your support!

**Comment by timtay-microsoft** [comment]
I am seeing some references in the Paho repo's issues to the same exception. It may be that we need to downgrade our Paho version to 1.1.0. Could you try building this sdk from source while editing the two references to Paho such that they use 1.1.0 instead of 1.2.0 and see if it resolves your problem?

[For additional details](https://github.com/eclipse/paho.mqtt.java/issues/345)

As for why you are encountering problems with AMQPS, I can't be sure. We don't require any particular ports to be open, but your firewall may be restricting network connections in some other way.

**Comment by hidips** [comment]
Tried Paho 1.1.0. Same results.
What I find that as from this network, I can only use HTTPS to write to the hub, so I need HTTPS support for Event Hub end point to receive the message. However I don't see an option to use that in the receiving end point. I see in documentation that by default it uses AMQP on port 5671. Is there a way that I can use HTTPS end point to receive message?

**Comment by timtay-microsoft** [comment]
If you are using HTTPS to write messages to your IotHub, that is fine. If you are trying to use HTTPS to send messages to devices using the service client, that is not possible. Our SDK only supports using AMQPS to send Cloud to Device messages.

I'm a little confused about what you are asking for about the endpoint to receive messages. No part of this SDK is used to receive device to cloud messages. What exactly are you trying to use this SDK for?

**Comment by emilm** [comment]
Shouldn't it try to connect and just silently retry? Is there a way to configure it like this? This is typical when a device boots and you have wifi that is not connected yet but the service starts up before that.

**Comment by timtay-microsoft** [comment]
@emilm What are you expecting to silently retry? The open call?

**Comment by timtay-microsoft** [comment]
Currently, the open call has no retry built into it. We may include it when we go to v2 of this SDK, but for now, adding that would be a breaking change. If you want to have your open call retry, you'll have to manually catch any exceptions and call open until it succeeds.

Something like:
```java
public static void openClientWithRetry(InternalClient client)
{
    boolean clientOpenSucceeded = false;
    long startTime = System.currentTimeMillis();
    while (!clientOpenSucceeded)
    {
        if (System.currentTimeMillis() - startTime > OPEN_RETRY_TIMEOUT)
        {
            Assert.fail("Timed out trying to open the device client");
        }

        try
        {
            client.open();
            clientOpenSucceeded = true;
        }
        catch (IOException e)
        {
            //ignore and try again
            System.out.println("Encountered exception while opening device client, retrying...");
            e.printStackTrace();
        }
    }

    System.out.println("Successfully opened connection!");
}
```

**Comment by emilm** [comment]
Thanks! I did something similar. How is the startDeviceTwin() handled here? Does it need to be started again if I lose connection again and then regain it?

**Comment by timtay-microsoft** [comment]
You won't have to re-subscribe to twins, methods, or message callbacks. You only have to call open again.

**Comment by emilm** [comment]
One thing, you could have a new openAsync() or startOpen() which does this, and that shouldn't be a breaking change, right? Then you can apply the same retry policy in a retry thread as set in setRetryPolicy().

**Comment by timtay-microsoft** [comment]
We considered that, but we try to maintain a similar API face as the other language SDKs for Azure Iot. No other SDK exposes an API like that. Some languages have the retry built into their normal open call, and we will be doing the same later. But for now, it's simple enough for a user to write their own retryable open call.

**Comment by timtay-microsoft** [comment]
@hidips are you still running into issues here?

**Comment by timtay-microsoft** [comment]
I'm closing this issue due to a lack of activity. Feel free to re-open if you feel this issue deserves further discussion.

**Comment by timtay-microsoft** [comment]
@Pavan-kumar-R this thread is a little crowded right now. Would you be willing to open a new issue thread for the problems you see? We'll need you to include the full stack trace of any exception thrown by the SDK to help you debug

**Comment by timtay-microsoft** [comment]
I'm closing this issue due to a lack of activity. Feel free to re-open if you feel this issue deserves further discussion.

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, @hidips, @emilm, @Pavan-kumar-R, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
