### ISSUE TITLE
[moduleclient] Unsupported authentication scheme.

### ISSUE THREAD

**Issue by adashen** [Azure/azure-iot-sdk-java#267]
- **OS and version used:** Ubuntu 18.04

- **Java runtime used:** java8 

- **SDK version used:** 1.13.0 

# Description of the issue:
When module client tries open connection to edgeHub. Following error throws
Exception in thread "main" com.microsoft.azure.sdk.iot.device.exceptions.ModuleClientException: Unsupported authentication scheme. Supported scheme is SasToken.
        at com.microsoft.azure.sdk.iot.device.ModuleClient.createFromEnvironment(ModuleClient.java:215)
        at com.microsoft.App.main(App.java:19)

# Code sample exhibiting the issue:
        IotHubClientProtocol protocol = IotHubClientProtocol.MQTT;
        ModuleClient client = ModuleClient.createFromEnvironment(protocol);
        client.open();

# Console log of the issue:
Exception in thread "main" com.microsoft.azure.sdk.iot.device.exceptions.ModuleClientException: Unsupported authentication scheme. Supported scheme is SasToken.
        at com.microsoft.azure.sdk.iot.device.ModuleClient.createFromEnvironment(ModuleClient.java:215)
        at com.microsoft.App.main(App.java:19)

**Comment by timtay-microsoft** [comment]
We are working to fix a few other issues around the edgehub scenario, but we do have a fix coded up for this issue. We are waiting to check it in alongside these other fixes.

**Comment by timtay-microsoft** [comment]
The fix for this issue has been released as of Device Client 1.13.1, so I'm going to go ahead and close this issue.
