### ISSUE TITLE
[ModuleClient] AMQPS connectivity issues

### ISSUE THREAD

**Issue by akulofficial** [Azure/azure-iot-sdk-java#269]
OS used: Mac OS X 10.13.4
Java runtime: 1.8.0_172
Azure IoT Device Client SDK version 1.12.0

I have a custom module (essentially a web server running within a Docker container)  in an IoT Edge device that won't connect to the IoT Hub, regardless of which messaging protocol I use (particularly AMQPS). This problem has occurred pretty much every time I have attempted to use this service and I have yet to find any fixes for it. 

Below is the code sample that throws the error (it's the open function that seems to do it):
MOD_CLIENT = ModuleClient.createFromEnvironment();

            MOD_CLIENT.open();

            MOD_CLIENT.subscribeToMethod(new DirectMethodCallback(), null, new DirectMethodStatusCallback(), null);

            MOD_CLIENT.setMessageCallback(new IotHubMessageCallback(), new HashMap<>());

            MOD_CLIENT.sendEventAsync(new Message("Hello from LRAM."), new IotHubEventCallbackImpl(), null);

And here is a console log (or at least the relevant part) of the issue:
[Connection string object created successfully, redacted due to private info]
[DeviceClientConfig successfully created, redacted due to private info]
2018-07-02 15:01:33,999 [main] INFO  com.microsoft.azure.sdk.iot.device.DeviceIO  - DeviceIO object is created successfully, method name is <init> 
2018-07-02 15:01:34,009 [main] INFO  com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - AmqpsIotHubConnection object is created successfully using port 5671 in <init> method 
2018-07-02 15:01:34,029 [main] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Entered in method open
2018-07-02 15:01:34,029 [main] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Entered in method openAsync
2018-07-02 15:01:34,029 [azure-iot-sdk-AmqpsDeviceAuthenticationCBSTokenRenewalTask] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionDeviceOperation  - Entered in method renewToken
2018-07-02 15:01:34,030 [azure-iot-sdk-AmqpsDeviceAuthenticationCBSTokenRenewalTask] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionDeviceOperation  - Exited from method renewToken
2018-07-02 15:01:34,049 [main] INFO  com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Reactor is assigned to executor service, method name is openAsync 
2018-07-02 15:01:34,058 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Entered in method onReactorInit
2018-07-02 15:01:34,070 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Exited from method onReactorInit
2018-07-02 15:01:34,076 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Entered in method onConnectionInit
2018-07-02 15:01:34,076 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionManager  - Entered in method onConnectionInit
2018-07-02 15:01:34,079 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsDeviceAuthenticationCBS  - Entered in method openLinks
2018-07-02 15:01:34,085 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsDeviceAuthenticationCBS  - Exited from method openLinks
2018-07-02 15:01:34,086 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionManager  - Exited from method onConnectionInit
2018-07-02 15:01:34,086 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Exited from method onConnectionInit
2018-07-02 15:01:34,214 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Entered in method onLinkInit
2018-07-02 15:01:34,214 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionManager  - Entered in method onLinkInit
2018-07-02 15:01:34,214 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsDeviceAuthenticationCBS  - Entered in method initLink
2018-07-02 15:01:34,215 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsDeviceAuthenticationCBS  - Exited from method initLink
2018-07-02 15:01:34,216 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionManager  - Exited from method onLinkInit
2018-07-02 15:01:34,216 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Exited from method onLinkInit
2018-07-02 15:01:34,216 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Entered in method onLinkInit
2018-07-02 15:01:34,216 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionManager  - Entered in method onLinkInit
2018-07-02 15:01:34,216 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsDeviceAuthenticationCBS  - Entered in method initLink
2018-07-02 15:01:34,217 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsDeviceAuthenticationCBS  - Exited from method initLink
2018-07-02 15:01:34,217 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionManager  - Exited from method onLinkInit
2018-07-02 15:01:34,217 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Exited from method onLinkInit
2018-07-02 15:01:34,217 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Entered in method onConnectionBound
2018-07-02 15:01:34,217 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionManager  - Entered in method onConnectionBound
2018-07-02 15:01:34,433 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionManager  - Exited from method onConnectionBound
2018-07-02 15:01:34,433 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Exited from method onConnectionBound
2018-07-02 15:01:34,477 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Entered in method onTransportError
2018-07-02 15:01:34,491 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Exited from method onTransportError
2018-07-02 15:01:34,492 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Entered in method onConnectionUnbound
2018-07-02 15:01:34,492 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Exited from method onConnectionUnbound
2018-07-02 15:01:34,492 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Entered in method onReactorFinal
2018-07-02 15:01:34,492 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Exited from method onReactorFinal
2018-07-02 15:01:34,492 [main] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Entered in method authenticate
2018-07-02 15:01:34,493 [main] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Exited from method authenticate
2018-07-02 15:01:34,493 [main] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Entered in method openLinks
2018-07-02 15:01:34,493 [main] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Exited from method openLinks
2018-07-02 15:01:34,493 [main] WARN  com.lexmark.champs.collector.azure.AzureConnection  - An IOException occurred.
java.io.IOException: Could not open the connection
	at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:164)
	at com.microsoft.azure.sdk.iot.device.InternalClient.open(InternalClient.java:130)
	at com.lexmark.champs.collector.azure.AzureConnection.initialize(AzureConnection.java:53)
	at com.lexmark.champs.collector.web.WebServer.init(WebServer.java:226)
	at com.lexmark.champs.collector.daemon.UnixDaemon.main(UnixDaemon.java:53)
Caused by: com.microsoft.azure.sdk.iot.device.transport.amqps.exceptions.AmqpConnectionFramingErrorException
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsExceptionTranslator.convertToAmqpException(AmqpsExceptionTranslator.java:36)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.onTransportError(AmqpsIotHubConnection.java:745)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.IotHubReactor.run(IotHubReactor.java:28)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call(AmqpsIotHubConnection.java:808)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-07-02 15:01:34,501 [main] DEBUG uk.org.lidalia.sysoutslf4j.context.SysOutOverSLF4JInitialiser  - Your logging framework class org.slf4j.impl.Log4jLoggerAdapter should not need access to the standard println methods on the console, so you should not need to register a logging system package.
2018-07-02 15:01:34,512 [main] INFO  uk.org.lidalia.sysoutslf4j.context.SysOutOverSLF4J  - Replaced standard System.out and System.err PrintStreams with SLF4JPrintStreams
2018-07-02 15:01:34,517 [main] INFO  uk.org.lidalia.sysoutslf4j.context.SysOutOverSLF4J  - Redirected System.out and System.err to SLF4J for this context

Any information would be greatly appreciated, thanks.

**Comment by timtay-microsoft** [comment]
Can you please provide the exception stacktrace you receive for when using MQTT as well?

**Comment by timtay-microsoft** [comment]
We are looking into this issue right now, and I'll keep you posted when progress has been made.

**Comment by akulofficial** [comment]
Sorry for the delayed response, but below is the exception stacktrace for MQTT as well.
[Connection string object created successfully, redacted due to private info]
[DeviceClientConfig successfully created, redacted due to private info]
2018-07-03 15:03:00,659 [main] INFO  com.microsoft.azure.sdk.iot.device.DeviceIO  - DeviceIO object is created successfully, method name is <init> 
2018-07-03 15:03:00,819 [main] WARN  com.lexmark.champs.collector.azure.AzureConnection  - An IOException occurred.
java.io.IOException: Could not open the connection
	at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:164)
	at com.microsoft.azure.sdk.iot.device.InternalClient.open(InternalClient.java:130)
	at com.lexmark.champs.collector.azure.AzureConnection.initialize(AzureConnection.java:54)
	at com.lexmark.champs.collector.web.WebServer.init(WebServer.java:226)
	at com.lexmark.champs.collector.daemon.UnixDaemon.main(UnixDaemon.java:53)
Caused by: com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Unable to establish MQTT connection
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:69)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connect(Mqtt.java:110)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttMessaging.start(MqttMessaging.java:49)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:174)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:642)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.open(IotHubTransport.java:277)
	at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:160)
	... 4 more
Caused by: Unable to connect to server (32103) - java.net.ConnectException: Connection refused (Connection refused)
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:94)
	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:103)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:701)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:80)
	... 9 more
2018-07-03 15:03:00,830 [main] DEBUG uk.org.lidalia.sysoutslf4j.context.SysOutOverSLF4JInitialiser  - Your logging framework class org.slf4j.impl.Log4jLoggerAdapter should not need access to the standard println methods on the console, so you should not need to register a logging system package.
2018-07-03 15:03:00,841 [main] INFO  uk.org.lidalia.sysoutslf4j.context.SysOutOverSLF4J  - Replaced standard System.out and System.err PrintStreams with SLF4JPrintStreams
2018-07-03 15:03:00,847 [main] INFO  uk.org.lidalia.sysoutslf4j.context.SysOutOverSLF4J  - Redirected System.out and System.err to SLF4J for this context

**Comment by timtay-microsoft** [comment]
Just to clarify this issue, you are communicating from a module to an IotHub, and not to an EdgeHub, correct? During the create from environment call, is it using a connection string, or is it calling an HSM to get the authentication token? If you are using a connection string, what is the format of that connection string?

**Comment by timtay-microsoft** [comment]
@akulofficial can you please clarify on my questions above? And are you still seeing the problem with MQTT in the newest Device Client 1.13.1 package? (AMQP should still be broken, but we pushed some fixes for MQTT in that package)

**Comment by akulofficial** [comment]
MQTT didn't seem to work, but upon further investigation (on a Linux machine and my Macbook), the problem seemed to stem from our company's firewall, however, after GA, the issue eventually caused no modules to connect including the Edge Agent which would try to connect via AMQPS, then fail, then try web sockets, then fail, then have an error to the tune of something like "No configuration found--using backup json" (I'm paraphrasing here, but I will reproduce and provide a stacktrace if requested).

**Comment by akulofficial** [comment]
The firewall actually doesn't allow connections over that port so that was definitely part of the issue (although this problem persisted when my laptop was outside the firewall).

**Comment by timtay-microsoft** [comment]
@akulofficial are you still seeing any issues here with the latest release?

**Comment by akulofficial** [comment]
Apologies for the late response but as I have left the job in which this issue was persistent, I haven't been working on this issue. I'll go ahead and close the issue due to that, but it seemed that other than firewall issues, there weren't major connectivity issues with AMQPS (MQTT was a little more finicky, but after 1.13.4, it was a lot more stable).

**Comment by az-iot-builder-01** [comment]
@akulofficial, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
