### ISSUE TITLE
Memory leak using DeviceClient with AMQPS (over WS) due to network issues

### ISSUE THREAD

**Issue by palg** [Azure/azure-iot-sdk-java#273]
- **OS and version used:** Red Hat Enterprise Linux 7 x86_64

- **Java runtime used:** Java(TM) SE Runtime Environment (build 1.8.0_131-b11)

- **SDK version used:** com.microsoft.azure.sdk.iot.iot-device-client 1.11.0

# Description of the issue:
Using iot-device-client SDK, when we create a `DeviceClient `using AMQPS over websockets, in order to update the reported properties of the device twin, if the connection fails the SDK creates several threads in order to reconnect, but these threads are never destroyed, creating a memory leak after several requests. All these threads are alive after closing the 'DeviceClient'.

For example, at `com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection`, doing some debug, we have seen that the method `scheduleReconnection `manages reconnections creating a `ScheduledExecutorService `as local variable, so the method `shutdown` of this executor is never invoked, leaving the reconnection thread as parked forever:

```
private void scheduleReconnection(Throwable throwable)
{
    if (!reconnectionScheduled)
    {
        reconnectionScheduled = true;
        ScheduledExecutorService reconnectThread = Executors.newScheduledThreadPool(1);
        reconnectThread.schedule(new ReconnectionTask(throwable, this.listener, this.connectionId), 0, TimeUnit.MILLISECONDS);
    }
} 

```
# Code sample exhibiting the issue:
```
DeviceClient deviceClient = new DeviceClient(deviceConnectionString, IotHubClientProtocol.AMQPS_WS);
deviceClient.open();
deviceClient.startDeviceTwin(...);
...
deviceClient.sendReportedProperties(message);
...
deviceClient.closeNow();
```

# Console log of the issue:
This is a VisualVM snapshot showing the leaked thread created after several invocations:

![imagen](https://user-images.githubusercontent.com/3263163/42616203-a7f77f64-85ad-11e8-864a-b509dcb5e88e.png)

Some logs:
```
0    [main] INFO  com.microsoft.azure.sdk.iot.device.IotHubConnectionString  - IotHubConnectionString object is created successfully for iothub-xxxxx.azure-devices.net, method name is <init> 
591  [main] INFO  com.microsoft.azure.sdk.iot.device.DeviceClientConfig  - DeviceClientConfig object is created successfully with IotHubName=iothub-xxxxx.azure-devices.net, deviceID=xxxxx , method name is <init> 
1075 [main] INFO  com.microsoft.azure.sdk.iot.device.DeviceIO  - DeviceIO object is created successfully, method name is <init> 
1076 [main] INFO  com.microsoft.azure.sdk.iot.device.DeviceClient  - DeviceClient object is created successfully, method name is commonConstructorSetup 
52549 [main] INFO  com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - AmqpsIotHubConnection object is created successfully using port 443 in <init> method 
60363 [main] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Entered in method open
60363 [main] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Entered in method openAsync
60363 [azure-iot-sdk-AmqpsDeviceAuthenticationCBSTokenRenewalTask] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionDeviceOperation  - Entered in method renewToken
60364 [azure-iot-sdk-AmqpsDeviceAuthenticationCBSTokenRenewalTask] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionDeviceOperation  - Exited from method renewToken
60469 [main] INFO  com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Reactor is assigned to executor service, method name is openAsync 
60508 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Entered in method onReactorInit
60530 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Exited from method onReactorInit
60548 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Entered in method onConnectionInit
60548 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionManager  - Entered in method onConnectionInit
60557 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsDeviceAuthenticationCBS  - Entered in method openLinks
60586 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsDeviceAuthenticationCBS  - Exited from method openLinks
60586 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionManager  - Exited from method onConnectionInit
60586 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Exited from method onConnectionInit
61120 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Entered in method onLinkInit
61120 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionManager  - Entered in method onLinkInit
61120 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsDeviceAuthenticationCBS  - Entered in method initLink
61122 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsDeviceAuthenticationCBS  - Exited from method initLink
61122 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionManager  - Exited from method onLinkInit
61122 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Exited from method onLinkInit
61122 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Entered in method onLinkInit
61123 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionManager  - Entered in method onLinkInit
61123 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsDeviceAuthenticationCBS  - Entered in method initLink
61125 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsDeviceAuthenticationCBS  - Exited from method initLink
61125 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionManager  - Exited from method onLinkInit
61126 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Exited from method onLinkInit
61126 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Entered in method onConnectionBound
61151 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionManager  - Entered in method onConnectionBound
61856 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionManager  - Exited from method onConnectionBound
61856 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Exited from method onConnectionBound
61958 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Entered in method onTransportError
62015 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Exited from method onTransportError
62016 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Entered in method onConnectionUnbound
62016 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Exited from method onConnectionUnbound
62016 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Entered in method onReactorFinal
62016 [azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Exited from method onReactorFinal
62016 [main] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Entered in method authenticate
62017 [main] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Exited from method authenticate
62017 [main] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Entered in method openLinks
62017 [main] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection  - Exited from method openLinks
78594 [main] INFO  com.microsoft.azure.sdk.iot.device.DeviceClient  - Connection closed with success, method name is closeNow 

java.io.IOException: Could not open the connection
	at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:164)
	at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:372)
	at com.ericsson.m2m.components.cloudcon.impl.azure.manager.AzureManager.send(AzureManager.java:55)
	... 25 more
Caused by: com.microsoft.azure.sdk.iot.device.transport.amqps.exceptions.AmqpConnectionFramingErrorException
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsExceptionTranslator.convertToAmqpException(AmqpsExceptionTranslator.java:36)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.onTransportError(AmqpsIotHubConnection.java:738)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.IotHubReactor.run(IotHubReactor.java:28)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call(AmqpsIotHubConnection.java:799)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by timtay-microsoft** [comment]
Good catch, this is a bug on our side. We'll look into fixing this issue

**Comment by palg** [comment]
Hi again.

Thanks for submitting the changes.
However, I have tested again with the last version and I still get the same problem.

I have made a test with one request blocking the connection and these are the threads that are alive after closing the device client:

![new version block](https://user-images.githubusercontent.com/3263163/43198707-dc0c7608-900f-11e8-900a-7ecbe0958589.PNG)

I have made a debug session trying to find where one of this leaked threads is created. In the case of the thread _"azure-iot-sdk-AmqpsDeviceAuthenticationCBSSendTask"_ we have seen that is created when calling _DeviceClient.open_ in this request chain:
```
com.microsoft.azure.sdk.iot.device.DeviceClient#open
com.microsoft.azure.sdk.iot.device.InternalClient#open
com.microsoft.azure.sdk.iot.device.DeviceIO#open
com.microsoft.azure.sdk.iot.device.transport.IotHubTransport#open
com.microsoft.azure.sdk.iot.device.transport.IotHubTransport#openConnection
com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection#AmqpsIotHubConnection (Constructor)
com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionManager#AmqpsSessionManager (Constructor)
```
When creating the _AmqpsSessionManager_ a thread pool is created as _"taskSchedulerCBSSend"_ and a thread is scheduled:

> com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionManager:65

```
	this.taskSchedulerCBSSend = Executors.newScheduledThreadPool(2);
        this.taskSchedulerCBSSend.scheduleAtFixedRate(this.cbsAuthSendTask, 0, SEND_PERIOD_MILLISECONDS, TimeUnit.MILLISECONDS);
```

This is the thread identified as _"azure-iot-sdk-AmqpsDeviceAuthenticationCBSSendTask"_ because it internally changes its name to this value.

After this, the connection tries to be opened but the connection fails, and we close the device client invoking _DeviceClient.closeNow_:
```
com.microsoft.azure.sdk.iot.device.DeviceClient#closeNow
com.microsoft.azure.sdk.iot.device.InternalClient#closeNow
com.microsoft.azure.sdk.iot.device.DeviceIO#close
```
This is the code of _DeviceIO.close_:

```
       public void close() throws IOException
	{
		/* Codes_SRS_DEVICE_IO_21_020: [If the client is already closed, the close shall do nothing.] */
		if (this.state == IotHubClientState.CLOSED)
		{
			return;
		}

		/* Codes_SRS_DEVICE_IO_21_017: [The close shall finish all ongoing tasks.] */
		/* Codes_SRS_DEVICE_IO_21_018: [The close shall cancel all recurring tasks.] */
		this.taskScheduler.shutdown();

		/* Codes_SRS_DEVICE_IO_21_019: [The close shall close the transport.] */
		try
		{
			this.transport.close(IotHubConnectionStatusChangeReason.CLIENT_CLOSE, null);
		}
		catch (DeviceClientException e)
		{
			this.state = IotHubClientState.CLOSED;
			throw new IOException(e);
		}

		/* Codes_SRS_DEVICE_IO_21_021: [The close shall set the `state` as `CLOSE`.] */
		this.state = IotHubClientState.CLOSED;
	}
```
Due to the network connection failure, _this.state_ is _IotHubClientState.CLOSED_ so _this.transport.close_ is never invoked. This _this.transport.close_ is the responsible of disposing the thread pool:
```
com.microsoft.azure.sdk.iot.device.transport.IotHubTransport#close
com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection#close
com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection#closeAsync
com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionManager#closeNow
com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionManager#shutDownScheduler
```
```
	private void shutDownScheduler()
	{
		if (this.taskSchedulerCBSSend != null)
		{
			this.taskSchedulerCBSSend.shutdown(); // Disable new tasks from being submitted
			try
			{
				// Wait a while for existing tasks to terminate
				if (!this.taskSchedulerCBSSend.awaitTermination(10, TimeUnit.SECONDS))
				{
					this.taskSchedulerCBSSend.shutdownNow(); // Cancel currently executing tasks
					// Wait a while for tasks to respond to being cancelled
					if (!this.taskSchedulerCBSSend.awaitTermination(10, TimeUnit.SECONDS))
					{
						System.err.println("taskSchedulerTokenRenewal did not terminate correctly");
					}
				}
			}
			catch (InterruptedException ie)
			{
				// (Re-)Cancel if current thread also interrupted
				this.taskSchedulerCBSSend.shutdownNow();
				// Preserve interrupt status
				Thread.currentThread().interrupt();
			}
		}
	}
```

Maybe I am wrong at some point, please check this explanation in order to verify my diagnosis.

Thanks again,

Pablo

**Comment by jasmineymlo** [comment]
This seems to be another leak rather than the original reported one.  Thanks for the additional info.  We will look into it.

**Comment by palg** [comment]
In fact, in the original report you can see several leaked threads:
```
azure-iot-sdk-ReactorRunner
azure-iot-sdk-AmqpsDeviceAuthenticationCBSxxxxx
pool-x-thread-y
```
Initially, I made an static code analysis and see the local variable issue but, as you can see in my last update, debuging the creation of one of the leaked threads I have found another problematic point.

My point here is that the thread leak problem may be caused by more that one code issues.

**Comment by jasmineymlo** [comment]
Looking into it actively and will provide a fix for that.  Thanks.

**Comment by jasmineymlo** [comment]
The initial fix is checked in for the majority of the leak.  We are working on the rest.  We hope to close on this in the next release.  Thanks.

**Comment by jasmineymlo** [comment]
@rkanubaddhi a5b70b1c86a8d60d96a49f3e4329db217f812054 should address the leak.  Please check and let us know.  Thanks.

**Comment by jasmineymlo** [comment]
In https://github.com/Azure/azure-iot-sdk-java/releases/tag/2018-8-10.  Thanks.

**Comment by CraigGemmill** [comment]
Hi @jasmineymlo -  I have been working with rkanubaddhi on this issue.  We have used the 2018-08-30 release (1.14.0), but I am still seeing the threads described by @palg as being leaked when the connection is unavailable for a period of time.  The biggest concern is the "pool-X-thread-Y" threads, as these seem to accumulate.  The leakage of the CBSSendTask and ReactorRunner threads seems to be non-accumulating.  Have there been any further insights, or are you considering the issue fixed?

**Comment by CraigGemmill** [comment]
A little clarification - in our test, I have a connector that is using the iot sdk, which is disconnected for about an hour.  After this time, I see two threads named "azure-iot-sdk-AmqpsDeviceAuthenticationCBSTokenRenewalTask", and eight threads with "pool-X-thread-Y" names.  I will work to generate a test code sample, and post a new issue if that is the preferred approach.

**Comment by timtay-microsoft** [comment]
The leaking CBS threads already has a fix in master, but has not been released yet. I can't comment on the other leaked threads. @jasmineymlo ?
