### ISSUE TITLE
[ModuleClient] GSON StackOverflowError when ModuleClient.createFromEnvironment(MQTT)

### ISSUE THREAD

**Issue by adashen** [Azure/azure-iot-sdk-java#280]
- **OS and version used:** Ubuntu 18.04

- **Java runtime used:** open-jdk 8
- **SDK version used:** 1.13.1

# Description of the issue:
mvn install module-invoke-method-sample
https://github.com/Azure/azure-iot-sdk-java/tree/master/device/iot-device-samples/module-invoke-method-sample

And containerize the result with Docker file:

FROM openjdk:8-jdk-alpine
COPY target/module-invoke-method-sample-1.13.1-with-deps.jar /app.jar
ENTRYPOINT ["java","-jar","/app.jar"]

Follow instruction https://docs.microsoft.com/en-us/azure/iot-edge/quickstart-linux
to deploy the java module to Ubuntu 18.04

And got the StackOverFlow Error during 
ModuleClient client = ModuleClient.createFromEnvironment(IotHubClientProtocol.MQTT)

# Code sample exhibiting the issue:
ModuleClient client = ModuleClient.createFromEnvironment(IotHubClientProtocol.MQTT)

# Console log of the issue:
Exception in thread "main" java.lang.StackOverflowError
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:353)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
        at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
....
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:158)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
        at com.google.gson.Gson.getAdapter(Gson.java:423)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
        at com.google.gson.Gson.getAdapter(Gson.java:423)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
        at com.google.gson.Gson.getAdapter(Gson.java:423)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
        at com.google.gson.Gson.getAdapter(Gson.java:423)

**Comment by jasmineymlo** [comment]
In https://github.com/Azure/azure-iot-sdk-java/releases/tag/2018-8-10.  Thanks.
