### ISSUE TITLE
Gracefully handle MQTT disconnections around sas token expiry time

### ISSUE THREAD

**Issue by timtay-microsoft** [Azure/azure-iot-sdk-java#316]
- **OS and version used:** any

- **Java runtime used:** any

- **SDK version used:** any

# Description of the issue:
Now that IotHub is actually forcing MQTT connections to end approximately around the time that the used sas token expires, customers are seeing more frequent connection status updates saying DISCONNECTED_RETRYING. It may be worthwhile to pre-emptively end the mqtt connection to attempt to re-open with a new sas token. It also may be worthwhile to not notify the connection status callback during this process as this is an expected connected change that is no cause for alarm.

**Comment by timtay-microsoft** [comment]
Thanks for filing this issue. We'll look into it soon.

**Comment by timtay-microsoft** [comment]
The IotHub team has advised that there is no benefit on their side to preemptively killing the connection like this, but there may be benefit on the SDK side if we intend to not report connection status changes that occur as a result of doing this. We are still weighing if this is a worthwhile feature or not

**Comment by fmarion** [comment]
Hi timtay, is there any updates on this issue?

We are currently receiving DISCONNECTED_RETRYING status updates when the sas token expires. This generates a lot of false disconnection events that should not be seen by the customer.

It is difficult to distinguish between *real* disconnection and forced disconnection. Usually we want to report disconnection events to the user, but those periodic forced disconnection flood the log needlessly. We take some steps to recover from a real disconnection, but we could avoid doing them in the case of a forced one.

On the IotHub side, the logs are filled with `Connection Error - 404104` for an expected behavior.

Thanks for your help.

**Comment by fmarion** [comment]
Ok Thanks. I receive NO_NETWORK on my side.

You can test it by using the `send-event` sample.
Just add a Thread.sleep(1000) after the sendEventAsync().

By sending enought messages to reach that time out, you will 
get a stack trace like this:

```
CONNECTION STATUS UPDATE: DISCONNECTED_RETRYING
CONNECTION STATUS REASON: NO_NETWORK
CONNECTION STATUS THROWABLE: Mqtt connection lost

com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Mqtt connection lost
    at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:75)
    at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connectionLost(Mqtt.java:367)
    at org.eclipse.paho.client.mqttv3.internal.CommsCallback.connectionLost(CommsCallback.java:292)
    at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:423)
    at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:181)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: Connection lost (32109) - java.io.EOFException
    ... 8 more
Caused by: java.io.EOFException
    at java.io.DataInputStream.readByte(DataInputStream.java:267)
    at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
    at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:133)
    ... 7 more
```

**Comment by timtay-microsoft** [comment]
Since we do not plan on implementing this feature after all, I'm closing this issue

**Comment by az-iot-builder-01** [comment]
@fmarion, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
