### ISSUE TITLE
Connection to IoT HUB fails on IoT Gateway whereas same source code works on another machines

### ISSUE THREAD

**Issue by tarung76** [Azure/azure-iot-sdk-java#328]
**Gateway (Not establishing communication with Azure IoT Hub)**
Linux OS: 
Linux WR-IDP-A027 3.14.5B_IDP-XT_3.1-grsec-WR7.0.0.25_idp

Java RunTime: 
java version "1.8.0_171"
Java(TM) SE Runtime Environment (Build 1.8.0_171-b11)
Java Hotspot(TM) 64-Bit Server VM (build 25.171.b11, mixed mode)

Azure SDK IOT: 
iot-device-client (1.7.0)

# Description of the issue:
same source code (Java), works on other machine expect on IoT gateway with above setup.  It give error "java.io.IOException: java.io.IOException: Unable to connect to servicenull"

Full Log Error Stack:
java.io.IOException: java.io.IOException: Unable to connect to servicenull
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:182)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttTransport.open(MqttTransport.java:83)
	at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:176)
	at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:365)
	at com.lnt.client.comm.AzureIOTClient.getDeviceClient(AzureIOTClient.java:41)
	at com.lnt.client.comm.AzureIOTClient.getInstance(AzureIOTClient.java:24)
	at com.lnt.main.LightingAgentMain.main(LightingAgentMain.java:348)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.io.IOException: Unable to connect to servicenull
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connect(Mqtt.java:112)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttMessaging.start(MqttMessaging.java:38)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:162)
	... 11 more
Caused by: Not authorized to connect (5)
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:28)
	at org.eclipse.paho.client.mqttv3.internal.ClientState.notifyReceivedAck(ClientState.java:988)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:145)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by timtay-microsoft** [comment]
Are you able to upgrade to the latest version of the Device Client library? And what is the source code that you are using? In particular, I need to know what form of authentication you are using. The stacktrace you provided suggests that you are using an expired sas token, or the x509 certificates for the wrong device.

**Comment by timtay-microsoft** [comment]
As of right now, this SDK does not have proxy support, so you may be hitting that issue, too.

**Comment by timtay-microsoft** [comment]
@tarung76 do you have any additional context you can provide on this issue?

**Comment by timtay-microsoft** [comment]
@tarung76 are you still running into this issue?

**Comment by timtay-microsoft** [comment]
I'm going to go ahead and close this issue due to inactivity. If you can provide more context on this issue later, feel free to open this issue again.

**Comment by az-iot-builder-01** [comment]
@tarung76, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
