### ISSUE TITLE
Issue starting Java Edge Module

### ISSUE THREAD

**Issue by VercammenG** [Azure/azure-iot-sdk-java#353]
- **OS and version used:** Ubuntu 16.04.5

# Description of the issue:
Everytime I try and start a default generated Edge Module on a Linux VM with IoT Edge running it fails. The default Edge modules for the other supported languages (Python, NodeJS) do work.

I could not find any earlier documentation on this issue.

# Console log of the issue:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
com.microsoft.azure.sdk.iot.device.exceptions.ModuleClientException: java.io.IOException: Broken pipe
        at com.microsoft.azure.sdk.iot.device.ModuleClient.createFromEnvironment(ModuleClient.java:252)
        at com.organisation.App.main(App.java:72)
Caused by: java.io.IOException: Broken pipe
        at jnr.enxio.channels.Common.write(Common.java:116)
        at jnr.enxio.channels.AbstractNativeSocketChannel.write(AbstractNativeSocketChannel.java:72)
        at jnr.unixsocket.UnixSocketChannel.write(UnixSocketChannel.java:261)
        at com.microsoft.azure.sdk.iot.device.hsm.HttpsHsmClient.sendHttpRequestUsingUnixSocket(HttpsHsmClient.java:256)
        at com.microsoft.azure.sdk.iot.device.hsm.HttpsHsmClient.sendRequestBasedOnScheme(HttpsHsmClient.java:225)
        at com.microsoft.azure.sdk.iot.device.hsm.HttpsHsmClient.getTrustBundle(HttpsHsmClient.java:157)
        at com.microsoft.azure.sdk.iot.device.edge.HttpsHsmTrustBundleProvider.getTrustBundleCerts(HttpsHsmTrustBundleProvider.java:38)
        at com.microsoft.azure.sdk.iot.device.ModuleClient.createFromEnvironment(ModuleClient.java:244)
        ... 1 more```

**Comment by VercammenG** [comment]
Hello @timtay-microsoft,

I consistently have the issue about all the time when I start it up. Every couple of times it will start up properly and work, but the vast majority of the times this error gets thrown.

**Comment by pietersap** [comment]
"iotedge restart <java module name>" usually works immediately for me. I don't know why it happens either, but I'm new to Java

**Comment by timtay-microsoft** [comment]
This may be a bug with the Java sdk rather than the environment you are running your edgehub in. I'll update this thread with my findings soon.

**Comment by az-iot-builder-01** [comment]
@VercammenG, @pietersap, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
