### ISSUE TITLE
[Device Client] AMQP should refresh token automatically to avoid reconnection

### ISSUE THREAD

**Issue by Sensing-Control-DevTeam** [Azure/azure-iot-sdk-java#365]
- **OS and version used:** Windows 10 / Raspbian

- **Java runtime used:** 1.8

- **SDK version used:** 1.14.1

# Description of the issue:
When using AMQP (WS) we're seeing this exception and reconnection about 1 time every hour, as the system knows the token expiration date it should automatically try to refresh it in advance so these exceptions do not happen.

# Console log of the issue:

```
2018-11-06 08:36:35,944 AzureIoTHub [pool-18680-thread-1] DEBUG: IoTHub connection state callback, status: DISCONNECTED_RETRYING reason: BAD_CREDENTIAL
com.microsoft.azure.sdk.iot.device.transport.amqps.exceptions.AmqpUnauthorizedAccessException: Token Invalid.
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsExceptionTranslator.convertToAmqpException(AmqpsExceptionTranslator.java:87)
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.getTransportExceptionFromEvent(AmqpsIotHubConnection.java:1161)
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.onLinkRemoteClose(AmqpsIotHubConnection.java:730)
        at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
        at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
        at com.microsoft.azure.sdk.iot.device.transport.amqps.IotHubReactor.run(IotHubReactor.java:28)
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call(AmqpsIotHubConnection.java:810)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2018-11-06 08:36:37,239 AzureIoTHub [pool-18680-thread-1] DEBUG: IoTHub connection state callback, status: CONNECTED reason: CONNECTION_OK

```

**Comment by timtay-microsoft** [comment]
What kind of authentication token are you providing to your device client? Is it the full shared access key, or is it just a sas token?

**Comment by pizerg** [comment]
We're using a connection string to create the DeviceClient with the device's shared access key

**Comment by prmathur-microsoft** [comment]
We use CBS over AMQP to automatically refresh token before they expire. What you are noticing is the link closure on expiry. This looks like a bug to me. We will add it to our backlog and address it. In the meantime, if you have a fix proposal feel free to submit a PR. We will be happy to review.

**Comment by timtay-microsoft** [comment]
From my investigation, it seems that our cbs flow is messed up. Right now, the client will only send a new sas token to the service after the one it has is expired. This means there is no pre-emptive renewal like we intended there to be. This is a bug on our side, and I'll look into fixing it soon.

**Comment by az-iot-builder-01** [comment]
@Sensing-Control-DevTeam, @pizerg, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
