### ISSUE TITLE
[Device Client] AMQP takes long time to detect connection drop

### ISSUE THREAD

**Issue by Sensing-Control-DevTeam** [Azure/azure-iot-sdk-java#366]
- **OS and version used:** Windows 10 / Raspbian

- **Java runtime used:** 1.8

- **SDK version used:** 1.14.1

# Description of the issue:
When connection drops, between the first failed to deliver message and the reconnection attempt there's a gap of around 15 minutes, also the messages do not expire until after the reconnection has succeeded

# Console log of the issue:

First failed message:
`2018-11-05 17:02:44,706 AzureIoTHub [pool-36-thread-1] DEBUG: ERROR sending IoTHub message`

4 more messages are sent (+/- 4 min interval)
```
2018-11-05 17:06:44,737 AzureIoTHub [pool-36-thread-10] DEBUG: ERROR sending IoTHub message
2018-11-05 17:10:44,733 AzureIoTHub [pool-36-thread-8] DEBUG: ERROR sending IoTHub message
2018-11-05 17:13:45,364 AzureIoTHub [pool-38-thread-1] DEBUG: ERROR sending IoTHub message
2018-11-05 17:14:44,733 AzureIoTHub [pool-36-thread-4] DEBUG: ERROR sending IoTHub message
```

First reconnection attempt:
```
2018-11-05 17:17:12,284 AzureIoTHub [pool-11801-thread-1] DEBUG: IoTHub connection state callback, status: DISCONNECTED_RETRYING reason: NO_NETWORK
com.microsoft.azure.sdk.iot.device.exceptions.TransportException: Unknown transport exception occurred
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.getTransportExceptionFromEvent(AmqpsIotHubConnection.java:1100)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.onTransportError(AmqpsIotHubConnection.java:749)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.IotHubReactor.run(IotHubReactor.java:28)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call(AmqpsIotHubConnection.java:810)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-11-05 17:17:13,591 AzureIoTHub [pool-11801-thread-1] DEBUG: IoTHub connection state callback, status: CONNECTED reason: CONNECTION_OK
2018-11-05 17:17:13,595 AzureIoTHub [azure-iot-sdk-IotHubSendTask] DEBUG: In result callback with status: MESSAGE_EXPIRED
2018-11-05 17:17:13,595 AzureIoTHub [azure-iot-sdk-IotHubSendTask] DEBUG: In result callback with status: MESSAGE_EXPIRED
2018-11-05 17:17:13,595 AzureIoTHub [azure-iot-sdk-IotHubSendTask] DEBUG: In result callback with status: MESSAGE_EXPIRED
2018-11-05 17:17:13,596 AzureIoTHub [azure-iot-sdk-IotHubSendTask] DEBUG: In result callback with status: MESSAGE_EXPIRED
2018-11-05 17:17:13,596 AzureIoTHub [azure-iot-sdk-IotHubSendTask] DEBUG: In result callback with status: MESSAGE_EXPIRED
```

**Comment by timtay-microsoft** [comment]
Can you provide a code sample of how you are using the device client? What type of authentication are you using?

**Comment by pizerg** [comment]
We're using a code similar to this, authentication method is connection string with device's SharedAccessKey:

```
DeviceClient client = new DeviceClient("CONNECTION_STRING", IotHubClientProtocol.AMQPS_WS);
client.setOperationTimeout(Long.MAX_VALUE);

client.registerConnectionStatusChangeCallback(new IotHubConnectionStatusChangeCallback() {
	@Override
	public void execute(IotHubConnectionStatus status, IotHubConnectionStatusChangeReason statusChangeReason, Throwable throwable, Object callbackContext) {
		// some logic
	}
}, null);

client.setMessageCallback(new MessageCallback() {
	@Override
	public IotHubMessageResult execute(Message message, Object callbackContext) {
		// some logic
	}
}, null);

client.open();

client.subscribeToDeviceMethod(callback, null, new IotHubEventCallback() {
	@Override
	public void execute(IotHubStatusCode responseStatus, Object callbackContext) {
		// some logic
	}
}, null);
```

**Comment by timtay-microsoft** [comment]
Are you seeing this on any other protocols?

**Comment by timtay-microsoft** [comment]
Also, if you are seeing connection status updates long after you are seeing the message callbacks with ERROR, it's more likely that your messages were rejected by the IotHub, but that the network connection to the IotHub was fine.

Do you have any other context on why those messages are being returned with ERROR? ERROR is the default status we present when we can't map the service error code to anything of [these](https://github.com/Azure/azure-iot-sdk-java/blob/64dd4a432015c35e315b639998ace16bf0d7d27c/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/IotHubStatusCode.java#L86) values.

Are you seeing this same 15 minute delay when you simply disconnect the Ethernet cord on your machine?

**Comment by pizerg** [comment]
Pretty sure it happened with both MQTT and AMQPS (both over WS). The messages couldn't have been rejected by IotHub because there was no network at all (pulled out eth cable), also notice the timing between the  "DISCONNECTED_RETRYING reason: NO_NETWORK" and "CONNECTED reason: CONNECTION_OK". 

We've been seeing this issue across all our deployments, usually when NO_NETWORK (network went down for some reason) we see almost immediately the CONNECTION_OK, I doubt all of our deployments (different countries, different cities) when they lose network it's only for a second (the time it takes usually to reconnect). So most likely there's something off with NO_NETWORK detection.

Ignore the "ERROR" log message as it's something internal, it just indicates that a message was not able to be sent through IoTHub (either due to error or timeout).

**Comment by timtay-microsoft** [comment]
Are you still seeing an issue here? We were unable to repro any issues with the NO_NETWORK detection locally on any protocol. And could you provide a full stacktrace on the exception that is given by the connection status change callback when you get NO_NETWORK?

**Comment by timtay-microsoft** [comment]
I'm going to close this issue due to inactivity. If you are still seeing issues around connectivity here, please feel free to re-open this issue with more context and/or repro steps

**Comment by az-iot-builder-01** [comment]
@Sensing-Control-DevTeam, @pizerg, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
