### ISSUE TITLE
[Android]Subsequent Iot connection fails on App crash 

### ISSUE THREAD

**Issue by sukesh2017** [Azure/azure-iot-sdk-java#408]
**OS and version used:** Android 8.0

**Java runtime used:** 1.7

**SDK version used:** iot-device-client:1.14.0

**Description of the issue:**
If app is crashing and if we try to connect again then we are not able to connect and proceed. we are unable connect forever. Always getting the exception when we try to open the connection.

**Code sample exhibiting the issue:**
private void start() {
        try {
            sClient = new DeviceClient(sConnString, IotHubClientProtocol.MQTT);
            sClient.registerConnectionStatusChangeCallback(new IotConnStatusCallback(), this);
            sClient.open();
        } catch (URISyntaxException | IOException e) {
            Log.e(TAG, "Exception in onStart()", e);
            mError = ERROR_STATE.ERROR;
        }
}
**Console log of the issue:**
com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Unable to subscribe to topic :devices/tnazeu-dv-mhs-device2/messages/devicebound/#
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:75)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.subscribe(Mqtt.java:283)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttMessaging.start(MqttMessaging.java:61)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:179)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:640)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.open(IotHubTransport.java:277)
	at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:160)
	at com.microsoft.azure.sdk.iot.device.InternalClient.open(InternalClient.java:130)
	at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:317)
	at com.tomra.dagwoodhandheld.clientManager.DeviceClientManager.connectDeviceToIOTHub(DeviceClientManager.java:92)
	at com.tomra.dagwoodhandheld.Repository.DataRepository.connectToDevice(DataRepository.java:191)
	at com.tomra.dagwoodhandheld.appmodules.SplashScreen.SplashInteractor.connectToDevice(SplashInteractor.java:26)
	at com.tomra.dagwoodhandheld.appmodules.SplashScreen.SplashScrenViewModel.connectToDevice(SplashScrenViewModel.java:29)
	at com.tomra.dagwoodhandheld.appmodules.SplashScreen.SplashScreenActivity.lambda$intialiseLayout$3$SplashScreenActivity(SplashScreenActivity.java:25)
	at com.tomra.dagwoodhandheld.appmodules.SplashScreen.SplashScreenActivity$$Lambda$0.onDelayCompleted(Unknown Source)
	at com.tomra.dagwoodhandheld.appmodules.CommonUI.BaseActivity$7.run(BaseActivity.java:425)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:7325)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: Timed out waiting for a response from the server (32000)
	at org.eclipse.paho.client.mqttv3.internal.Token.waitForCompletion(Token.java:112)
	at org.eclipse.paho.client.mqttv3.MqttToken.waitForCompletion(MqttToken.java:67)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.subscribe(Mqtt.java:278)
	... 21 more

**Comment by jasmineymlo** [comment]
@sukesh2017 Please update to [iot-device-client:1.14.2](https://github.com/Azure/azure-iot-sdk-java/releases/tag/2018-12-3) which include some important bug fixes for Android.  Let us know if that fixes this issue.  Thanks.

**Comment by timtay-microsoft** [comment]
@sukesh2017 do you have this issue after upgrading to the latest device client package?

**Comment by yzhong94** [comment]
@sukesh2017 we will close this issue for now since we haven't heard back.  Please reopen or file a new issue if you still see this repro on the latest version.  Thanks!

**Comment by az-iot-builder-01** [comment]
@sukesh2017, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
