### ISSUE TITLE
ProvisioningX509Sample provisioning issue

### ISSUE THREAD

**Issue by sharathnarayancodes** [Azure/azure-iot-sdk-java#486]
com.microsoft.azure.sdk.iot.provisioning.security.SecurityProviderSymmetricKey
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	
	ception in thread "main" java.lang.NoClassDefFoundError: com/microsoft/azure/sdk/iot/provisioning/security/SecurityProviderSymmetricKey
	at com.microsoft.azure.sdk.iot.device.DeviceClientConfig.<init>(DeviceClientConfig.java:206)
	at com.microsoft.azure.sdk.iot.device.InternalClient.<init>(InternalClient.java:104)
	at com.microsoft.azure.sdk.iot.device.DeviceClient.<init>(DeviceClient.java:267)
	at com.microsoft.azure.sdk.iot.device.DeviceClient.createFromSecurityProvider(DeviceClient.java:232)
	at samples.com.microsoft.azure.sdk.iot.ProvisioningX509Sample.main(ProvisioningX509Sample.java:139)
Caused by: java.lang.ClassNotFoundException: com.microsoft.azure.sdk.iot.provisioning.security.SecurityProviderSymmetricKey
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 5 more

**Comment by sharathnarayancodes** [comment]
Please help me in solving the above issue

**Comment by timtay-microsoft** [comment]
It looks like you did not include the jar file that contains the SecurityProviderSymmetricKey class when you ran the sample. How did you compile and then run the sample file?

**Comment by timtay-microsoft** [comment]
@sharathnarayancodes are you still seeing this issue?

**Comment by timtay-microsoft** [comment]
I'm closing this issue due to inactivity. Feel free to open another issue if you are still having trouble here.

**Comment by az-iot-builder-01** [comment]
@sharathnarayancodes, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
