### ISSUE TITLE
Enrollment group with intermediate cert does not work

### ISSUE THREAD

**Issue by hochas** [Azure/azure-iot-sdk-java#530]
**OS and version used:**
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

**Java runtime used:**
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.18.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)

**SDK version used:**

```xml
<dependency>
	<groupId>com.microsoft.azure.sdk.iot</groupId>
	<artifactId>iot-device-client</artifactId>
	<version>1.7.0</version>
</dependency>
```

# Description of the issue:
Using an intermediate cert in an enrollment group causes failure when provisioning devices.

Just to figure out how the DPS works before we use an actual CA, we have created our own root cert. We have uploaded the root cert and verified it. We have generated an intermediate cert from our root cert and created an enrollment group from this intermediate certificate. We have created this enrollment group both from the portal and using the service enrollment group sample.

We then use the device provisioning sample. We have tried using MQTT, HTTPS and AMQPS, they all fail.

Lastly, we tried to make device certs from the root cert that we uploaded and use the root cert in an enrollment group and that works fine.

# Code sample exhibiting the issue:
[Gist](https://gist.github.com/hochas/bd31d685d302dce5b64a161f73699b26). All of the samples/code used are from tutorials in the documentation.

# Console log of the issue:

**AMQPS:**
```
java.lang.NoSuchMethodError: com.microsoft.azure.sdk.iot.deps.transport.amqp.AmqpMessage.setBody([B)V
------------
java.lang.NoSuchMethodError: com.microsoft.azure.sdk.iot.deps.transport.amqp.AmqpMessage.setBody([B)V
Exception in thread "main" java.lang.RuntimeException: Got registration error PROVISIONING_DEVICE_STATUS_ERROR, bailing out java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: com.microsoft.azure.sdk.iot.deps.transport.amqp.AmqpMessage.setBody([B)V
	at storemanager.core.azure.DeviceProvisioningService.provisionDevice(DeviceProvisioningService.java:123)
	at storemanager.core.azure.DeviceProvisioningService.main(DeviceProvisioningService.java:92)
```
**MQTT:**
```
Exception opening connection
------------
java.io.IOException: Unable to connect to mqtt service
Exception in thread "main" java.lang.RuntimeException: Got registration error PROVISIONING_DEVICE_STATUS_ERROR, bailing out com.microsoft.azure.sdk.iot.provisioning.device.internal.exceptions.ProvisioningDeviceConnectionException: Exception opening connection
	at storemanager.core.azure.DeviceProvisioningService.provisionDevice(DeviceProvisioningService.java:123)
	at storemanager.core.azure.DeviceProvisioningService.main(DeviceProvisioningService.java:92)
```

**HTTPS:**
```
Exception in thread "main" ----------
com.microsoft.azure.sdk.iot.provisioning.device.internal.exceptions.ProvisioningDeviceHubException: {"errorCode":401002,"trackingId":"2bf770df-1a0a-4023-9edc-0a6d9b4c0a1c","message":"Unauthorized","timestampUtc":"2019-05-24T13:21:18.3939184Z"}
------------
com.microsoft.azure.sdk.iot.provisioning.device.internal.exceptions.ProvisioningDeviceHubException: {"errorCode":401002,"trackingId":"2bf770df-1a0a-4023-9edc-0a6d9b4c0a1c","message":"Unauthorized","timestampUtc":"2019-05-24T13:21:18.3939184Z"}
java.lang.RuntimeException: Got registration error PROVISIONING_DEVICE_STATUS_ERROR, bailing out java.util.concurrent.ExecutionException: com.microsoft.azure.sdk.iot.provisioning.device.internal.exceptions.ProvisioningDeviceHubException: {"errorCode":401002,"trackingId":"2bf770df-1a0a-4023-9edc-0a6d9b4c0a1c","message":"Unauthorized","timestampUtc":"2019-05-24T13:21:18.3939184Z"}
	at storemanager.core.azure.DeviceProvisioningService.provisionDevice(DeviceProvisioningService.java:123)
	at storemanager.core.azure.DeviceProvisioningService.main(DeviceProvisioningService.java:92)
```

**Comment by hochas** [comment]
Tried generating certs from the x509 generator in this repo and it works, so we were doing something wrong.

**Comment by az-iot-builder-01** [comment]
@hochas, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
