### ISSUE TITLE
Transport error with long running connection (messages are still sent)

### ISSUE THREAD

**Issue by larskn** [Azure/azure-iot-sdk-java#582]
We are running an application that sends C2D messages to multiple devices (currently about 10, later it might be 100 or more) and periodically (currently every ~20 seconds) receives D2C messages from them. The application is developed with Spring Boot 2.1.5.

- **OS and version used:** Ubuntu Server 18.04.2 LTS

- **Java runtime used:** OpenJDK 11.0.3

- **SDK version used:** iot-service-client 1.17.1

# Description of the issue:
In general everything is working well, but in production we noticed an issue if the application is running for a longer period of time. At some point (I could not see a pattern of how long it takes or how many message were sent), the application starts throwing Errors ("A Transport error occured") everytime the application sends a C2D message.

Interestingly, although an error occurs, **the message is still sent and received by the device**. But still this causes a lot of issues because from the application perspective the send operation failed and subsequent operations are not executed.

To fix this issue we need to restart the application.

# Code sample exhibiting the issue:
The connection is opened once when the service is initialized and kept open. Can this be an issue? Are there best practices for long running applications?

```
import java.io.IOException;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import com.microsoft.azure.sdk.iot.service.exceptions.IotHubException;
import com.microsoft.azure.sdk.iot.service.Message;
import com.microsoft.azure.sdk.iot.service.ServiceClient;

@Service
public class IotHubServiceImpl implements IotHubService {

    private final ServiceClient serviceClient;

    @Autowired
    public IotHubServiceImpl(@Value("${myapp.azure.iothub.service-connection-string}") String serviceConnectionString)
        throws IOException {
        this.serviceClient = 
            ServiceClient.createFromConnectionString(serviceConnectionString, IotHubServiceClientProtocol.AMQPS);
        this.serviceClient.open();
    }

    ...

    private void send(String deviceId, String payload) {
        try {
            Message message = new Message(payload);
            this.serviceClient.send(deviceId, message);
        }
        catch (IOException e) {
            // Exception handling
        }
        catch (IotHubException e) {
            // Exception handling
        }
    }

    ...
}
```

# Console log of the issue:

Unfortunately since this a production environment there are no debug logs available. The issue did not occur on my local machine yet.

```
Caused by: java.io.IOException: Connection failed to be established
	at com.microsoft.azure.sdk.iot.service.transport.amqps.AmqpSendHandler.sendComplete(AmqpSendHandler.java:386) ~[iot-service-client-1.17.1.jar!/:na]
	at com.microsoft.azure.sdk.iot.service.transport.amqps.AmqpSend.send(AmqpSend.java:136) ~[iot-service-client-1.17.1.jar!/:na]
	at com.microsoft.azure.sdk.iot.service.ServiceClient.send(ServiceClient.java:143) ~[iot-service-client-1.17.1.jar!/:na]
	at com.microsoft.azure.sdk.iot.service.ServiceClient.send(ServiceClient.java:123) ~[iot-service-client-1.17.1.jar!/:na]
	at my.application.integration.azure.iot.IotHubServiceImpl.send(IotHubServiceImpl.java:211) ~[myapplication-integration-1.2.1.jar!/:na]
	... 23 common frames omitted
Caused by: java.io.IOException: A Transport error occurred
	at com.microsoft.azure.sdk.iot.service.transport.amqps.AmqpSendHandler.onTransportError(AmqpSendHandler.java:270) ~[iot-service-client-1.17.1.jar!/:na]
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191) ~[proton-j-0.31.0.jar!/:na]
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) ~[proton-j-0.31.0.jar!/:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324) ~[proton-j-0.31.0.jar!/:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291) ~[proton-j-0.31.0.jar!/:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.run(ReactorImpl.java:357) ~[proton-j-0.31.0.jar!/:na]
	at com.microsoft.azure.sdk.iot.service.transport.amqps.AmqpSend.send(AmqpSend.java:133) ~[iot-service-client-1.17.1.jar!/:na]
	... 26 common frames omitted
```

There is nothing else in the log that is in any way unusual. Moments before this error, messages are sent correctly. After it occured once it occurs for every C2D message, always with the same stack trace that is shown above.

Is there any scenario that might cause this behaviour - receiving a transport error although the mesage is still sent? Or are we doing something wrong in managing our connection?

**Comment by timtay-microsoft** [comment]
The error logging within the AMQP service client is a bit lacking right now, so it's hard to say what that exception may be. How long does the connection live before you see one of these exceptions? Does it disappear if you periodically close and re-open the connection?

**Comment by larskn** [comment]
Unfortunately it is not really predictable. One time it takes 3 days, then it occured every day for 3 days in a row. Afterwards there was no problem for 11 days, then 6 days.

No I did not try closing and re-opening yet because it feels more like a workaround and I first wanted to check first if this maybe can be fixed properly.
So is this your recommended approach? Or do you have any other suggestions?

**Comment by timtay-microsoft** [comment]
We are working on a re-vamp of the service client such that it includes better logging. You can follow the progress of PR #672 if you are interested

**Comment by timtay-microsoft** [comment]
@larskn have you tried out the latest service client jar? And if you are still seeing issues with that jar, can you please provide logs?

**Comment by timtay-microsoft** [comment]
Closing this issue due to lack of activity

**Comment by az-iot-builder-01** [comment]
@larskn, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
