### ISSUE TITLE
TPM Exception: {COMMAND_CODE} when trying to provision device

### ISSUE THREAD

**Issue by tdesmet** [Azure/azure-iot-sdk-java#611]
- **OS and version used:** Linux kernel version 5.2.18 ARM32 

- **Java runtime used:** openjdk 11.0.3 2019-04-16 LTS
OpenJDK Runtime Environment Zulu11.31+16-CA (build 11.0.3+7-LTS)
OpenJDK Client VM Zulu11.31+16-CA (build 11.0.3+7-LTS, mixed mode)

- **SDK version used:** 
    <dependency>
      <groupId>com.microsoft.azure.sdk.iot</groupId>
      <artifactId>iot-device-client</artifactId>
      <version>1.18.0</version>
    </dependency>
    <dependency>
        <groupId>com.microsoft.azure.sdk.iot.provisioning.security</groupId>
        <artifactId>tpm-provider</artifactId>
        <version>1.1.2</version>
    </dependency>
    <dependency>
        <groupId>com.microsoft.azure.sdk.iot.provisioning.security</groupId>
        <artifactId>security-provider</artifactId>
        <version>1.3.0</version>
    </dependency>
    <dependency>
        <groupId>com.microsoft.azure.sdk.iot.provisioning</groupId>
        <artifactId>provisioning-device-client</artifactId>
        <version>1.7.1</version>
    </dependency>

# Description of the issue:
I am trying to get device provisioning to work on our custom boards. We use the infineon SLB9670 TPM chip via spi. I can use tpm2 tools to communicate with the tpm device.

When I start my application I get an Endorsement key and registration id but when trying to provision a tss.TpmException: TPM Exception: {COMMAND_CODE} exception is thrown.

Edit: some more info:
`tpm2_getcap -c properties-fixed` list the revision as 1.16
```
TPM_PT_FAMILY_INDICATOR:
  as UINT32:                0x08322e3000
  as string:                "2.0"
TPM_PT_LEVEL:               0
TPM_PT_REVISION:            1.16
TPM_PT_DAY_OF_YEAR:         0x0000000f
TPM_PT_YEAR:                0x000007e0
TPM_PT_MANUFACTURER:        0x49465800
TPM_PT_VENDOR_STRING_1:
  as UINT32:                0x534c4239
  as string:                "SLB9"
TPM_PT_VENDOR_STRING_2:
  as UINT32:                0x36373000
  as string:                "670"
TPM_PT_VENDOR_STRING_3:
  as UINT32:                0x00000000
  as string:                ""
TPM_PT_VENDOR_STRING_4:
  as UINT32:                0x00000000
  as string:                ""
TPM_PT_VENDOR_TPM_TYPE:     0x00000000
TPM_PT_FIRMWARE_VERSION_1:  0x0007003d
TPM_PT_FIRMWARE_VERSION_2:  0x000ae100
```

`tpm2_getcap -c commands` shows that the tpm chip does not have the EncryptDecrypt2 command.

# Code sample exhibiting the issue:
```
SecurityProviderTpm securityProviderTpm = null;
try {
  securityProviderTpm = new SecurityProviderTPMHsm();
  String endorsementKey = new String(Base64.encodeBase64Local(securityProviderTpm.getEndorsementKey()));
  String registrationId = securityProviderTpm.getRegistrationId();
  log.info("Endorsement Key : \n" + endorsementKey);
  log.info("Registration Id : \n" + registrationId);
  tPMSettingsStore.set(endorsementKey, registrationId);
} catch (SecurityProviderException e) {
  log.error("Could not create TPM security provider", e);
  return;
}

ProvisioningDeviceClient provisioningDeviceClient = null;
try {

  ProvisioningStatus provisioningStatus = new ProvisioningStatus();
  provisioningDeviceClient = ProvisioningDeviceClient.create(GLOBAL_ENDPOINT, SCOPE_ID,
      ProvisioningDeviceClientTransportProtocol.HTTPS, securityProviderTpm);
  provisioningDeviceClient.registerDevice(new ProvisioningDeviceClientRegistrationCallbackImpl(),
      provisioningStatus);
  while (provisioningStatus.provisioningDeviceClientRegistrationInfoClient
      .getProvisioningDeviceClientStatus() != ProvisioningDeviceClientStatus.PROVISIONING_DEVICE_STATUS_ASSIGNED) {
    if (provisioningStatus.provisioningDeviceClientRegistrationInfoClient
        .getProvisioningDeviceClientStatus() == ProvisioningDeviceClientStatus.PROVISIONING_DEVICE_STATUS_ERROR
        || provisioningStatus.provisioningDeviceClientRegistrationInfoClient
            .getProvisioningDeviceClientStatus() == ProvisioningDeviceClientStatus.PROVISIONING_DEVICE_STATUS_DISABLED
        || provisioningStatus.provisioningDeviceClientRegistrationInfoClient
            .getProvisioningDeviceClientStatus() == ProvisioningDeviceClientStatus.PROVISIONING_DEVICE_STATUS_FAILED) {
      log.error("Registration error, bailing out", provisioningStatus.exception);
      break;
    }
    log.info("Waiting for Provisioning Service to register");
    Thread.sleep(10000);
  }

  if (provisioningDeviceClient != null) {
    provisioningDeviceClient.closeNow();
  }

  if (provisioningStatus.provisioningDeviceClientRegistrationInfoClient
      .getProvisioningDeviceClientStatus() == ProvisioningDeviceClientStatus.PROVISIONING_DEVICE_STATUS_ASSIGNED) {
    log.info("IotHUb Uri : " + provisioningStatus.provisioningDeviceClientRegistrationInfoClient.getIothubUri());
    log.info("Device ID : " + provisioningStatus.provisioningDeviceClientRegistrationInfoClient.getDeviceId());
  }
} catch (ProvisioningDeviceClientException | InterruptedException e) {
  log.error("Provisioning Device Client threw an exception", e);
  if (provisioningDeviceClient != null) {
    provisioningDeviceClient.closeNow();
  }
}

```

# Console log of the issue:

```
09:29:26.766 [Thread-3] INFO  IotHub - 290 - Endorsement Key : 
<Endorsement key>
09:29:26.769 [Thread-3] INFO  IotHub - 291 - Registration Id : 
<registration id>
09:29:26.905 [Thread-3] INFO  IotHub - 226 - Waiting for Provisioning Service to register
09:29:36.911 [Thread-3] ERROR IotHub - 223 - Registration error, bailing out
java.util.concurrent.ExecutionException: tss.TpmException: TPM Exception: {COMMAND_CODE}
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at com.microsoft.azure.sdk.iot.provisioning.device.internal.task.ProvisioningTask.invokeRegister(ProvisioningTask.java:113)
	at com.microsoft.azure.sdk.iot.provisioning.device.internal.task.ProvisioningTask.call(ProvisioningTask.java:287)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: tss.TpmException: TPM Exception: {COMMAND_CODE}
	at tss.TpmBase.DispatchCommand(TpmBase.java:383)
	at tss.Tpm.EncryptDecrypt2(Tpm.java:513)
	at com.microsoft.azure.sdk.iot.provisioning.security.hsm.SecurityProviderTPMHsm.activateIdentityKey(SecurityProviderTPMHsm.java:338)
	at com.microsoft.azure.sdk.iot.provisioning.device.internal.task.RegisterTask.authenticateWithTPM(RegisterTask.java:243)
	at com.microsoft.azure.sdk.iot.provisioning.device.internal.task.RegisterTask.authenticateWithDPS(RegisterTask.java:303)
	at com.microsoft.azure.sdk.iot.provisioning.device.internal.task.RegisterTask.call(RegisterTask.java:331)
	at com.microsoft.azure.sdk.iot.provisioning.device.internal.task.RegisterTask.call(RegisterTask.java:35)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	... 4 common frames omitted

```

**Comment by timtay-microsoft** [comment]
Right now, this SDK uses the [EncryptDecrypt2](https://github.com/Azure/azure-iot-sdk-java/blob/25d04aa064ed7089714fb61fabdf0a1e5aea94e0/provisioning/security/tpm-provider/src/main/java/com/microsoft/azure/sdk/iot/provisioning/security/hsm/SecurityProviderTPMHsm.java#L338) command during the provisioning flow for the SecurityProviderTpmHsm class. If your TPM does not support this command, then the SecurityProviderTpmHsm won't work for that device.

I recommend implementing your own SecurityProvider class that extends from the [SecurityProviderTpm ](https://github.com/Azure/azure-iot-sdk-java/blob/master/provisioning/security/security-provider/src/main/java/com/microsoft/azure/sdk/iot/provisioning/security/SecurityProviderTpm.java)abstract class. That abstract class does not have any strict dependency on EncryptDecrypt2 and allows you the flexibility to use whatever commands your tpm has access to.

**Comment by timtay-microsoft** [comment]
@tdesmet are you still having any issues here?

**Comment by tdesmet** [comment]
No I am good thanks.

**Comment by az-iot-builder-01** [comment]
@tdesmet, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
