### ISSUE TITLE
Android Application throwing exception : java.io.IOException: Could not open the connection

### ISSUE THREAD

**Issue by rohitm53** [Azure/azure-iot-sdk-java#624]
Hi 

Whenever I m trying to connect to IOT hub from my android application , having following dependency .

implementation("com.microsoft.azure.sdk.iot:iot-device-client:1.16.0") {
    exclude module: 'azure-storage'
}
implementation "com.microsoft.azure.android:azure-storage-android:2.0.0"
implementation "org.apache.commons:commons-lang3:3.6"
api "com.microsoft.azure.sdk.iot:iot-service-client:1.16.1"
implementation 'com.microsoft.azure:notification-hubs-android-sdk:0.4@aar'
implementation 'com.microsoft.azure:azure-notifications-handler:1.0.1@aar'
I m getting following exception : 

Informations :
java.io.IOException: Could not open the connection
at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:164)
at com.microsoft.azure.sdk.iot.device.InternalClient.open(InternalClient.java:130)
at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:317)
at com.tomra.mhs.hh.mobile.clientManager.DeviceClientManager.connectDeviceToIOTHub(DeviceClientManager.java:150)
at com.tomra.mhs.hh.mobile.repository.DataRepository.connectToDevice(DataRepository.java:784)
at com.tomra.mhs.hh.mobile.appmodules.splashscreen.SplashInteractor.connectToDevice(SplashInteractor.java:50)
at com.tomra.mhs.hh.mobile.appmodules.splashscreen.SplashScrenViewModel.connectToDevice(SplashScrenViewModel.java:73)
at com.tomra.mhs.hh.mobile.appmodules.splashscreen.SplashScreenActivity.lambda$connectToIotHub$0(SplashScreenActivity.java:94)
at com.tomra.mhs.hh.mobile.appmodules.splashscreen.-$$Lambda$SplashScreenActivity$5jQzB_Om_vojPuEqYQ4KqUNIZVE.onDelayCompleted(Unknown Source:2)
at com.tomra.mhs.hh.mobile.appmodules.CommonUI.BaseActivity$7.run(BaseActivity.java:482)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6518)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Unable to subscribe to topic :devices/tnazeu-pd-mhs-device-101/messages/devicebound/#
at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:75)
at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.subscribe(Mqtt.java:286)
at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttMessaging.start(MqttMessaging.java:61)
at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:180)
at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:653)
at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.open(IotHubTransport.java:280)
at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:160)
... 16 more
Caused by: Timed out waiting for a response from the server (32000)
at org.eclipse.paho.client.mqttv3.internal.Token.waitForCompletion(Token.java:112)
at org.eclipse.paho.client.mqttv3.MqttToken.waitForCompletion(MqttToken.java:67)
at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.subscribe(Mqtt.java:281)
... 21 more

****  End of current Report ***
This is happening sometimes , not regularly , but I need to have the solution for this.

So can anybody help me in this.

Thanks,

Rohit

**Comment by timtay-microsoft** [comment]
Can you upgrade to the latest version of the device client library? 1.16.0 is a very old version.

That exception suggests that your device cannot reach IoT Hub and times out. Are you experiencing network problems?

**Comment by rohitm53** [comment]
> Can you upgrade to the latest version of the device client library? 1.16.0 is a very old version.
> 
> That exception suggests that your device cannot reach IoT Hub and times out. Are you experiencing network problems?
No My device has full network , but still it throws this exception.

**Comment by timtay-microsoft** [comment]
Do you get a similar exception when using AMQP or HTTP?

**Comment by timtay-microsoft** [comment]
We have a [PR](https://github.com/Azure/azure-iot-sdk-java/pull/612) that demonstrates our recommended connection status handling, including adding retry to the open call. I recommend looking into it.

If you are seeing this error only occasionally, then it is likely some network issue, and you will need to retry.

**Comment by shivaambi** [comment]
i am also facing the same issue i do have latest version

**Comment by timtay-microsoft** [comment]
@shivaambi do you see this error 100% of the time? Or only occasionally?

**Comment by rohitm53** [comment]
@timtay-microsoft  No , I m facing this exception occasionally, mean to say daily twice almost when we are using device for continuously 8 hours .

**Comment by timtay-microsoft** [comment]
If you are only occasionally seeing this exception, then it is likely just a network connectivity issue. I recommend upgrading to the latest version and adding some basic retry logic around your open calls.

**Comment by timtay-microsoft** [comment]
Closing this issue due to inactivity after providing mitigation steps

**Comment by az-iot-builder-01** [comment]
@rohitm53, @shivaambi, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by rohitm53** [comment]
> Can you upgrade to the latest version of the device client library? 1.16.0 is a very old version.
> 
> That exception suggests that your device cannot reach IoT Hub and times out. Are you experiencing network problems?

I have tried with latest version com.microsoft.azure.sdk.iot:iot-device-client:1.19.1 , but still getting same exception

**Comment by rohitm53** [comment]
> Closing this issue due to inactivity after providing mitigation steps
I have tried with different protocols such as AMQPS , but still not luck.

**Comment by ankitdutta170** [comment]
Hi @rohitm53. I am getting the same issue in same project. Can you tell me how you solved this?
