### ISSUE TITLE
AMPQ DeviceClient.open() never returns

### ISSUE THREAD

**Issue by mwm-twx** [Azure/azure-iot-sdk-java#70]
# OS / JVM Details
OS:  Linux; Fedora 25
Java:
  Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
  Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
SDK:
  Service:  1.0.11
  Device:  1.0.16

# Description of the issue:

1.  Create a device with the RegistryManager
2.  Retrieve the DeviceClient with AMQPS
3.  Call open()
4.  open() never returns

NOTE:  This code works if using MQTT instead of AMQPS

# Code sample exhibiting the issue:
```java
import com.microsoft.azure.iot.service.sdk.Device;
import com.microsoft.azure.iot.service.sdk.RegistryManager;
import com.microsoft.azure.iothub.DeviceClient;
import com.microsoft.azure.iothub.IotHubClientProtocol;

public class Deadlock {
    public static void main(String[] args) {
        String hubHostname = "";
        String registryPolicyName = "registryReadWrite";
        String registryPolicyKey = "";
        String deviceName = "Deadlock-" + System.currentTimeMillis();

        String registryConnectionString = new StringBuilder()
            .append("HostName=").append(hubHostname)
            .append(";SharedAccessKeyName=").append(registryPolicyName)
            .append(";SharedAccessKey=").append(registryPolicyKey)
            .toString();

        try {
            Device device = Device.createFromId(deviceName, null, null);
            RegistryManager registry = RegistryManager.createFromConnectionString(registryConnectionString);
            device = registry.addDevice(device);

            String deviceConnectionString = new StringBuilder()
                .append("HostName=").append(hubHostname)
                .append(";DeviceId=").append(device.getDeviceId())
                .append(";SharedAccessKey=").append(device.getPrimaryKey())
                .toString();

            DeviceClient client = new DeviceClient(deviceConnectionString, IotHubClientProtocol.AMQPS);
            client.open();
            client.close();
        } catch (Exception exc) {
            exc.printStackTrace();
        }
    }
}
```

# Thread is blocked
```
"main" #1 prio=5 os_prio=0 tid=0x00007f2a2800d800 nid=0x60d in Object.wait() [0x00007f2a2f6d0000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000071b472330> (a com.microsoft.azure.iothub.ObjectLock)
	at com.microsoft.azure.iothub.ObjectLock.waitLock(ObjectLock.java:9)
	at com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnection.open(AmqpsIotHubConnection.java:210)
	- locked <0x000000071b472330> (a com.microsoft.azure.iothub.ObjectLock)
	at com.microsoft.azure.iothub.transport.amqps.AmqpsTransport.open(AmqpsTransport.java:100)
	- locked <0x000000071b16cb38> (a com.microsoft.azure.iothub.transport.amqps.AmqpsTransport)
	at com.microsoft.azure.iothub.DeviceClient.open(DeviceClient.java:175)
	at Deadlock.main(Deadlock.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by JMayrbaeurl** [comment]
Did you wait for at least 3 minutes? That's the time out value to establish an AMQP connection. BTW. com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.onConnectionBound(Event) should get you out of the Object.wait, when the connection was successfully established.

**Comment by mwm-twx** [comment]
No, I didn't wait three minutes.  The same code works in seconds with MQTT or with AMQPS when using version 1.0.8 of the device client.

I realized after filing this issue that the maven artifacts had been renamed, but this issue is still valid against device-client 1.1.22 and service-client 1.2.16.

**Comment by JMayrbaeurl** [comment]
I checked the sample code with device client SDK 1.1.22 and service client SDK 1.2.16 on Java 8 on a windows machine and it works correctly showing the following output:

```
[INFO  - main] 2017-03-28 19:44:10,482 com.microsoft.azure.sdk.iot.device.DeviceClientConfig - DeviceClientConfig object is created successfully with IotHubName=jmiottesting, deviceID=Deadlock-1490723049314 , method name is <init> 
[INFO  - main] 2017-03-28 19:44:10,487 com.microsoft.azure.sdk.iot.device.DeviceClient - DeviceClient object is created successfully, method name is <init> 
[INFO  - main] 2017-03-28 19:44:10,488 com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsTransport - Opening the connection..., method name is open 
[INFO  - main] 2017-03-28 19:44:10,510 com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection - AmqpsIotHubConnection object is created successfully using port 5671 in <init> method 
[INFO  - main] 2017-03-28 19:44:10,513 com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection - SAS Token is created successfully, method name is openAsync 
[INFO  - main] 2017-03-28 19:44:10,514 com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection - Reactor is assigned to executor service, method name is openAsync 
[DEBUG - pool-2-thread-1] 2017-03-28 19:44:10,522 com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection - Entered in method onReactorInit
[DEBUG - pool-2-thread-1] 2017-03-28 19:44:10,527 com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection - Exited from method onReactorInit
[DEBUG - pool-2-thread-1] 2017-03-28 19:44:10,534 com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection - Entered in method onConnectionInit
[DEBUG - pool-2-thread-1] 2017-03-28 19:44:10,539 com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection - Exited from method onConnectionInit
[DEBUG - pool-2-thread-1] 2017-03-28 19:44:10,539 com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection - Entered in method onLinkInit
[DEBUG - pool-2-thread-1] 2017-03-28 19:44:10,542 com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection - Exited from method onLinkInit
[DEBUG - pool-2-thread-1] 2017-03-28 19:44:10,542 com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection - Entered in method onLinkInit
[DEBUG - pool-2-thread-1] 2017-03-28 19:44:10,543 com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection - Exited from method onLinkInit
[DEBUG - pool-2-thread-1] 2017-03-28 19:44:10,621 com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection - Entered in method onConnectionBound
[INFO  - main] 2017-03-28 19:44:10,676 com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsTransport - Connection has been opened, method name is open 
[DEBUG - pool-2-thread-1] 2017-03-28 19:44:10,676 com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection - Exited from method onConnectionBound
[INFO  - main] 2017-03-28 19:44:10,680 com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsTransport - Starting to close the connection..., method name is close 
[INFO  - main] 2017-03-28 19:44:10,680 com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection - Proton reactor has been stopped, method name is closeAsync 
[DEBUG - pool-2-thread-1] 2017-03-28 19:44:10,694 com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection - Entered in method onReactorFinal
[DEBUG - pool-2-thread-1] 2017-03-28 19:44:10,695 com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection - Exited from method onReactorFinal
[INFO  - main] 2017-03-28 19:44:10,695 com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection - Shutdown of executor service has started, method name is close 
[INFO  - main] 2017-03-28 19:44:10,696 com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection - Shutdown of executor service completed, method name is close 
[INFO  - main] 2017-03-28 19:44:10,696 com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsTransport - Connection has been closed, method name is close 
```

**Comment by JMayrbaeurl** [comment]
And the actual code looks like:

```java
package com.microsoft.azure.sdk.iot.jm.tests;

import com.microsoft.azure.sdk.iot.service.Device;
import com.microsoft.azure.sdk.iot.service.RegistryManager;
import com.microsoft.azure.sdk.iot.device.DeviceClient;
import com.microsoft.azure.sdk.iot.device.IotHubClientProtocol;

public class Deadlock {
	
    public static void main(String[] args) {
        String hubHostname = "jmiottesting.azure-devices.net";
        String registryPolicyName = "registryReadWrite";
        String registryPolicyKey = "";
        String deviceName = "Deadlock-" + System.currentTimeMillis();

        String registryConnectionString = new StringBuilder()
            .append("HostName=").append(hubHostname)
            .append(";SharedAccessKeyName=").append(registryPolicyName)
            .append(";SharedAccessKey=").append(registryPolicyKey)
            .toString();

        try {
            Device device = Device.createFromId(deviceName, null, null);
            RegistryManager registry = RegistryManager.createFromConnectionString(registryConnectionString);
            device = registry.addDevice(device);

            String deviceConnectionString = new StringBuilder()
                .append("HostName=").append(hubHostname)
                .append(";DeviceId=").append(device.getDeviceId())
                .append(";SharedAccessKey=").append(device.getPrimaryKey())
                .toString();

            DeviceClient client = new DeviceClient(deviceConnectionString, IotHubClientProtocol.AMQPS);
            client.open();
            client.close();
        } catch (Exception exc) {
            exc.printStackTrace();
        }
    }
}
```

**Comment by mwm-twx** [comment]
The reproduction code in this issue was extracted from parts of a larger application, which happens to have used the bouncycastle crypto libraries already.

Apparently, version 1.53 of the PEMReader is not happy with the DefaultCertificate used by the DeviceClient, though the specified version (1.47) is fine.

**Comment by prmathur-microsoft** [comment]
1.53 of bouncy castle has API breaking changes and we did not yet move to that in device client. Can you please see if you are at a state where you can use 1.47 until we make changes at our end ?

**Comment by mwm-twx** [comment]
We can use 1.47.

**Comment by prmathur-microsoft** [comment]
Thank you mwm-twx . Let us know if you are still seeing issues.
