### ISSUE TITLE
Android iot-device-client:1.20.0 minifyEnabled true fails: Duplicate jar entry [module-info.class]

### ISSUE THREAD

**Issue by devzeze** [Azure/azure-iot-sdk-java#707]
# Description of the issue:
Build of app with latest iot-device-client (also fails with older) with minifyEnabled true fails.

# Code sample exhibiting the issue:

    android {
        compileSdkVersion 29
        buildToolsVersion '29.0.0'
        defaultConfig {
            minSdkVersion 23
            targetSdkVersion 29
            versionCode 1
            multiDexEnabled true
    
        testOptions {
        unitTests.includeAndroidResources = true
        }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    packagingOptions {
        exclude "META-INF/MSFTSIG.SF"
        exclude "META-INF/MSFTSIG.RSA"
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'thirdpartynotice.txt'
    }

    lintOptions {
        ignore 'InvalidPackage'
    }
    ...
        implementation('com.microsoft.azure.sdk.iot:iot-device-client:1.20.0') { exclude module: 'azure-storage' }
        implementation 'com.microsoft.azure.sdk.iot.provisioning:provisioning-device-client:1.7.1'
        implementation 'com.microsoft.azure.sdk.iot.provisioning.security:x509-provider:1.1.3'
        implementation 'com.microsoft.azure.android:azure-storage-android:2.0.0@aar'
    }

# The fail is specially related with version of gradle

       dependencies {
           classpath 'com.android.tools.build:gradle:3.3.2'
   
           // NOTE: Do not place your application dependencies here; they belong
           // in the individual module build.gradle files
       }

# Console log of the issue:

Warning: Exception while processing task java.io.IOException: Can't write [/Users/jose/Documents/rep/cloud_rep_android/mobile_client/app/build/intermediates/transforms/proguard/production/release/0.jar] (Can't read [/Users/jose/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-commons/7.1/431dc677cf5c56660c1c9004870de1ed1ea7ce6c/asm-commons-7.1.jar(;;;;;;;**.class)] (Duplicate jar entry [module-info.class]))
Thread(Tasks limiter_5): destruction

> Task :app:transformClassesAndResourcesWithProguardForProductionRelease FAILED

FAILURE: Build failed with an exception.

# Result of the scan of build fail

> Job failed, see logs for details
> > Can't write [/Users/jose/Documents/rep/cloud_rep_android/mobile_client/app/build/intermediates/transforms/proguard/production/release/0.jar] (Can't read [/Users/jose/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-commons/7.1/431dc677cf5c56660c1c9004870de1ed1ea7ce6c/asm-commons-7.1.jar(;;;;;;;**.class)] (Duplicate jar entry [module-info.class]))
>   > Can't read [/Users/jose/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-commons/7.1/431dc677cf5c56660c1c9004870de1ed1ea7ce6c/asm-commons-7.1.jar(;;;;;;;**.class)] (Duplicate jar entry [module-info.class])
>     > Duplicate jar entry [module-info.class]
> 

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesAndResourcesWithProguardForProductionRelease'.Open stacktrace
Caused by: java.lang.RuntimeException: Job failed, see logs for detailsOpen stacktrace
Caused by: java.io.IOException: Can't write [/Users/jose/Documents/rep/cloud_rep_android/mobile_client/app/build/intermediates/transforms/proguard/production/release/0.jar] (Can't read [/Users/jose/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-commons/7.1/431dc677cf5c56660c1c9004870de1ed1ea7ce6c/asm-commons-7.1.jar(;;;;;;;**.class)] (Duplicate jar entry [module-info.class]))Open stacktrace
Caused by: java.io.IOException: Can't read [/Users/jose/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-commons/7.1/431dc677cf5c56660c1c9004870de1ed1ea7ce6c/asm-commons-7.1.jar(;;;;;;;**.class)] (Duplicate jar entry [module-info.class])Open stacktrace
Caused by: java.io.IOException: Duplicate jar entry [module-info.class]Close stacktrace
at proguard.io.ZipOutput.createOutputStream(ZipOutput.java:155)
at proguard.io.ZipOutput.createOutputStream(ZipOutput.java:120)
at proguard.io.JarWriter.createOutputStream(JarWriter.java:137)
at proguard.io.FilteredDataEntryWriter.createOutputStream(FilteredDataEntryWriter.java:111)
at proguard.io.FilteredDataEntryWriter.createOutputStream(FilteredDataEntryWriter.java:111)
at proguard.io.ClassDataEntryWriter.createOutputStream(ClassDataEntryWriter.java:93)
at proguard.io.ExtraDataEntryWriter.createOutputStream(ExtraDataEntryWriter.java:135)
at proguard.io.IdleRewriter.read(IdleRewriter.java:49)
at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
at proguard.io.JarReader.read(JarReader.java:83)
at proguard.io.DirectoryPump.readFiles(DirectoryPump.java:65)
at proguard.io.DirectoryPump.pumpDataEntries(DirectoryPump.java:53)
at proguard.InputReader.readInput(InputReader.java:210)
at proguard.InputReader.readInput(InputReader.java:184)
at proguard.OutputWriter.writeOutput(OutputWriter.java:191)
at proguard.OutputWriter.execute(OutputWriter.java:89)
at proguard.ProGuard.writeOutput(ProGuard.java:515)
at proguard.ProGuard.execute(ProGuard.java:210)
at com.android.build.gradle.internal.transforms.BaseProguardAction.runProguard(BaseProguardAction.java:66)
at com.android.build.gradle.internal.transforms.ProGuardTransform.doMinification(ProGuardTransform.java:274)
at com.android.build.gradle.internal.transforms.ProGuardTransform.access$000(ProGuardTransform.java:67)
at com.android.build.gradle.internal.transforms.ProGuardTransform$1.run(ProGuardTransform.java:178)
at com.android.builder.tasks.Job.runTask(Job.java:47)
at com.android.build.gradle.tasks.SimpleWorkQueue$EmptyThreadContext.runTask(SimpleWorkQueue.java:41)
at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:282)

**Comment by timtay-microsoft** [comment]
Upgrading your gradle version solves this issue, so I don't see this as a bug with this SDK. Closing this issue.

**Comment by az-iot-builder-01** [comment]
@devzeze, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
