### ISSUE TITLE
Fatal Exception while attempting reconnect to IoT Hub Transport

### ISSUE THREAD

**Issue by mmacagno** [Azure/azure-iot-sdk-java#817]
- OS and version used: Android 10
- Package version: 

```
    implementation 'androidx.multidex:multidex:2.0.1'
    api 'com.microsoft.azure.sdk.iot:iot-device-client:1.18.0'
```

- transmission protocol: MQTT

We are getting sporadic crash reports coming from within the internals of the java MQTT implementation.
 
Have you seen this? Not sure we can trap them and how to recover from them.

`
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.eclipse.paho.client.mqttv3.f.e()' on a null object reference
       at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.subscribe(Mqtt.java:282)
       at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttMessaging.start(MqttMessaging.java:62)
       at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.a(MqttIotHubConnection.java:187)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:707)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.singleReconnectAttempt(IotHubTransport.java:834)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.reconnect(IotHubTransport.java:783)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.b(IotHubTransport.java:738)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.onConnectionLost(IotHubTransport.java:201)
       at com.microsoft.azure.sdk.iot.device.transport.ReconnectionNotifier$1.run(ReconnectionNotifier.java:21)
       at java.lang.Thread.run(Thread.java:919)
`

AB#7500965

**Comment by timtay-microsoft** [comment]
Have you tried upgrading to the latest SDK version (1.23.0)? And if you still see it, can you attach some SDK logs? Instructions on how to capture these logs is [here](https://github.com/Azure/azure-iot-sdk-java/blob/master/logging.md)

And can you add more context on when/how often you see this crash? Is it upon reconnection, or is it during initial open?

**Comment by mmacagno** [comment]
No. I can't upgrade due to #784. Need to make a change first.
I receive these logs from Firebase/Crashlytics, it's sporadic. Have received 13 occurrences so far.

![image](https://user-images.githubusercontent.com/2315384/85451814-1bb34a00-b54f-11ea-9698-fbfc5e0864bc.png)

**Comment by timtay-microsoft** [comment]
Are you able to provide the SDK logs from around the time you see this crash? Windows/Linux instructions can be found [here](https://github.com/Azure/azure-iot-sdk-java/blob/master/logging.md) but you'll need an Android logging framework to capture our SLF4J logs

**Comment by timtay-microsoft** [comment]
I do have some vague memories of seeing this NPE from time to time in the past, but we haven't seen this recently. I understand there is something else keeping you from upgrading, but I would still recommend it.

**Comment by timtay-microsoft** [comment]
@mmacagno are you still seeing this issue after upgrading?

**Comment by timtay-microsoft** [comment]
Closing this issue due to inactivity

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, @mmacagno, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
