### ISSUE TITLE
[Bug Report] Connection drops after a few hours ("force detached. Code: RenewToken")

### ISSUE THREAD

**Issue by sticksen** [Azure/azure-iot-sdk-java#880]
# Description
I´m using the example in 
https://github.com/Azure-Samples/azure-iot-samples-java/tree/master/iot-hub/Quickstarts/read-d2c-messages
to connect to the IoTHub Eventhub. At first it all works fine, but after a few hours the connection drops with the following error messages in the log.
Neither the `completed`, `error` or any other lambda is called by the Reactive chain, so I don´t see any chance to recover in my code currently.

What is the preferred way to handle this?

```
2020-08-04 18:23:38.923 ERROR 6 --- [       single-1] c.a.c.a.implementation.ReactorReceiver   : connectionId[MF_8603c0_1596534787788] linkName[all_573270_1596534787852-2] entityPath[xxx-iothub-westeurope/ConsumerGroups/$Default/Partitions/2] Error occurred in link.
The link 'all_573270_1596534787852-2' is force detached. Code: RenewToken. Details: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://iothub-xxx.servicebus.windows.net/xxx-iothub-westeurope/consumergroups/$default/partitions/2'.. TrackingId:4f81ccfd8dbe4e928c4826d9a782bc5c_G6, SystemTracker:gateway5, Timestamp:2020-08-04T18:23:38, errorContext[NAMESPACE: iothub-xxx.servicebus.windows.net, PATH: xxx-iothub-westeurope/ConsumerGroups/$Default/Partitions/2, REFERENCE_ID: all_573270_1596534787852-2, LINK_CREDIT: 485]
2020-08-04 18:23:38.926 ERROR 6 --- [       single-1] c.a.c.a.i.ReactorDispatcher              : ReactorDispatcher instance is closed.
2020-08-04 18:23:38.927 ERROR 6 --- [       single-1] reactor.core.publisher.Operators         : Operator called default onErrorDropped

java.util.concurrent.RejectedExecutionException: ReactorDispatcher instance is closed.
	at com.azure.core.amqp.implementation.ReactorDispatcher.throwIfSchedulerError(ReactorDispatcher.java:93) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorDispatcher.invoke(ReactorDispatcher.java:68) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorReceiver.dispose(ReactorReceiver.java:169) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorSession$LinkSubscription.dispose(ReactorSession.java:600) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorSession.removeLink(ReactorSession.java:336) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorSession.lambda$getSubscription$28(ReactorSession.java:564) ~[azure-core-amqp-1.3.0.jar!/:na]
	at reactor.core.publisher.LambdaSubscriber.onError(LambdaSubscriber.java:149) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replayNormal(FluxReplay.java:802) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replay(FluxReplay.java:898) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.ReplayProcessor.onError(ReplayProcessor.java:460) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxCreate$BaseSink.error(FluxCreate.java:452) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxCreate$SerializedSink.drainLoop(FluxCreate.java:229) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxCreate$SerializedSink.drain(FluxCreate.java:205) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxCreate$SerializedSink.error(FluxCreate.java:181) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at com.azure.core.amqp.implementation.ReactorReceiver.lambda$new$5(ReactorReceiver.java:91) ~[azure-core-amqp-1.3.0.jar!/:na]
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.UnicastProcessor.drainRegular(UnicastProcessor.java:240) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.UnicastProcessor.drain(UnicastProcessor.java:312) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.UnicastProcessor.onNext(UnicastProcessor.java:386) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxCreate$IgnoreSink.next(FluxCreate.java:618) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:153) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at com.azure.core.amqp.implementation.handler.Handler.onNext(Handler.java:54) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.handler.LinkHandler.processOnClose(LinkHandler.java:93) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.handler.LinkHandler.handleRemoteLinkClosed(LinkHandler.java:108) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.handler.LinkHandler.onLinkRemoteClose(LinkHandler.java:50) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.handler.ReceiveLinkHandler.onLinkRemoteClose(ReceiveLinkHandler.java:18) ~[azure-core-amqp-1.3.0.jar!/:na]
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176) ~[proton-j-0.33.4.jar!/:na]
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) ~[proton-j-0.33.4.jar!/:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324) ~[proton-j-0.33.4.jar!/:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291) ~[proton-j-0.33.4.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:82) ~[azure-core-amqp-1.3.0.jar!/:na]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2020-08-04 18:23:38.940 ERROR 6 --- [       single-1] c.a.c.a.i.ReactorDispatcher              : ReactorDispatcher instance is closed.
2020-08-04 18:23:38.941 ERROR 6 --- [       single-1] reactor.core.publisher.Operators         : Operator called default onErrorDropped

java.util.concurrent.RejectedExecutionException: ReactorDispatcher instance is closed.
	at com.azure.core.amqp.implementation.ReactorDispatcher.throwIfSchedulerError(ReactorDispatcher.java:93) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorDispatcher.invoke(ReactorDispatcher.java:68) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorReceiver.addCredits(ReactorReceiver.java:119) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.messaging.eventhubs.implementation.AmqpReceiveLinkProcessor.onNext(AmqpReceiveLinkProcessor.java:156) ~[azure-messaging-eventhubs-5.1.2.jar!/:na]
	at com.azure.messaging.eventhubs.implementation.AmqpReceiveLinkProcessor.onNext(AmqpReceiveLinkProcessor.java:31) ~[azure-messaging-eventhubs-5.1.2.jar!/:na]
	at reactor.core.publisher.FluxRepeatPredicate$RepeatPredicateSubscriber.onNext(FluxRepeatPredicate.java:79) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.Operators$MonoSubscriber.request(Operators.java:1799) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:2046) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at com.azure.messaging.eventhubs.implementation.AmqpReceiveLinkProcessor.requestUpstream(AmqpReceiveLinkProcessor.java:357) ~[azure-messaging-eventhubs-5.1.2.jar!/:na]
	at com.azure.messaging.eventhubs.implementation.AmqpReceiveLinkProcessor.lambda$onNext$2(AmqpReceiveLinkProcessor.java:186) ~[azure-messaging-eventhubs-5.1.2.jar!/:na]
	at reactor.core.publisher.LambdaSubscriber.onComplete(LambdaSubscriber.java:132) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replayNormal(FluxReplay.java:805) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replay(FluxReplay.java:898) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.ReplayProcessor.onComplete(ReplayProcessor.java:475) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxCreate$BaseSink.complete(FluxCreate.java:438) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxCreate$SerializedSink.drainLoop(FluxCreate.java:239) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxCreate$SerializedSink.drain(FluxCreate.java:205) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxCreate$SerializedSink.complete(FluxCreate.java:196) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at com.azure.core.amqp.implementation.ReactorReceiver.dispose(ReactorReceiver.java:163) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorSession$LinkSubscription.dispose(ReactorSession.java:600) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorSession.lambda$dispose$4(ReactorSession.java:154) ~[azure-core-amqp-1.3.0.jar!/:na]
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603) ~[na:na]
	at com.azure.core.amqp.implementation.ReactorSession.dispose(ReactorSession.java:154) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorConnection$SessionSubscription.dispose(ReactorConnection.java:430) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorConnection.removeSession(ReactorConnection.java:259) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorConnection.dispose(ReactorConnection.java:286) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.messaging.eventhubs.implementation.EventHubReactorAmqpConnection.dispose(EventHubReactorAmqpConnection.java:144) ~[azure-messaging-eventhubs-5.1.2.jar!/:na]
	at com.azure.core.amqp.implementation.AmqpChannelProcessor.close(AmqpChannelProcessor.java:308) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.AmqpChannelProcessor.setAndClearChannel(AmqpChannelProcessor.java:297) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.AmqpChannelProcessor.lambda$onNext$2(AmqpChannelProcessor.java:103) ~[azure-core-amqp-1.3.0.jar!/:na]
	at reactor.core.publisher.LambdaSubscriber.onError(LambdaSubscriber.java:149) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replayNormal(FluxReplay.java:802) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replay(FluxReplay.java:898) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.ReplayProcessor.onError(ReplayProcessor.java:460) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at com.azure.core.amqp.implementation.ReactorConnection$ReactorExceptionHandler.onConnectionError(ReactorConnection.java:382) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:126) ~[azure-core-amqp-1.3.0.jar!/:na]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2020-08-04 18:23:38.942 ERROR 6 --- [       single-1] reactor.core.scheduler.Schedulers        : Scheduler worker in group main failed with an uncaught exception

java.util.concurrent.RejectedExecutionException: ReactorDispatcher instance is closed.
	at com.azure.core.amqp.implementation.ReactorDispatcher.throwIfSchedulerError(ReactorDispatcher.java:93) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorDispatcher.invoke(ReactorDispatcher.java:68) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorReceiver.addCredits(ReactorReceiver.java:119) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.messaging.eventhubs.implementation.AmqpReceiveLinkProcessor.onNext(AmqpReceiveLinkProcessor.java:156) ~[azure-messaging-eventhubs-5.1.2.jar!/:na]
	at com.azure.messaging.eventhubs.implementation.AmqpReceiveLinkProcessor.onNext(AmqpReceiveLinkProcessor.java:31) ~[azure-messaging-eventhubs-5.1.2.jar!/:na]
	at reactor.core.publisher.FluxRepeatPredicate$RepeatPredicateSubscriber.onNext(FluxRepeatPredicate.java:79) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.Operators$MonoSubscriber.request(Operators.java:1799) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:2046) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at com.azure.messaging.eventhubs.implementation.AmqpReceiveLinkProcessor.requestUpstream(AmqpReceiveLinkProcessor.java:357) ~[azure-messaging-eventhubs-5.1.2.jar!/:na]
	at com.azure.messaging.eventhubs.implementation.AmqpReceiveLinkProcessor.lambda$onNext$2(AmqpReceiveLinkProcessor.java:186) ~[azure-messaging-eventhubs-5.1.2.jar!/:na]
	at reactor.core.publisher.LambdaSubscriber.onComplete(LambdaSubscriber.java:132) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replayNormal(FluxReplay.java:805) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replay(FluxReplay.java:898) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.ReplayProcessor.onComplete(ReplayProcessor.java:475) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxCreate$BaseSink.complete(FluxCreate.java:438) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxCreate$SerializedSink.drainLoop(FluxCreate.java:239) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxCreate$SerializedSink.drain(FluxCreate.java:205) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxCreate$SerializedSink.complete(FluxCreate.java:196) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at com.azure.core.amqp.implementation.ReactorReceiver.dispose(ReactorReceiver.java:163) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorSession$LinkSubscription.dispose(ReactorSession.java:600) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorSession.lambda$dispose$4(ReactorSession.java:154) ~[azure-core-amqp-1.3.0.jar!/:na]
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603) ~[na:na]
	at com.azure.core.amqp.implementation.ReactorSession.dispose(ReactorSession.java:154) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorConnection$SessionSubscription.dispose(ReactorConnection.java:430) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorConnection.removeSession(ReactorConnection.java:259) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorConnection.dispose(ReactorConnection.java:286) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.messaging.eventhubs.implementation.EventHubReactorAmqpConnection.dispose(EventHubReactorAmqpConnection.java:144) ~[azure-messaging-eventhubs-5.1.2.jar!/:na]
	at com.azure.core.amqp.implementation.AmqpChannelProcessor.close(AmqpChannelProcessor.java:308) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.AmqpChannelProcessor.setAndClearChannel(AmqpChannelProcessor.java:297) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.AmqpChannelProcessor.lambda$onNext$2(AmqpChannelProcessor.java:103) ~[azure-core-amqp-1.3.0.jar!/:na]
	at reactor.core.publisher.LambdaSubscriber.onError(LambdaSubscriber.java:149) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replayNormal(FluxReplay.java:802) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replay(FluxReplay.java:898) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.publisher.ReplayProcessor.onError(ReplayProcessor.java:460) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at com.azure.core.amqp.implementation.ReactorConnection$ReactorExceptionHandler.onConnectionError(ReactorConnection.java:382) ~[azure-core-amqp-1.3.0.jar!/:na]
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:126) ~[azure-core-amqp-1.3.0.jar!/:na]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2020-08-04 18:31:01.378 ERROR 6 --- [     parallel-1] c.a.c.a.i.ReactorDispatcher              : ReactorDispatcher instance is closed.
2020-08-04 18:31:01.383 ERROR 6 --- [     parallel-1] c.a.c.a.i.ActiveClientTokenManager       : Error occurred while refreshing token that is not retriable. Not scheduling refresh task. Use ActiveClientTokenManager.authorize() to schedule task again. audience[amqp://iothub-xxx.servicebus.windows.net/xxx-iothub-westeurope/ConsumerGroups/$Default/Partitions/0] scopes[amqp://iothub-xxx.servicebus.windows.net/xxx-iothub-westeurope/ConsumerGroups/$Default/Partitions/0]
ReactorDispatcher instance is closed.
2020-08-04 18:31:01.425 ERROR 6 --- [     parallel-1] c.a.c.a.i.ReactorDispatcher              : ReactorDispatcher instance is closed.
2020-08-04 18:31:01.427 ERROR 6 --- [     parallel-1] c.a.c.a.i.ActiveClientTokenManager       : Error occurred while refreshing token that is not retriable. Not scheduling refresh task. Use ActiveClientTokenManager.authorize() to schedule task again. audience[amqp://iothub-xxx.servicebus.windows.net/xxx-iothub-westeurope/ConsumerGroups/$Default/Partitions/1] scopes[amqp://iothub-xxx.servicebus.windows.net/xxx-iothub-westeurope/ConsumerGroups/$Default/Partitions/1]
ReactorDispatcher instance is closed.
```

# Context

- **OS and version used:** Ubuntu
- **Java runtime used:** 11
- **SDK version used:** 5.1.2

AB#7890917

**Comment by timtay-microsoft** [comment]
That sample and the logs you provided only reference the [Event Hub's sdk](https://github.com/Azure/azure-event-hubs-java/issues). This repo is for the IoT Hub sdks, so you'll need to file this issue on the linked page instead

**Comment by az-iot-builder-01** [comment]
@sticksen, @timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by timtay-microsoft** [comment]
The latest eventhub code is maintained [here](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/eventhubs), so you may have more luck filing the issue to this repo rather than the one above

**Comment by sticksen** [comment]
@timtay-microsoft The repo where the sample code (which I used to build my piece of code) resides (https://github.com/Azure-Samples/azure-iot-samples-java/tree/master/iot-hub/Quickstarts/read-d2c-messages) is leading me directly to this Repo right here. :)
This can be seen exactly here: https://github.com/Azure-Samples/azure-iot-samples-java#need-support

So maybe there´s a need for an updated link there? 👀

**Comment by timtay-microsoft** [comment]
Most of that repo is for IoT Hub samples, but that one sample you are using only uses the Event Hub SDK to read messages from the built-in eventhub for your IoT Hub. I'll see about adding a link to the eventhub SDK for that sample in particular
