### ISSUE TITLE
Make Amqp layer timeouts configurable

### ISSUE THREAD

**Issue by EinarBergseth** [Azure/azure-iot-sdk-java#906]
# Context

- **OS and version used:** Linux version 4.4.187 (build@a78bfeb6277f) (gcc version 7.4.0 (Buildroot 2019.02.2-svn3578) )
- **Java runtime used:** Java(TM) SE Embedded Runtime Environment (build 1.8.0_251-b08, profile compact2, headless)
- **SDK version used:** iot-device-client 1.25.0

## Description of the issue
We are experiencing a lot of: com.microsoft.azure.sdk.iot.device.exceptions.TransportException: Timed out waiting for authentication session to open when opening an AMQPS session. I have tracked this down to AmqpsIotHubConnection.MAX_WAIT_TO_OPEN_AUTHENTICATION_SESSION which is set to 20 seconds. This is too low for our rather slow IoT devices. I have tested to increase this constant to 60 seconds. This seems to have solved the problem. Can you please increase this timeout? Or perhaps make it configurable?

## Console log of the issue
java.io.IOException: Failed to open connection with AMQPS
        at e2u.gateway.commandservice.CommandServiceImpl.openConnection(CommandServiceImpl.java:77)
        at e2u.gateway.commandservice.CommandServiceImpl.open(CommandServiceImpl.java:50)
        at e2u.gateway.commandservice.CommandAndControlModule.lambda$startIotHubConnectTask$0(CommandAndControlModule.java:140)
        at e2u.gateway.common.system.E2UExecutor.lambda$scheduleWithFixedDelay$4(E2UExecutor.java:147)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Could not open the connection
        at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:160)
        at com.microsoft.azure.sdk.iot.device.InternalClient.open(InternalClient.java:146)
        at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:395)
        at e2u.gateway.commandservice.CommandServiceConnectionImpl.open(CommandServiceConnectionImpl.java:40)
        at e2u.gateway.commandservice.CommandServiceImpl.openConnection(CommandServiceImpl.java:68)
        ... 10 more
Caused by: com.microsoft.azure.sdk.iot.device.exceptions.TransportException: Timed out waiting for authentication session to open
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.closeConnectionWithException(AmqpsIotHubConnection.java:686)
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.open(AmqpsIotHubConnection.java:143)
        at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:785)
        at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.open(IotHubTransport.java:325)
        at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:156)
        ... 14 more

AB#8137491

**Comment by timtay-microsoft** [comment]
This would be a good enhancement to make, sure. We'll look into making this timeout (and a few other amqp specific timeouts) configurable for you

**Comment by timtay-microsoft** [comment]
Once we add this enhancement, I'd like to make our e2e tests use longer timeouts than our current defaults. We see this same exception from time to time in our nightly builds.

**Comment by timtay-microsoft** [comment]
It'll also be a good idea to reference these new APIs in the exceptions that currently throw for the timeouts. For most users, "timed out waiting for authentication links to open" doesn't really tell them what they need to do to avoid the issue in the future. Ideally the error would tell them that the timeout value is configurable using this new API

**Comment by timtay-microsoft** [comment]
We have now released device client version 1.27.0 that contains this feature, so I'm closing this issue. Feel free to open a new issue if you still hit any issues here

**Comment by az-iot-builder-01** [comment]
@EinarBergseth, @timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
