### ISSUE TITLE
java.io.IOException: Connection failed to be established

### ISSUE THREAD

**Issue by aindriu** [Azure/azure-iot-sdk-java#91]
Hi, I am using the latest iot-service-client to send a message to a device
Using Windows 7 and latest Java version.

Here is my code. I got the connection string from the devices tab under the microsoft azure portal so I'm sure it's correct.

This is the error I get - it can't seem to connect - Please help!
java.io.IOException: Connection failed to be established
	at com.microsoft.azure.sdk.iot.service.transport.amqps.AmqpSendHandler.sendComplete(AmqpSendHandler.java:340)
	at com.microsoft.azure.sdk.iot.service.transport.amqps.AmqpSend.send(AmqpSend.java:125)
	at com.microsoft.azure.sdk.iot.service.ServiceClient.send(ServiceClient.java:126)
	at testreceiver.Cloud2DeviceSender.main(Cloud2DeviceSender.java:30)

import com.microsoft.azure.sdk.iot.service.*;
import com.microsoft.azure.sdk.iot.service.exceptions.IotHubException;

import java.io.IOException;
import java.net.URISyntaxException;

public class Cloud2DeviceSender {

	private static final String connectionString = "HostName=riv.azure-devices.net;DeviceId=214279;SharedAccessKeyName=iothubowner;SharedAccessKey=pq1g+mm3+vUYjvb+PHWDJud8t4lPkyeQKiXXMd9FMM4=";
	private static final String deviceId = "214279";
	private static final IotHubServiceClientProtocol protocol = IotHubServiceClientProtocol.AMQPS;
	 
	public static void main(String[] args) {
		  ServiceClient serviceClient;
		try {
			serviceClient = ServiceClient.createFromConnectionString(
					     connectionString, protocol);
	

				   if (serviceClient != null) {
				     serviceClient.open();
				     FeedbackReceiver feedbackReceiver = serviceClient
				       .getFeedbackReceiver(deviceId);
				     if (feedbackReceiver != null) feedbackReceiver.open();

				     Message messageToSend = new Message("test message");
				     messageToSend.setDeliveryAcknowledgement(DeliveryAcknowledgement.Full);

				     serviceClient.send(deviceId, messageToSend);
				     System.out.println("Message sent to device");

				     FeedbackBatch feedbackBatch = feedbackReceiver.receive(10000);
				     if (feedbackBatch != null) {
				       System.out.println("Message feedback received, feedback time: "
				         + feedbackBatch.getEnqueuedTimeUtc().toString());
				     }

				     if (feedbackReceiver != null) feedbackReceiver.close();
				     serviceClient.close();
				   }
				 
		} catch (IOException | IotHubException | InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

}

**Comment by aindriu** [comment]
I got it working. Nevermind. I had to take the connectstring from the shared access key and not the device key.
