### ISSUE TITLE
OutOfMemoryError from CustomLogger when running on OSGI implementation Apache Felix

### ISSUE THREAD

**Issue by JMayrbaeurl** [Azure/azure-iot-sdk-java#93]
- **OS and version used:** <VERSION> 

- **Java runtime used:** 1.8 

- **SDK version used:** 1.1.24 

# Description of the issue:
Reported on behalf of partner Bosch Rexroth: Out of memory error when using the SDK with OSGI runtime implementation http://felix.apache.org/ . According to the stack trace (see below) the error is somehow caused by the CustomLogger class (at least the partner thinks so). It's obvisous that there are memory leaks in the code, probably coming from circular references that can be found in several places in the code. For more guidance on finding memory leaks see https://www.dynatrace.com/resources/ebooks/javabook/memory-leaks/.
Anyway. This is a critical bug, because the code stops working after running 12 hours or more.

# Code sample exhibiting the issue:

# Console log of the issue:

# Stack trace
```java
2017-04-25 00:51:03,084 ERROR [org.apache.felix.fileinstall] - In main loop, we have serious trouble
java.lang.OutOfMemoryError: Java heap space
	at java.util.HashSet.<init>(HashSet.java:105)
	at org.apache.felix.fileinstall.internal.WatcherScanner.scan(WatcherScanner.java:66)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:307)
2017-04-25 00:51:04,570 ERROR [com.boschrexroth.iiot.core.scheduler] - An error was detected during execution of Test
java.lang.OutOfMemoryError: Java heap space
	at java.util.LinkedHashMap.newNode(LinkedHashMap.java:256)
	at java.util.HashMap.putVal(HashMap.java:641)
	at java.util.HashMap.put(HashMap.java:611)
	at sun.util.resources.OpenListResourceBundle.loadLookup(OpenListResourceBundle.java:146)
	at sun.util.resources.OpenListResourceBundle.loadLookupTablesIfNecessary(OpenListResourceBundle.java:128)
	at sun.util.resources.OpenListResourceBundle.handleKeySet(OpenListResourceBundle.java:96)
	at java.util.ResourceBundle.containsKey(ResourceBundle.java:1807)
	at sun.util.locale.provider.LocaleResources.getTimeZoneNames(LocaleResources.java:263)
	at sun.util.locale.provider.TimeZoneNameProviderImpl.getDisplayNameArray(TimeZoneNameProviderImpl.java:124)
	at sun.util.locale.provider.TimeZoneNameProviderImpl.getDisplayName(TimeZoneNameProviderImpl.java:99)
	at sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter.getName(TimeZoneNameUtility.java:240)
	at sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter.getObject(TimeZoneNameUtility.java:198)
	at sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter.getObject(TimeZoneNameUtility.java:184)
	at sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObjectImpl(LocaleServiceProviderPool.java:281)
	at sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObject(LocaleServiceProviderPool.java:265)
	at sun.util.locale.provider.TimeZoneNameUtility.retrieveDisplayNamesImpl(TimeZoneNameUtility.java:166)
	at sun.util.locale.provider.TimeZoneNameUtility.retrieveDisplayName(TimeZoneNameUtility.java:137)
	at java.util.TimeZone.getDisplayName(TimeZone.java:400)
	at java.util.Date.toString(Date.java:1045)
	at java.util.Formatter$FormatSpecifier.printString(Formatter.java:2886)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2763)
	at java.util.Formatter.format(Formatter.java:2520)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at com.microsoft.azure.sdk.iot.device.CustomLogger.LogInfo(CustomLogger.java:22)
	at com.microsoft.azure.sdk.iot.device.Message.setExpiryTime(Message.java:360)
	at com.boschrexroth.iiot.processing.azure.AzurePublisher.process(AzurePublisher.java:350)
	at com.boschrexroth.iiot.core.scheduler.Processing.execute(Processing.java:282)
	at com.boschrexroth.iiot.core.scheduler.Scheduler.tick(Scheduler.java:138)
	at com.boschrexroth.iiot.core.scheduler.Scheduler.access$600(Scheduler.java:25)
	at com.boschrexroth.iiot.core.scheduler.Scheduler$SchedulerRunnable.run(Scheduler.java:219)
	at java.lang.Thread.run(Thread.java:745)
2017-04-25 00:51:38,903 ERROR [com.boschrexroth.iiot.core.scheduler] - An error was detected during execution of Test
java.lang.OutOfMemoryError: Java heap space
	at java.util.LinkedHashMap.newNode(LinkedHashMap.java:256)
	at java.util.HashMap.putVal(HashMap.java:630)
	at java.util.HashMap.put(HashMap.java:611)
	at sun.util.resources.OpenListResourceBundle.loadLookup(OpenListResourceBundle.java:146)
	at sun.util.resources.OpenListResourceBundle.loadLookupTablesIfNecessary(OpenListResourceBundle.java:128)
	at sun.util.resources.OpenListResourceBundle.handleKeySet(OpenListResourceBundle.java:96)
	at java.util.ResourceBundle.containsKey(ResourceBundle.java:1807)
	at sun.util.locale.provider.LocaleResources.getTimeZoneNames(LocaleResources.java:263)
	at sun.util.locale.provider.TimeZoneNameProviderImpl.getDisplayNameArray(TimeZoneNameProviderImpl.java:124)
	at sun.util.locale.provider.TimeZoneNameProviderImpl.getDisplayName(TimeZoneNameProviderImpl.java:99)
	at sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter.getName(TimeZoneNameUtility.java:240)
	at sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter.getObject(TimeZoneNameUtility.java:198)
	at sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter.getObject(TimeZoneNameUtility.java:184)
	at sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObjectImpl(LocaleServiceProviderPool.java:281)
	at sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObject(LocaleServiceProviderPool.java:265)
	at sun.util.locale.provider.TimeZoneNameUtility.retrieveDisplayNamesImpl(TimeZoneNameUtility.java:166)
	at sun.util.locale.provider.TimeZoneNameUtility.retrieveDisplayName(TimeZoneNameUtility.java:137)
	at java.util.TimeZone.getDisplayName(TimeZone.java:400)
	at java.util.Date.toString(Date.java:1045)
	at java.util.Formatter$FormatSpecifier.printString(Formatter.java:2886)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2763)
	at java.util.Formatter.format(Formatter.java:2520)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at com.microsoft.azure.sdk.iot.device.CustomLogger.LogInfo(CustomLogger.java:22)
	at com.microsoft.azure.sdk.iot.device.Message.setExpiryTime(Message.java:360)
	at com.boschrexroth.iiot.processing.azure.AzurePublisher.process(AzurePublisher.java:350)
	at com.boschrexroth.iiot.core.scheduler.Processing.execute(Processing.java:282)
	at com.boschrexroth.iiot.core.scheduler.Scheduler.tick(Scheduler.java:138)
	at com.boschrexroth.iiot.core.scheduler.Scheduler.access$600(Scheduler.java:25)
	at com.boschrexroth.iiot.core.scheduler.Scheduler$SchedulerRunnable.run(Scheduler.java:219)
	at java.lang.Thread.run(Thread.java:745)
2017-04-25 00:52:23,694 ERROR [org.apache.felix.fileinstall] - In main loop, we have serious trouble
java.lang.OutOfMemoryError: Java heap space
```

**Comment by prmathur-microsoft** [comment]
As there has been no repro or steps for this issue closing it. Feel free to reopen if you see this issue again.
